package yantuseed

// overseasUnivInfo holds QS ranking tier and location for an overseas university.
type overseasUnivInfo struct {
	Tier    string // "QS前50", "QS前100", "QS前200"
	Country string // e.g. "美国", "英国"
	Region  string // e.g. "北美", "欧洲", "亚洲"
}

// overseasUniversities maps both Chinese and English name keywords
// to QS 2026 ranking tier and location info. Source: QS World University Rankings 2026.
var overseasUniversities = map[string]overseasUnivInfo{
	"麻省理工学院": overseasUnivInfo{"QS前50", "美国", "北美"},
	"Massachusetts Institute of Technology (MIT)": overseasUnivInfo{"QS前50", "美国", "北美"},
	"帝国理工学院": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"Imperial College London": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"斯坦福大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"Stanford University": overseasUnivInfo{"QS前50", "美国", "北美"},
	"牛津大学": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"University of Oxford": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"哈佛大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"Harvard University": overseasUnivInfo{"QS前50", "美国", "北美"},
	"剑桥大学": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"University of Cambridge": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"苏黎世联邦理工学院": overseasUnivInfo{"QS前50", "瑞士", "欧洲"},
	"ETH Zurich (Swiss Federal Institute of Technology)": overseasUnivInfo{"QS前50", "瑞士", "欧洲"},
	"新加坡国立大学": overseasUnivInfo{"QS前50", "新加坡", "亚洲"},
	"National University of Singapore (NUS)": overseasUnivInfo{"QS前50", "新加坡", "亚洲"},
	"伦敦大学学院": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"UCL (University College London)": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"加州理工学院": overseasUnivInfo{"QS前50", "美国", "北美"},
	"California Institute of Technology (Caltech)": overseasUnivInfo{"QS前50", "美国", "北美"},
	"香港大学": overseasUnivInfo{"QS前50", "中国香港", "亚洲"},
	"The University of Hong Kong": overseasUnivInfo{"QS前50", "中国香港", "亚洲"},
	"南洋理工大学": overseasUnivInfo{"QS前50", "新加坡", "亚洲"},
	"Nanyang Technological University, Singapore (NTU Singapore)": overseasUnivInfo{"QS前50", "新加坡", "亚洲"},
	"芝加哥大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"University of Chicago": overseasUnivInfo{"QS前50", "美国", "北美"},
	"宾夕法尼亚大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"University of Pennsylvania": overseasUnivInfo{"QS前50", "美国", "北美"},
	"康奈尔大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"Cornell University": overseasUnivInfo{"QS前50", "美国", "北美"},
	"加州大学伯克利分校": overseasUnivInfo{"QS前50", "美国", "北美"},
	"University of California, Berkeley (UCB)": overseasUnivInfo{"QS前50", "美国", "北美"},
	"墨尔本大学": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"The University of Melbourne": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"新南威尔士大学": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"The University of New South Wales": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"耶鲁大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"Yale University": overseasUnivInfo{"QS前50", "美国", "北美"},
	"洛桑联邦理工学院": overseasUnivInfo{"QS前50", "瑞士", "欧洲"},
	"École Polytechnique Fédérale de Lausanne": overseasUnivInfo{"QS前50", "瑞士", "欧洲"},
	"慕尼黑工业大学": overseasUnivInfo{"QS前50", "德国", "欧洲"},
	"Technical University of Munich": overseasUnivInfo{"QS前50", "德国", "欧洲"},
	"约翰斯·霍普金斯大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"Johns Hopkins University": overseasUnivInfo{"QS前50", "美国", "北美"},
	"普林斯顿大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"Princeton University": overseasUnivInfo{"QS前50", "美国", "北美"},
	"悉尼大学": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"The University of Sydney": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"麦吉尔大学": overseasUnivInfo{"QS前50", "加拿大", "北美"},
	"McGill University": overseasUnivInfo{"QS前50", "加拿大", "北美"},
	"巴黎文理研究大学": overseasUnivInfo{"QS前50", "法国", "欧洲"},
	"PSL University": overseasUnivInfo{"QS前50", "法国", "欧洲"},
	"多伦多大学": overseasUnivInfo{"QS前50", "加拿大", "北美"},
	"University of Toronto": overseasUnivInfo{"QS前50", "加拿大", "北美"},
	"伦敦国王学院": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"King's College London (KCL)": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"澳大利亚国立大学": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"Australian National University": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"香港中文大学": overseasUnivInfo{"QS前50", "中国香港", "亚洲"},
	"The Chinese University of Hong Kong": overseasUnivInfo{"QS前50", "中国香港", "亚洲"},
	"爱丁堡大学": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"University of Edinburgh": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"曼彻斯特大学": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"The University of Manchester": overseasUnivInfo{"QS前50", "英国", "欧洲"},
	"莫纳什大学": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"Monash University": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"东京大学": overseasUnivInfo{"QS前50", "日本", "亚洲"},
	"The University of Tokyo": overseasUnivInfo{"QS前50", "日本", "亚洲"},
	"哥伦比亚大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"Columbia University": overseasUnivInfo{"QS前50", "美国", "北美"},
	"首尔国立大学": overseasUnivInfo{"QS前50", "韩国", "亚洲"},
	"Seoul National University": overseasUnivInfo{"QS前50", "韩国", "亚洲"},
	"不列颠哥伦比亚大学": overseasUnivInfo{"QS前50", "加拿大", "北美"},
	"University of British Columbia": overseasUnivInfo{"QS前50", "加拿大", "北美"},
	"巴黎综合理工学院": overseasUnivInfo{"QS前50", "法国", "欧洲"},
	"Institut Polytechnique de Paris": overseasUnivInfo{"QS前50", "法国", "欧洲"},
	"西北大学": overseasUnivInfo{"QS前50", "美国", "北美"},
	"Northwestern University": overseasUnivInfo{"QS前50", "美国", "北美"},
	"昆士兰大学": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"The University of Queensland": overseasUnivInfo{"QS前50", "澳大利亚", "大洋洲"},
	"香港科技大学": overseasUnivInfo{"QS前50", "中国香港", "亚洲"},
	"The Hong Kong University of Science and Technology": overseasUnivInfo{"QS前50", "中国香港", "亚洲"},
	"密歇根大学安娜堡分校": overseasUnivInfo{"QS前50", "美国", "北美"},
	"University of Michigan-Ann Arbor": overseasUnivInfo{"QS前50", "美国", "北美"},
	"加州大学洛杉矶分校": overseasUnivInfo{"QS前50", "美国", "北美"},
	"University of California, Los Angeles (UCLA)": overseasUnivInfo{"QS前50", "美国", "北美"},
	"代尔夫特理工大学": overseasUnivInfo{"QS前50", "荷兰", "欧洲"},
	"Delft University of Technology": overseasUnivInfo{"QS前50", "荷兰", "欧洲"},
	"延世大学": overseasUnivInfo{"QS前50", "韩国", "亚洲"},
	"Yonsei University": overseasUnivInfo{"QS前50", "韩国", "亚洲"},
	"布里斯托大学": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"University of Bristol": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"卡内基梅隆大学": overseasUnivInfo{"QS前100", "美国", "北美"},
	"Carnegie Mellon University": overseasUnivInfo{"QS前100", "美国", "北美"},
	"阿姆斯特丹大学": overseasUnivInfo{"QS前100", "荷兰", "欧洲"},
	"The University of Amsterdam": overseasUnivInfo{"QS前100", "荷兰", "欧洲"},
	"香港理工大学": overseasUnivInfo{"QS前100", "中国香港", "亚洲"},
	"The Hong Kong Polytechnic University": overseasUnivInfo{"QS前100", "中国香港", "亚洲"},
	"纽约大学": overseasUnivInfo{"QS前100", "美国", "北美"},
	"New York University (NYU)": overseasUnivInfo{"QS前100", "美国", "北美"},
	"伦敦政治经济学院": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"London School of Economics and Political Science (LSE)": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"京都大学": overseasUnivInfo{"QS前100", "日本", "亚洲"},
	"Kyoto University": overseasUnivInfo{"QS前100", "日本", "亚洲"},
	"慕尼黑大学": overseasUnivInfo{"QS前100", "德国", "欧洲"},
	"Ludwig-Maximilians-Universität München": overseasUnivInfo{"QS前100", "德国", "欧洲"},
	"马来亚大学": overseasUnivInfo{"QS前100", "马来西亚", "亚洲"},
	"Universiti Malaya (UM)": overseasUnivInfo{"QS前100", "马来西亚", "亚洲"},
	"鲁汶大学": overseasUnivInfo{"QS前100", "比利时", "欧洲"},
	"KU Leuven": overseasUnivInfo{"QS前100", "比利时", "欧洲"},
	"高丽大学": overseasUnivInfo{"QS前100", "韩国", "亚洲"},
	"Korea University": overseasUnivInfo{"QS前100", "韩国", "亚洲"},
	"杜克大学": overseasUnivInfo{"QS前100", "美国", "北美"},
	"Duke University": overseasUnivInfo{"QS前100", "美国", "北美"},
	"香港城市大学": overseasUnivInfo{"QS前100", "中国香港", "亚洲"},
	"City University of Hong Kong": overseasUnivInfo{"QS前100", "中国香港", "亚洲"},
	"台湾大学": overseasUnivInfo{"QS前100", "中国台湾", "亚洲"},
	"National Taiwan University (NTU)": overseasUnivInfo{"QS前100", "中国台湾", "亚洲"},
	"奥克兰大学": overseasUnivInfo{"QS前100", "新西兰", "大洋洲"},
	"The University of Auckland": overseasUnivInfo{"QS前100", "新西兰", "大洋洲"},
	"加州大学圣迭戈分校": overseasUnivInfo{"QS前100", "美国", "北美"},
	"University of California, San Diego (UCSD)": overseasUnivInfo{"QS前100", "美国", "北美"},
	"法赫德国王石油矿产大学": overseasUnivInfo{"QS前100", "沙特阿拉伯", "中东"},
	"King Fahd University of Petroleum & Minerals": overseasUnivInfo{"QS前100", "沙特阿拉伯", "中东"},
	"得克萨斯大学奥斯汀分校": overseasUnivInfo{"QS前100", "美国", "北美"},
	"University of Texas at Austin": overseasUnivInfo{"QS前100", "美国", "北美"},
	"布朗大学": overseasUnivInfo{"QS前100", "美国", "北美"},
	"Brown University": overseasUnivInfo{"QS前100", "美国", "北美"},
	"巴黎萨克雷大学": overseasUnivInfo{"QS前100", "法国", "欧洲"},
	"Université Paris-Saclay": overseasUnivInfo{"QS前100", "法国", "欧洲"},
	"伊利诺伊大学厄巴纳-香槟分校": overseasUnivInfo{"QS前100", "美国", "北美"},
	"University of Illinois at Urbana-Champaign": overseasUnivInfo{"QS前100", "美国", "北美"},
	"隆德大学": overseasUnivInfo{"QS前100", "瑞典", "欧洲"},
	"Lund University": overseasUnivInfo{"QS前100", "瑞典", "欧洲"},
	"索邦大学": overseasUnivInfo{"QS前100", "法国", "欧洲"},
	"Sorbonne University (merged from Paris IV & UPMC)": overseasUnivInfo{"QS前100", "法国", "欧洲"},
	"华威大学": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"The University of Warwick": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"都柏林三一学院": overseasUnivInfo{"QS前100", "爱尔兰", "欧洲"},
	"Trinity College Dublin, The University of Dublin": overseasUnivInfo{"QS前100", "爱尔兰", "欧洲"},
	"伯明翰大学": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"University of Birmingham": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"西澳大学": overseasUnivInfo{"QS前100", "澳大利亚", "大洋洲"},
	"The University of Western Australia": overseasUnivInfo{"QS前100", "澳大利亚", "大洋洲"},
	"瑞典皇家理工学院": overseasUnivInfo{"QS前100", "瑞典", "欧洲"},
	"KTH Royal Institute of Technology": overseasUnivInfo{"QS前100", "瑞典", "欧洲"},
	"格拉斯哥大学": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"University of Glasgow": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"海德堡大学": overseasUnivInfo{"QS前100", "德国", "欧洲"},
	"Ruprecht-Karls-Universität Heidelberg": overseasUnivInfo{"QS前100", "德国", "欧洲"},
	"华盛顿大学": overseasUnivInfo{"QS前100", "美国", "北美"},
	"University of Washington": overseasUnivInfo{"QS前100", "美国", "北美"},
	"阿德莱德大学": overseasUnivInfo{"QS前100", "澳大利亚", "大洋洲"},
	"Adelaide University": overseasUnivInfo{"QS前100", "澳大利亚", "大洋洲"},
	"宾夕法尼亚州立大学": overseasUnivInfo{"QS前100", "美国", "北美"},
	"Pennsylvania State University": overseasUnivInfo{"QS前100", "美国", "北美"},
	"布宜诺斯艾利斯大学": overseasUnivInfo{"QS前100", "阿根廷", "南美"},
	"Universidad de Buenos Aires": overseasUnivInfo{"QS前100", "阿根廷", "南美"},
	"东京工业大学": overseasUnivInfo{"QS前100", "日本", "亚洲"},
	"Tokyo Institute of Technology": overseasUnivInfo{"QS前100", "日本", "亚洲"},
	"利兹大学": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"University of Leeds": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"南安普顿大学": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"University of Southampton": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"波士顿大学": overseasUnivInfo{"QS前100", "美国", "北美"},
	"Boston University": overseasUnivInfo{"QS前100", "美国", "北美"},
	"柏林自由大学": overseasUnivInfo{"QS前100", "德国", "欧洲"},
	"Freie Universität Berlin": overseasUnivInfo{"QS前100", "德国", "欧洲"},
	"普渡大学": overseasUnivInfo{"QS前100", "美国", "北美"},
	"Purdue University": overseasUnivInfo{"QS前100", "美国", "北美"},
	"大阪大学": overseasUnivInfo{"QS前100", "日本", "亚洲"},
	"The University of Osaka": overseasUnivInfo{"QS前100", "日本", "亚洲"},
	"谢菲尔德大学": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"The University of Sheffield": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"乌普萨拉大学": overseasUnivInfo{"QS前100", "瑞典", "欧洲"},
	"Uppsala University": overseasUnivInfo{"QS前100", "瑞典", "欧洲"},
	"杜伦大学": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"Durham University": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"阿尔伯塔大学": overseasUnivInfo{"QS前100", "加拿大", "北美"},
	"University of Alberta": overseasUnivInfo{"QS前100", "加拿大", "北美"},
	"悉尼科技大学": overseasUnivInfo{"QS前100", "澳大利亚", "大洋洲"},
	"University of Technology Sydney": overseasUnivInfo{"QS前100", "澳大利亚", "大洋洲"},
	"诺丁汉大学": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"The University of Nottingham": overseasUnivInfo{"QS前100", "英国", "欧洲"},
	"卡尔斯鲁厄理工学院": overseasUnivInfo{"QS前100", "德国", "欧洲"},
	"Karlsruhe Institute of Technology (KIT)": overseasUnivInfo{"QS前100", "德国", "欧洲"},
	"米兰理工大学": overseasUnivInfo{"QS前100", "意大利", "欧洲"},
	"Politecnico di Milano": overseasUnivInfo{"QS前100", "意大利", "欧洲"},
	"苏黎世大学": overseasUnivInfo{"QS前100", "瑞士", "欧洲"},
	"University of Zurich (UZH)": overseasUnivInfo{"QS前100", "瑞士", "欧洲"},
	"哥本哈根大学": overseasUnivInfo{"QS前200", "丹麦", "欧洲"},
	"University of Copenhagen": overseasUnivInfo{"QS前200", "丹麦", "欧洲"},
	"浦项科技大学": overseasUnivInfo{"QS前200", "韩国", "亚洲"},
	"Pohang University of Science And Technology (POSTECH)": overseasUnivInfo{"QS前200", "韩国", "亚洲"},
	"乌得勒支大学": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"Utrecht University": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"莫斯科国立大学": overseasUnivInfo{"QS前200", "俄罗斯", "欧洲"},
	"Lomonosov Moscow State University": overseasUnivInfo{"QS前200", "俄罗斯", "欧洲"},
	"亚琛工业大学": overseasUnivInfo{"QS前200", "德国", "欧洲"},
	"Rheinisch-Westfälische Technische Hochschule Aachen": overseasUnivInfo{"QS前200", "德国", "欧洲"},
	"丹麦技术大学": overseasUnivInfo{"QS前200", "丹麦", "欧洲"},
	"Technical University of Denmark": overseasUnivInfo{"QS前200", "丹麦", "欧洲"},
	"圣保罗大学": overseasUnivInfo{"QS前200", "巴西", "南美"},
	"Universidade de São Paulo (USP)": overseasUnivInfo{"QS前200", "巴西", "南美"},
	"东北大学": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"Tohoku University": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"伦敦玛丽女王大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"Queen Mary University of London (QMUL)": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"威斯康星大学麦迪逊分校": overseasUnivInfo{"QS前200", "美国", "北美"},
	"University of Wisconsin-Madison": overseasUnivInfo{"QS前200", "美国", "北美"},
	"卡塔尔大学": overseasUnivInfo{"QS前200", "卡塔尔", "中东"},
	"Qatar University": overseasUnivInfo{"QS前200", "卡塔尔", "中东"},
	"圣安德鲁斯大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"University of St Andrews": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"阿尔托大学": overseasUnivInfo{"QS前200", "芬兰", "欧洲"},
	"Aalto University": overseasUnivInfo{"QS前200", "芬兰", "欧洲"},
	"加州大学戴维斯分校": overseasUnivInfo{"QS前200", "美国", "北美"},
	"University of California, Davis": overseasUnivInfo{"QS前200", "美国", "北美"},
	"智利天主教大学": overseasUnivInfo{"QS前200", "智利", "南美"},
	"Pontificia Universidad Católica de Chile": overseasUnivInfo{"QS前200", "智利", "南美"},
	"赫尔辛基大学": overseasUnivInfo{"QS前200", "芬兰", "欧洲"},
	"University of Helsinki": overseasUnivInfo{"QS前200", "芬兰", "欧洲"},
	"都柏林大学": overseasUnivInfo{"QS前200", "爱尔兰", "欧洲"},
	"University College Dublin": overseasUnivInfo{"QS前200", "爱尔兰", "欧洲"},
	"莱顿大学": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"Leiden University": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"莱斯大学": overseasUnivInfo{"QS前200", "美国", "北美"},
	"Rice University": overseasUnivInfo{"QS前200", "美国", "北美"},
	"奥斯陆大学": overseasUnivInfo{"QS前200", "挪威", "欧洲"},
	"University of Oslo": overseasUnivInfo{"QS前200", "挪威", "欧洲"},
	"滑铁卢大学": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"University of Waterloo": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"佐治亚理工学院": overseasUnivInfo{"QS前200", "美国", "北美"},
	"Georgia Institute of Technology": overseasUnivInfo{"QS前200", "美国", "北美"},
	"印度理工学院德里分校": overseasUnivInfo{"QS前200", "印度", "亚洲"},
	"Indian Institute of Technology Delhi (IITD)": overseasUnivInfo{"QS前200", "印度", "亚洲"},
	"皇家墨尔本理工大学": overseasUnivInfo{"QS前200", "澳大利亚", "大洋洲"},
	"RMIT University": overseasUnivInfo{"QS前200", "澳大利亚", "大洋洲"},
	"成均馆大学": overseasUnivInfo{"QS前200", "韩国", "亚洲"},
	"Sungkyunkwan University": overseasUnivInfo{"QS前200", "韩国", "亚洲"},
	"马来西亚国民大学": overseasUnivInfo{"QS前200", "马来西亚", "亚洲"},
	"Universiti Kebangsaan Malaysia (UKM)": overseasUnivInfo{"QS前200", "马来西亚", "亚洲"},
	"罗马大学": overseasUnivInfo{"QS前200", "意大利", "欧洲"},
	"Sapienza University of Rome": overseasUnivInfo{"QS前200", "意大利", "欧洲"},
	"印度理工学院孟买分校": overseasUnivInfo{"QS前200", "印度", "亚洲"},
	"Indian Institute of Technology Bombay (IITB)": overseasUnivInfo{"QS前200", "印度", "亚洲"},
	"柏林洪堡大学": overseasUnivInfo{"QS前200", "德国", "欧洲"},
	"Humboldt-Universität zu Berlin": overseasUnivInfo{"QS前200", "德国", "欧洲"},
	"奥胡斯大学": overseasUnivInfo{"QS前200", "丹麦", "欧洲"},
	"Aarhus University": overseasUnivInfo{"QS前200", "丹麦", "欧洲"},
	"巴斯大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"University of Bath": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"马来西亚博特拉大学": overseasUnivInfo{"QS前200", "马来西亚", "亚洲"},
	"Universiti Putra Malaysia (UPM)": overseasUnivInfo{"QS前200", "马来西亚", "亚洲"},
	"马来西亚理科大学": overseasUnivInfo{"QS前200", "马来西亚", "亚洲"},
	"Universiti Sains Malaysia (USM)": overseasUnivInfo{"QS前200", "马来西亚", "亚洲"},
	"墨西哥国立自治大学": overseasUnivInfo{"QS前200", "墨西哥", "北美"},
	"Universidad Nacional Autónoma de México (UNAM)": overseasUnivInfo{"QS前200", "墨西哥", "北美"},
	"纽卡斯尔大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"Newcastle University": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"博洛尼亚大学": overseasUnivInfo{"QS前200", "意大利", "欧洲"},
	"Alma Mater Studiorum - University of Bologna": overseasUnivInfo{"QS前200", "意大利", "欧洲"},
	"麦考瑞大学": overseasUnivInfo{"QS前200", "澳大利亚", "大洋洲"},
	"Macquarie University": overseasUnivInfo{"QS前200", "澳大利亚", "大洋洲"},
	"埃因霍温理工大学": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"Eindhoven University of Technology": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"鹿特丹伊拉斯谟大学": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"Erasmus University Rotterdam": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"北卡罗来纳大学教堂山分校": overseasUnivInfo{"QS前200", "美国", "北美"},
	"University of North Carolina, Chapel Hill": overseasUnivInfo{"QS前200", "美国", "北美"},
	"沙特国王大学": overseasUnivInfo{"QS前200", "沙特阿拉伯", "中东"},
	"King Saud University": overseasUnivInfo{"QS前200", "沙特阿拉伯", "中东"},
	"得克萨斯A&M大学": overseasUnivInfo{"QS前200", "美国", "北美"},
	"Texas A&M University": overseasUnivInfo{"QS前200", "美国", "北美"},
	"柏林工业大学": overseasUnivInfo{"QS前200", "德国", "欧洲"},
	"Technische Universität Berlin": overseasUnivInfo{"QS前200", "德国", "欧洲"},
	"南加州大学": overseasUnivInfo{"QS前200", "美国", "北美"},
	"University of Southern California": overseasUnivInfo{"QS前200", "美国", "北美"},
	"斯德哥尔摩大学": overseasUnivInfo{"QS前200", "瑞典", "欧洲"},
	"Stockholm University": overseasUnivInfo{"QS前200", "瑞典", "欧洲"},
	"格罗宁根大学": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"University of Groningen": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"利物浦大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"University of Liverpool": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"开普敦大学": overseasUnivInfo{"QS前200", "南非", "非洲"},
	"University of Cape Town": overseasUnivInfo{"QS前200", "南非", "非洲"},
	"西安大略大学": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"Western University": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"维也纳大学": overseasUnivInfo{"QS前200", "奥地利", "欧洲"},
	"University of Vienna": overseasUnivInfo{"QS前200", "奥地利", "欧洲"},
	"马来西亚理工大学": overseasUnivInfo{"QS前200", "马来西亚", "亚洲"},
	"Universiti Teknologi Malaysia (UTM)": overseasUnivInfo{"QS前200", "马来西亚", "亚洲"},
	"瓦赫宁根大学": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"Wageningen University & Research": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"埃克塞特大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"University of Exeter": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"日内瓦大学": overseasUnivInfo{"QS前200", "瑞士", "欧洲"},
	"University of Geneva": overseasUnivInfo{"QS前200", "瑞士", "欧洲"},
	"兰卡斯特大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"Lancaster University": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"巴塞尔大学": overseasUnivInfo{"QS前200", "瑞士", "欧洲"},
	"University of Basel": overseasUnivInfo{"QS前200", "瑞士", "欧洲"},
	"汉阳大学": overseasUnivInfo{"QS前200", "韩国", "亚洲"},
	"Hanyang University": overseasUnivInfo{"QS前200", "韩国", "亚洲"},
	"巴塞罗那大学": overseasUnivInfo{"QS前200", "西班牙", "欧洲"},
	"University of Barcelona": overseasUnivInfo{"QS前200", "西班牙", "欧洲"},
	"密歇根州立大学": overseasUnivInfo{"QS前200", "美国", "北美"},
	"Michigan State University": overseasUnivInfo{"QS前200", "美国", "北美"},
	"根特大学": overseasUnivInfo{"QS前200", "比利时", "欧洲"},
	"Ghent University": overseasUnivInfo{"QS前200", "比利时", "欧洲"},
	"阿卜杜勒阿齐兹国王大学": overseasUnivInfo{"QS前200", "沙特阿拉伯", "中东"},
	"King Abdul Aziz University (KAU)": overseasUnivInfo{"QS前200", "沙特阿拉伯", "中东"},
	"名古屋大学": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"Nagoya University": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"查尔姆斯理工大学": overseasUnivInfo{"QS前200", "瑞典", "欧洲"},
	"Chalmers University of Technology": overseasUnivInfo{"QS前200", "瑞典", "欧洲"},
	"阿里法拉比哈萨克国立大学": overseasUnivInfo{"QS前200", "哈萨克斯坦", "中亚"},
	"Al-Farabi Kazakh National University": overseasUnivInfo{"QS前200", "哈萨克斯坦", "中亚"},
	"圣路易斯华盛顿大学": overseasUnivInfo{"QS前200", "美国", "北美"},
	"Washington University in St. Louis": overseasUnivInfo{"QS前200", "美国", "北美"},
	"蒙特利尔大学": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"University of Montreal": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"约克大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"University of York": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"北海道大学": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"Hokkaido University": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"九州大学": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"Kyushu University": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"巴塞罗那自治大学": overseasUnivInfo{"QS前200", "西班牙", "欧洲"},
	"Universitat Autónoma de Barcelona": overseasUnivInfo{"QS前200", "西班牙", "欧洲"},
	"亚利桑那州立大学": overseasUnivInfo{"QS前200", "美国", "北美"},
	"Arizona State University": overseasUnivInfo{"QS前200", "美国", "北美"},
	"麦克马斯特大学": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"McMaster University": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"智利大学": overseasUnivInfo{"QS前200", "智利", "南美"},
	"Universidad de Chile": overseasUnivInfo{"QS前200", "智利", "南美"},
	"台湾清华大学": overseasUnivInfo{"QS前200", "中国台湾", "亚洲"},
	"National Tsing Hua University": overseasUnivInfo{"QS前200", "中国台湾", "亚洲"},
	"哈利法大学": overseasUnivInfo{"QS前200", "阿联酋", "中东"},
	"Khalifa University of Science and Technology": overseasUnivInfo{"QS前200", "阿联酋", "中东"},
	"加州大学圣巴巴拉分校": overseasUnivInfo{"QS前200", "美国", "北美"},
	"University of California, Santa Barbara (UCSB)": overseasUnivInfo{"QS前200", "美国", "北美"},
	"印度理工学院马德拉斯分校": overseasUnivInfo{"QS前200", "印度", "亚洲"},
	"Indian Institute of Technology Madras (IITM)": overseasUnivInfo{"QS前200", "印度", "亚洲"},
	"卡迪夫大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"Cardiff University": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"埃默里大学": overseasUnivInfo{"QS前200", "美国", "北美"},
	"Emory University": overseasUnivInfo{"QS前200", "美国", "北美"},
	"科廷大学": overseasUnivInfo{"QS前200", "澳大利亚", "大洋洲"},
	"Curtin University": overseasUnivInfo{"QS前200", "澳大利亚", "大洋洲"},
	"伯尔尼大学": overseasUnivInfo{"QS前200", "瑞士", "欧洲"},
	"University of Bern": overseasUnivInfo{"QS前200", "瑞士", "欧洲"},
	"伍伦贡大学": overseasUnivInfo{"QS前200", "澳大利亚", "大洋洲"},
	"University of Wollongong": overseasUnivInfo{"QS前200", "澳大利亚", "大洋洲"},
	"蒙特雷科技大学": overseasUnivInfo{"QS前200", "墨西哥", "北美"},
	"Tecnológico de Monterrey (ITESM)": overseasUnivInfo{"QS前200", "墨西哥", "北美"},
	"马德里康普顿斯大学": overseasUnivInfo{"QS前200", "西班牙", "欧洲"},
	"University Complutense Madrid": overseasUnivInfo{"QS前200", "西班牙", "欧洲"},
	"印度尼西亚大学": overseasUnivInfo{"QS前200", "印度尼西亚", "亚洲"},
	"UNIVERSITAS INDONESIA": overseasUnivInfo{"QS前200", "印度尼西亚", "亚洲"},
	"俄亥俄州立大学": overseasUnivInfo{"QS前200", "美国", "北美"},
	"Ohio State University": overseasUnivInfo{"QS前200", "美国", "北美"},
	"女王大学": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"Queen's University, Ontario": overseasUnivInfo{"QS前200", "加拿大", "北美"},
	"天主教鲁汶大学": overseasUnivInfo{"QS前200", "比利时", "欧洲"},
	"Université Catholique de Louvain (UCL)": overseasUnivInfo{"QS前200", "比利时", "欧洲"},
	"汉堡大学": overseasUnivInfo{"QS前200", "德国", "欧洲"},
	"Universität Hamburg": overseasUnivInfo{"QS前200", "德国", "欧洲"},
	"雷丁大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"University of Reading": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"阿姆斯特丹自由大学": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"Vrije Universiteit Amsterdam": overseasUnivInfo{"QS前200", "荷兰", "欧洲"},
	"早稻田大学": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"Waseda University": overseasUnivInfo{"QS前200", "日本", "亚洲"},
	"奥塔哥大学": overseasUnivInfo{"QS前200", "新西兰", "大洋洲"},
	"University of Otago": overseasUnivInfo{"QS前200", "新西兰", "大洋洲"},
	"维也纳工业大学": overseasUnivInfo{"QS前200", "奥地利", "欧洲"},
	"Vienna University of Technology": overseasUnivInfo{"QS前200", "奥地利", "欧洲"},
	"台湾阳明交通大学": overseasUnivInfo{"QS前200", "中国台湾", "亚洲"},
	"National Yang Ming Chiao Tung University": overseasUnivInfo{"QS前200", "中国台湾", "亚洲"},
	"贝尔法斯特女王大学": overseasUnivInfo{"QS前200", "英国", "欧洲"},
	"Queen's University Belfast": overseasUnivInfo{"QS前200", "英国", "欧洲"},
}
