package yantuseed

var sustechFeyueSCIProfiles = []Profile{
	{
		DisplayName:       "感染研究喵yy",
		OriginalAuthor: "蔡逸扬",
		School:            "南方科技大学",
		MajorLine:         "Infection Biology PhD @ MHH (德国)",
		ScoreLine:         "GPA 3.63/4 (本科), MRes Merit (IC硕士)",
		ArticleTitle:      "南科大飞跃手册 | 生物系曲折申请德国PhD的全记录",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "经历美国PhD全拒、IC硕士、多次欧洲面试后拿到德国PhD offer，分享欧洲PhD信息渠道。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对欧洲PhD申请、program面试或如何寻找PhD position感兴趣，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"欧洲PhD和美国PhD申请有什么区别？",
			"如何在欧洲找到PhD position？",
			"美国PhD全拒后怎么调整方向？",
		},
		ExpertiseTags: []string{"欧洲PhD", "德国留学", "感染生物学", "飞跃手册", "IC硕士"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级生物系，本科GPA 3.63/4，TOEFL 102，GRE 319+4。曾在校内课题组和JHU暑研。2020年美国PhD全拒后补救申请硕士，因疫情赴IC读MRes。之后陆续申请英国和欧陆PhD，经历巴塞尔Biozentrum面试、Bristol奖学金候补，最终拿到德国MHH Infection Biology PhD offer，通过DAAD奖学金资助。文章详细介绍欧洲PhD信息渠道：euraxess、nature career、findaphd、twitter等平台，以及德国MHH、瑞士Biozentrum等program的申请流程。强调生命科学方向套磁和导师推荐至关重要，建议抓住交流和暑研机会建立直接联系。`,
	},
	{
		DisplayName:       "化学反应堆y",
		OriginalAuthor: "陈颖",
		School:            "南方科技大学",
		MajorLine:         "Chemistry PhD @ Rice University",
		ScoreLine:         "GPA 3.65/4, TOEFL 95 (口语24)",
		ArticleTitle:      "南科大飞跃手册 | 化学系PhD申请与伯克利交流经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA一般无论文但凭文书和面试拿到Rice等PhD offer，分享化学PhD申请策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对化学PhD申请、学期交流科研或文书写作有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"没有论文能申到化学PhD吗？",
			"化学PhD申请文书怎么写？",
			"学期交流对申请有多大帮助？",
		},
		ExpertiseTags: []string{"化学PhD", "Rice", "文书写作", "飞跃手册", "学期交流"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级化学系，GPA 3.65/4，TOEFL 95(口语24)。大一至大三在校内有机实验室，大四上赴伯克利学期交流并加入化学生物学方向课题组。申请时无发表论文。最终录取Rice PhD(面试次日即收offer)，另获UW Seattle和Indiana offer，被UCB和UMich拒。交流期间确定了化生方向兴趣，选校以paper中感兴趣的导师为导向。文书按时间线串联科研经历，回答Why Chemistry到Why Choose Me五个核心问题。面试前准备科研PPT提前发给教授，让面试问题围绕熟悉内容展开。建议大一大二考GRE、大三考TOEFL，学期交流要充分利用地理优势拜访教授。`,
	},
	{
		DisplayName:       "化工跨界人zz",
		OriginalAuthor: "王叶晗",
		School:            "南方科技大学",
		MajorLine:         "Chemical Engineering MSc @ Imperial College",
		ScoreLine:         "GPA 3.74/4 (14/43), IELTS 7.5",
		ArticleTitle:      "南科大飞跃手册 | 化学跨大类申请帝国理工化工硕士",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "化学跨化工方向7投1中进入IC waiting list后逆袭，分享跨方向申请的心跳体验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你想跨专业申请英国硕士或对化工方向感兴趣，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"化学跨申化工方向可行吗？",
			"英国硕士申请时间线是怎样的？",
			"IC面试和ATAS审核需要注意什么？",
		},
		ExpertiseTags: []string{"英国留学", "帝国理工", "跨专业", "飞跃手册", "化工"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `17级化学系，GPA 3.74/4排名14/43，IELTS 7.0(后刷到7.5)。校内课题组科研，无论文无专利。化学跨大类申请授课型化学工程MSc，7投1中(IC)。被爱丁堡、UCL、曼大、TU Delft拒，港科大无消息。IC安排面试后拿到conditional offer，在waiting list上侥幸获选。时间线：2020年9-10月联系中介确定方向，11-12月提交申请，次年2月起陆续收到拒信和IC面试。建议选择跨方向时充分了解目标专业课程设置，尽早提交申请(英国先到先得)，ATAS申请需提前规划。`,
	},
	{
		DisplayName:       "数值计算君zy",
		OriginalAuthor: "董泽宇",
		School:            "南方科技大学",
		MajorLine:         "Applied Math PhD @ Stony Brook University",
		ScoreLine:         "GPA 3.85/4 (5/48), TOEFL 102",
		ArticleTitle:      "南科大飞跃手册 | 应用数学PhD申请与日常积累的力量",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "后知后觉型申请者，无套磁无成果但靠日常积累逃离失学，分享数学申请关键要素。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对数学系PhD申请、推荐信策略或成绩单的重要性有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"数学PhD申请中成绩单有多重要？",
			"如何通过科研经历获取推荐信？",
			"没有套磁能申到PhD吗？",
		},
		ExpertiseTags: []string{"应用数学", "PhD申请", "推荐信", "飞跃手册", "科学计算"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级数学系，GPA 3.85/4排名5/48，TOEFL 102(口语24)，GRE 149V+166Q+3.0AW。两段科研经历无发表成果无暑研无套磁。最终录取Stony Brook应用数学PhD(全奖)和FSU科学计算PhD(全奖)。Columbia降录为无奖MS，Cornell、Brown等PhD拒。申请UIUC、GaTech、Penn的MS反而全拒。数学系申请成绩单是关键因素，专业核心课和相关选修课成绩很重要。推荐信地位critical——建议借科研经历争取推荐信。科研经历如同谈恋爱，帮助确定兴趣点并获得impressive的推荐信。日常积累靠坚持而非逆袭。`,
	},
	{
		DisplayName:       "量子态观测xy",
		OriginalAuthor: "冯鑫钰",
		School:            "南方科技大学",
		MajorLine:         "Physics PhD @ UMich, Ann Arbor",
		ScoreLine:         "GPA 3.91/4 (2/63), TOEFL 101",
		ArticleTitle:      "南科大飞跃手册 | 物理系PhD申请与明确目的的重要性",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "系排名第二无论文，凭科研推荐信拿到UMich等多校PhD offer，深度分析中美读博差异。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在考虑读物理PhD、中美读博差异或推荐信策略有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"为什么要去美国读物理PhD？",
			"无论文能申到好学校物理PhD吗？",
			"推荐信对物理PhD申请有多重要？",
		},
		ExpertiseTags: []string{"物理PhD", "UMich", "推荐信", "飞跃手册", "中美对比"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `20级物理系，GPA 3.91/4排名2/63，TOEFL 101(口语19)，无GRE。在量子院课题组从大二做到毕业，无论文。推荐信两封科研推+一封课程推。最终录取UMich Physics PhD，另获Purdue、Rochester、GaTech、HKUST Physics PhD和Notre Dame ECE PhD。被Berkeley、UChicago、Duke等10所拒。文章深度分析为什么读博、为什么去美国：美国去中心化程度更高、研究自由度大、但需自律。中美对比：美国博士文章产出不如国内但培养方式不同。推荐信一定要言之有物，口语分被看重因为需要做TA。`,
	},
	{
		DisplayName:       "港中文化学dj",
		OriginalAuthor: "傅得峻",
		School:            "南方科技大学",
		MajorLine:         "Chemistry PhD @ CUHK",
		ScoreLine:         "GPA 3.59/4, TOEFL 87",
		ArticleTitle:      "南科大飞跃手册 | 化学系亚洲PhD申请与套磁攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA平平但凭科研经历和面试表现拿到港中文和港科大PhD，分享亚洲PhD申请策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对香港PhD申请、套磁信写作或面试技巧有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GPA不高能申到香港PhD吗？",
			"香港PhD申请套磁信怎么写？",
			"PhD面试需要准备什么？",
		},
		ExpertiseTags: []string{"香港PhD", "CUHK", "套磁", "飞跃手册", "面试"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `17级化学系，GPA 3.59/4，TOEFL 87。大一因迷茫GPA受损，专业GPA较高但总体平平。申请面向亚洲性价比高的PhD项目(香港、新加坡)。最终录取CUHK Chemistry PhD和HKUST Chemistry PhD。PhD申请入选门槛：科研经历>推荐信>语言成绩≈GPA。香港新加坡PhD申请中教授话语权大于委员会，必须提前套磁。套磁信要针对目标教授的最新研究方向提出成熟见解。面试是最重要环节，需对课题所有细节了如指掌。建议使用Gmail而非学校企业邮箱(可能被对方黑名单)。收到多个offer后尽快通知其他教授。`,
	},
	{
		DisplayName:       "光华套利手yy",
		OriginalAuthor: "高奕扬",
		School:            "南方科技大学",
		MajorLine:         "金融硕士 保研 @ 北大光华管理学院",
		ScoreLine:         "GPA 3.79/4 (1/20), CET-6 550, TOEFL 100",
		ArticleTitle:      "南科大飞跃手册 | 金融数学保研北大光华的逆袭经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "金融数学专业排名第一，一路入营被拒后逆袭北大光华第三批offer。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对商科保研、北大光华申请或金融行业选择有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"南科大保研商科难度有多大？",
			"金融硕士项目怎么选择？",
			"保研中信息差如何弥补？",
		},
		ExpertiseTags: []string{"保研", "北大光华", "金融", "飞跃手册", "商科"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `21级金融数学，GPA 3.79/4排名1/20，CET-6 550，TOEFL 100。最终保研北大光华管理学院MFin第三批。清华经管BA夏令营入营后waiting，北大汇丰、清华五道口、复旦泛海、人大财金均未入营。南科大保研特色：试错成本高、信息差大、保研氛围缺乏。商科保研是卷中卷，往年经验第二年可能失效。文章详细介绍金融行业岗位(VC/PE/IB/量化/行研/咨询)和国内热门经管硕博项目。南科大学生硬实力不差但背景看起来有差距。建议：垂直积累背景、关注实习经历、早做规划。`,
	},
	{
		DisplayName:       "公共政策人lw",
		OriginalAuthor: "姜力维",
		School:            "南方科技大学",
		MajorLine:         "Public Policy MS @ Duke University",
		ScoreLine:         "GPA 3.52/4, TOEFL 101, GRE 326",
		ArticleTitle:      "南科大飞跃手册 | 化学系工作两年后跨专业申请公共政策",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "化学系毕业工作两年后跨专业申请公共政策硕士，拿到Duke 5万刀奖学金。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在犹豫读研方向、考虑跨专业或工作后申请，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"工作后再申请研究生可行吗？",
			"理科跨申公共政策需要什么条件？",
			"Duke MPP项目怎么样？",
		},
		ExpertiseTags: []string{"跨专业", "公共政策", "Duke", "飞跃手册", "工作后申请"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `15级化学系，GPA 3.52/4，TOEFL 101(工作期间重考)，GRE 326(大三暑假突击一月)。本科计划申化学PhD但发现不适合科研，毕业后先做电商再做外贸。工作一年后决定出国读公共政策/管理硕士(MPA/MPP)。最终获Duke MPP(5万刀奖学金)、USC MPA、UPitt MPA、UW MPA、AU MPA(4.2万刀奖学金)、NEU MPA录取。被Columbia、NYU、Cornell、UNC拒。选校考虑地理位置和未来NGO就业机会。文书要讲清楚与申请项目的契合点，建议找专业人多次修改。`,
	},
	{
		DisplayName:       "控制论信徒nf",
		OriginalAuthor: "江南飞",
		School:            "南方科技大学",
		MajorLine:         "ECE PhD @ UC Santa Barbara (Control)",
		ScoreLine:         "GPA 3.87/4 (4/41), TOEFL 105",
		ArticleTitle:      "南科大飞跃手册 | 数学系DIY申请UCSB控制方向PhD",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "有保底心态从容申请，意外拿到UCSB ECE PhD offer，分享DIY申请和选校策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对数学转ECE/控制方向申请、DIY策略或暑研经历有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"数学系能申ECE方向PhD吗？",
			"为什么不建议找中介申请？",
			"有保底offer心态怎么调整？",
		},
		ExpertiseTags: []string{"控制方向", "UCSB", "DIY申请", "飞跃手册", "跨方向"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `19级数学系，GPA 3.87/4排名4/41，TOEFL 105，GRE 158V+167Q+3.0AW。伯克利两学期交流GPA 4.0，暑研经历有推荐信。申请时无论文。最终录取UCSB ECE PhD(Control方向，全美Top3)，另获UCSC Applied Math PhD、GaTech CSE PhD口头offer、UW Seattle Applied Math博退硕。MIT、Berkeley、Caltech、Brown、Cornell等10所拒。因有UCSC保底心态从容，大量申彩票校。不找中介原因：中介不了解专业，ChatGPT时代文书能力已被AI超越。UCSB控制方向实力强劲，选校时发现ECE意外匹配。`,
	},
	{
		DisplayName:       "名古屋环境cl",
		OriginalAuthor: "廖崇霖",
		School:            "南方科技大学",
		MajorLine:         "G30/SGU 修士 @ 名古屋大学 (环境土木)",
		ScoreLine:         "GPA 3.74/4, TOEFL 91, GRE 324",
		ArticleTitle:      "南科大飞跃手册 | 日本SGU英语项目申请与套磁经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "跨专业拿到东大内诺后被鸽，转战名古屋和欧陆，分享日本英语项目申请攻略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对日本SGU英语项目、教授内诺制度或欧陆申请有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"日本SGU英语项目是什么？",
			"如何拿到日本教授的内诺？",
			"东京大学GPES项目怎么申？",
		},
		ExpertiseTags: []string{"日本留学", "名古屋", "SGU", "飞跃手册", "跨专业"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `17级海洋系，GPA 3.74/4，TOEFL 91，GRE 324。三段校内科研无论文无交换。跨专业申请环境方向。2020年7月拿到东大GPES教授内诺，8月拿到名古屋G30教授内诺。东大教授因个人原因面试前取消招生。转而准备欧陆申请，最终拿到名古屋G30/SGU offer、哥本哈根和DTU offer。日本英语项目不要求日语，需提前套磁获教授内诺。GPES需提交GRE和研究计划书。名古屋G30全球招5人左右，推荐信需教授自行邮寄。申请季持续9个月，跨专业和教授变卦导致格外煎熬。`,
	},
	{
		DisplayName:       "延毕数学人rj",
		OriginalAuthor: "林睿军",
		School:            "南方科技大学",
		MajorLine:         "Mathematics MSc @ University of Copenhagen",
		ScoreLine:         "GPA 3.43/4, IELTS 6.5",
		ArticleTitle:      "南科大飞跃手册 | 延期毕业到欧洲数学硕士的逆袭之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "延期毕业、成绩普通的数学系学生，三考雅思后拿到7个欧洲数学硕士offer。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你成绩不突出但想申请欧洲硕士，或者对延毕有顾虑，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GPA不高能申到欧洲数学硕士吗？",
			"欧洲数学硕士项目怎么选校？",
			"延期毕业对申请有影响吗？",
		},
		ExpertiseTags: []string{"欧洲留学", "哥本哈根", "数学硕士", "飞跃手册", "延毕"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级数学系，GPA 3.43/4(普通)，IELTS 6.5(三考才达线)，无GRE。延期毕业一年。最终录取哥本哈根大学数学硕士(综合地理位置和学术水平选择)，另获阿姆斯特丹、乌特勒支、奥尔胡斯、乌普萨拉等7所欧洲大学offer。被帝国理工和曼大拒。欧洲数学硕士项目特点：北欧多所学校不需要推荐信和PS，申请门槛相对灵活。建议GPA不突出的同学考虑欧洲——学费低廉甚至免费，学术水平高。哥本哈根和奥尔胡斯只需成绩单即可申请。IC和曼大拒了说明要量力而行。`,
	},
	{
		DisplayName:       "深蓝潜水员ww",
		OriginalAuthor: "刘雯文",
		School:            "南方科技大学",
		MajorLine:         "海洋科学 直博 @ 同济大学",
		ScoreLine:         "GPA 3.74/4, 海洋系",
		ArticleTitle:      "南科大飞跃手册 | 海洋系同学的「玩」中成长记",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "持证潜水员、义工旅行者，用丰富体验诠释大学可能性，最终直博同济海洋科学。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对海洋科学方向、大学课外探索或义工旅行有兴趣，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"海洋系有哪些有趣的课外体验？",
			"如何找到免费科研实习机会？",
			"大学期间怎么平衡学业和探索？",
		},
		ExpertiseTags: []string{"海洋科学", "同济大学", "潜水", "飞跃手册", "探索"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `17级海洋系，GPA 3.74/4，直博同济大学海洋科学。因疫情学期交流取消，用半年自由时间做了大量探索：参加KAUST海报比赛(中东一周费用全免)、考取潜水证、参与海洋公益、寺庙修禅体验、海南义工旅行、三亚海洋所实习喂小丑鱼和给海龟洗澡。文章以「玩」为主题分享大学可能性：关注公众号找活动、培养爱好加入社团、旁听感兴趣的课、豆瓣搜义工旅行。经费来源：基本生活费+奖学金+兼职+比赛奖金。敢想敢做是最重要的品质。`,
	},
	{
		DisplayName:       "布朗数学人yh",
		OriginalAuthor: "陈勇",
		School:            "南方科技大学",
		MajorLine:         "Mathematics PhD @ Brown University",
		ScoreLine:         "GPA 3.88/4 (2/50), TOEFL 106, GRE Sub 92%",
		ArticleTitle:      "南科大飞跃手册 | 数学系英语备考、交流与方向选择经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "伯克利交流一年后确定基础数学方向，分享英语备考、暑研收获与导师选择建议。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对数学PhD申请、伯克利交流体验或方向选择有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"数学系怎么选择研究方向和导师？",
			"GRE Subject数学怎么准备？",
			"交流经历对数学PhD申请有多大帮助？",
		},
		ExpertiseTags: []string{"基础数学", "Brown", "GRE Sub", "飞跃手册", "交流"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `19级数学系基础数学方向，GPA 3.88/4排名2/50，伯克利交流GPA 4.0/4.0。TOEFL 106，GRE 147V+170Q+3.0AW，GRE Subject Math 92%。最终录取布朗大学数学系全奖博士。文章分享三点经验：一、英语备考——托福口语最被看重(需做TA)，GRE verbal难但可选择optional不交，GRE Sub一年一次需大三就考。二、交流收获——在伯克利首次接触科研、跟教授暑研聊天爬山，加入武术社团学做饭，是综合能力提升。三、方向和导师选择——不要仅凭基础课判断方向，旁听研究生课感受真实面貌，选导师看其带出学生的平均水平。`,
	},
	{
		DisplayName:       "华威神经元ym",
		OriginalAuthor: "马一铭",
		School:            "南方科技大学",
		MajorLine:         "MSc leading to PhD @ Warwick (Mathematics of Systems)",
		ScoreLine:         "GPA 3.84/4 (5/48), IELTS 8.0, GRE 323",
		ArticleTitle:      "南科大飞跃手册 | 数学系申请英国硕博连读与选校经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "爱丁堡交流后申请英国硕博项目，分享英国申请琐碎经验和跨方向规划。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对英国数学硕博项目、爱丁堡交流或先到先得策略有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"英国硕博连读项目怎么选？",
			"申请英国大学有哪些注意事项？",
			"数学转神经科学方向可行吗？",
		},
		ExpertiseTags: []string{"英国留学", "Warwick", "数学", "飞跃手册", "硕博连读"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级数学系，GPA 3.84/4排名5/48，IELTS 8.0(R9.0)，GRE 153V+170Q+3.5AW。爱丁堡学期交流(First-Class Honours)和北卡州立GEARS项目。最终录取华威大学系统数学硕博连读(MSc leading to PhD)，计划研究复杂神经元和神经网络模拟。另获LSE运筹学、UCL数学建模、爱丁堡、华威CS MSc等录取。被IC两个项目和UCL机器学习拒。英国申请关键经验：先到先得一定要系统开通就提交；授课型硕士1年学制；硕士阶段中国学生基本无奖学金。申请材料需成绩单、语言成绩、推荐信和PS。`,
	},
	{
		DisplayName:       "踩坑幸存者bz",
		OriginalAuthor: "南博钊",
		School:            "南方科技大学",
		MajorLine:         "Chemistry PhD @ Notre Dame University",
		ScoreLine:         "GPA 3.66/4, TOEFL 92 (口语18)",
		ArticleTitle:      "南科大飞跃手册 | 化学系非典型申请人的逆境求生",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA低、英语翻车、暑研被鸽的非典型申请人，分享如何在困境中拿到PhD offer。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你的申请条件不理想但仍想冲PhD，或者遇到了暑研被鸽等困境，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"条件很差还能申化学PhD吗？",
			"暑研被导师鸽了怎么办？",
			"英语口语不达标怎么选校？",
		},
		ExpertiseTags: []string{"化学PhD", "Notre Dame", "逆境申请", "飞跃手册", "套磁"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `15级化学系，GPA 3.66/4，TOEFL 92(口语18)，GRE 146V+166Q+3.0AW。大一选课爆炸导致GPA再没上过3.7，暑研被UCI导师鸽掉，申请截止前无论文。最终拿到Notre Dame、Rutgers、Stony Brook三个Chemistry PhD offer，另有NUS和东京大学申请后因转方向withdraw。虽然英语低于大部分学校标准，但还是拿到offer说明官网要求仅供参考。建议把课题成果做成展会海报式Summary附到PS附录中，面试大概率围绕这些内容问。合理安排TOEFL和GRE考试时间避免车轮战。`,
	},
	{
		DisplayName:       "怒考化学生k",
		OriginalAuthor: "化学",
		School:            "南方科技大学",
		MajorLine:         "化学学硕 考研 @ 南方科技大学",
		ScoreLine:         "化学系倒数GPA, 初试总分351擦线上岸",
		ArticleTitle:      "南科大飞跃手册 | 考研前1个月报名的极限上岸攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "考了五六次托福未过线，怒而考研前一个月报名并擦线上岸，分享极限备考策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在考虑考研本校化学、出国受阻想考研、或想了解极限备考经验，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"南科大化学考研难度大吗？",
			"考研只有一个月怎么准备？",
			"出国还是考研怎么选？",
		},
		ExpertiseTags: []string{"考研", "化学", "南科大", "飞跃手册", "极限备考"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级化学系，GPA倒数(过3)，考了五六次TOEFL仍不满足境外高校要求，考研前1个多月怒而报名并擦线上岸。初试351分：政治70多(肖四肖八必刷)、英语50多(裸考)、物化90多、有机130多。南科大化学系考研对本校学生相对简单，建议准备3个月。有机化学试题风格中规中矩，有机和高等有机90+可尝试裸考。物理化学出题风格较奇特，结构部分课本原题，热力学部分课堂原题。复试准备英文自我介绍和PPT即可。建议：想出国就早考英语，想转行直接转别犹豫，考研不应是走投无路时的救命稻草。`,
	},
	{
		DisplayName:       "北大物理一jj",
		OriginalAuthor: "石晶晶",
		School:            "南方科技大学",
		MajorLine:         "物理凝聚态 直博 @ 北京大学",
		ScoreLine:         "GPA 3.93/4 (1/55), CET-4 567",
		ArticleTitle:      "南科大飞跃手册 | 物理系排名第一保研北大直博的全攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "物理系排名第一，清北双offer后选择北大凝聚态直博，分享夏令营面试全流程。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对物理系保研清北、夏令营面试或直博选择有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"物理系保研清北需要什么条件？",
			"清北物理夏令营怎么准备？",
			"保研还是出国怎么选？",
		},
		ExpertiseTags: []string{"保研", "北大", "物理直博", "飞跃手册", "夏令营"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `19级物理系，GPA 3.93/4排名1/55，CET-4 567，IELTS 6.0。参加过牛津寒假项目和以色列研究所寒校，物理竞赛三等奖、实验竞赛三等奖，主导量子院攀登计划项目。最终保研北大物理学院凝聚态直博，同时获清华物理直博offer。选择保研原因：英语不好、凝聚态方向国内领先。夏令营准备重点：把本科9门专业核心课全部复习一遍并总结可能考点。清华夏令营3天(前两天聊导师+参观，第三天5位老师面试问到不会为止)，北大6天(学术报告+自我展示+面试+联系导师)。提交材料前一定反复检查。`,
	},
	{
		DisplayName:       "生物交叉侠l",
		OriginalAuthor: "孙力",
		School:            "南方科技大学",
		MajorLine:         "Intelligent Systems PhD @ U of Pittsburgh",
		ScoreLine:         "GPA 3.86/4 (2/22), TOEFL 104",
		ArticleTitle:      "南科大飞跃手册 | 生物信息转CV方向PhD申请实录",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "生物信息转计算机视觉方向，MICCAI竞赛获奖后套磁拿到多个PhD offer。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对交叉方向PhD申请、MICCAI竞赛或套磁策略有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"生物信息转CV方向PhD可行吗？",
			"MICCAI竞赛对申请有帮助吗？",
			"PhD申请中套磁有什么技巧？",
		},
		ExpertiseTags: []string{"生物信息", "医学影像", "PhD申请", "飞跃手册", "套磁"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `15级生物系生物信息专业，GPA 3.86/4排名2/22，TOEFL 104，GRE 156V+170Q+3.5AW。国家奖学金，两篇MICCAI Workshop一作，BraTS Challenge获Survival Prediction第二名和Intel AI Award。最终录取UPitt Intelligent Systems PhD，另获Stony Brook和ASU Biomedical Informatics PhD、KAUST CS PhD等offer。被UVa、CUHK等拒。套磁策略：查遍MICCAI 2018所有发文教授，筛选发过CVPR顶会的，确定hunting list后一一发邮件。建议找方向match的导师，早考TOEFL/GRE，暑研选与方向匹配的实验室。`,
	},
	{
		DisplayName:       "ETH地球人lu",
		OriginalAuthor: "田璐",
		School:            "南方科技大学",
		MajorLine:         "Earth Science MS @ ETH Zurich",
		ScoreLine:         "GPA 3.73 (2/8), 专业GPA 3.86, TOEFL 100",
		ArticleTitle:      "南科大飞跃手册 | 地空系首届毕业生申请ETH和美国PhD",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "地空系首届毕业生，选择情怀ETH放弃美国PhD全奖offer，分享取向狙击申请法。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对地球科学方向申请、ETH硕士或PhD套磁策略有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"ETH Earth Science硕士怎么样？",
			"PhD申请如何做到取向狙击？",
			"美国PhD和ETH硕士怎么选？",
		},
		ExpertiseTags: []string{"ETH", "地球科学", "PhD申请", "飞跃手册", "套磁"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级地空系(ESS)，总GPA 3.73排名2/8，专业GPA 3.86，GRE 321+3.5，TOEFL 100。大三加入院士课题组做国创项目，大四赴伯克利交流并参加AGU年会。最终选择ETH Zurich Earth Science硕士(Assistantship)，放弃UMich PhD(Fellowship)、Penn State PhD、Rice PhD等美国offer。ETH连续六年QS Earth Science排名第一，本校申PhD基本只需导师同意。PhD申请要义：教授寻找最match而非最优秀的人。套磁时利用AGU等学术会议当面交流，通过教授态度判断定位。文书要精炼高效，保底校也要选真正想去的。`,
	},
	{
		DisplayName:       "伯克利神经c",
		OriginalAuthor: "王超",
		School:            "南方科技大学",
		MajorLine:         "Neuroscience PhD @ USC",
		ScoreLine:         "GPA 3.61/4 (南科大), 3.95/4 (UCB), TOEFL 109",
		ArticleTitle:      "南科大飞跃手册 | 生物系伯克利交流三学期后申请神经科学PhD",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "伯克利交流三学期扭转大学轨迹，14拒后凭邮件主动联系拿到USC Neuroscience PhD。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对神经科学PhD申请、伯克利长期交流或主动争取面试有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"伯克利交流三学期是什么体验？",
			"被14所学校拒了怎么办？",
			"神经科学PhD怎么申请？",
		},
		ExpertiseTags: []string{"神经科学", "USC", "伯克利交流", "飞跃手册", "PhD申请"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `17级生物系，南科大GPA 3.61/4，伯克利交流三学期GPA 3.95/4，TOEFL 109(口语23)。大二进实验室做神经科学基础实验，之后赴UCI三周和伯克利三学期交流。申请14所Neuroscience PhD被拒(Harvard、Berkeley、JHU、Columbia等)，最终通过主动邮件联系教授获得USC Neuroscience PhD面试和offer。另获伯克利教授直接录取(因方向不匹配放弃)和中科院脑科学中心硕博连读。大一GPA 3.14后努力拉到3.61，强调大一第一学期GPA极其重要。建议不急于进实验室，先探索不同职业方向再决定科研。`,
	},
	{
		DisplayName:       "跨考逆袭王h",
		OriginalAuthor: "王晗",
		School:            "南方科技大学",
		MajorLine:         "电子系 考研 @ 南方科技大学",
		ScoreLine:         "初试373分 (电子系第2), GPA 3.12/4",
		ArticleTitle:      "南科大飞跃手册 | 物理系跨考电子系四个月逆袭上岸",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "物理系GPA 3.12、大四还剩8门课，跨专业四个月备考电子系并成功上岸。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在短时间备考、跨专业考研或数学复习策略方面有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"四个月能考上研究生吗？",
			"跨专业考研需要注意什么？",
			"数学一怎么高效复习？",
		},
		ExpertiseTags: []string{"考研", "跨专业", "短期备考", "飞跃手册", "电子系"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级物理系应用物理，GPA 3.12/4排名5/5。大四开学仍剩8门专业课，四个月跨考电子系。初试373分(电子系第2)：政治61、英语75、数学一102、专业课135。数学复习策略：只买真题(2010-2019)，发现线代薄弱后看《简明线性代数》三周补基础，高数教材3天17小时看完一本——专注时效率惊人但制订计划不可以此为预期。不建议南科大学生花太多时间看网课(节奏太慢)。英语关键在背单词，女朋友一眼看出问题建议每天两小时背单词，一个月后模考排名第一。不用整理错题本。`,
	},
	{
		DisplayName:       "中科大微尺度jh",
		OriginalAuthor: "汪静涵",
		School:            "南方科技大学",
		MajorLine:         "物理 直博 @ 中国科学技术大学",
		ScoreLine:         "GPA 3.88/4 (2/55), CET-4 527",
		ArticleTitle:      "南科大飞跃手册 | 物理系保研中科大直博经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "物理系排名第二但英语差选择保研，分享清华面试失利和中科大上岸经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对物理系保研、中科大微尺度中心或夏令营面试有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"物理系保研怎么选学校？",
			"中科大夏令营面试考什么？",
			"英语差选择保研还是出国？",
		},
		ExpertiseTags: []string{"保研", "中科大", "物理直博", "飞跃手册", "夏令营"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `19级物理系，GPA 3.88/4排名2/55，CET-4 527。大二上进实验室参与攀登计划项目。因英语太差选择保研而非出国。最终保研中科大合肥微尺度物质科学国家研究中心。清华物理夏令营面试不通过，复旦和南大夏令营未入营，北大因时间冲突放弃。中科大5月底有预面试可作为正式面试演练。面试内容：自我介绍(突出优势)、英文文献翻译(南科大英文教育足够应对)、专业问题(一直问到不会为止)、科研经历。保研要重视四六级成绩，很多夏令营需要六级。与导师提前沟通硕士vs直博意向。`,
	},
	{
		DisplayName:       "材料踩坑侠yf",
		OriginalAuthor: "汪轶凡",
		School:            "南方科技大学",
		MajorLine:         "MSE PhD @ Arizona State University",
		ScoreLine:         "GPA 3.73/4 (22/55), TOEFL 110",
		ArticleTitle:      "南科大飞跃手册 | 物理系波折申请材料科学PhD的搞笑实录",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "自嘲来搞笑的申请者，经历疫情困家、板上钉钉被拒后AD转offer逆袭ASU。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你的申请季充满波折、或者想了解保底校策略和套磁转offer经验，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"申请遇到大量拒信怎么办？",
			"如何把AD转为PhD offer？",
			"保底校应该怎么选？",
		},
		ExpertiseTags: []string{"材料科学", "ASU", "保底校", "飞跃手册", "套磁"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级物理系，GPA 3.73/4排名22/55，TOEFL 110(S23 W27)，GRE 155V+170Q+3.5AW。有暑研经历。推荐信迟交一个月导致焦虑。板上钉钉的学校3月初发来拒信后开始紧急套磁。ASU先给了AD(著名AD狂魔)，之后发邮件套教授等了一周得到积极回复，又等了一个月终于约到面试并拿到offer。面试时应主动问研究方向、工作时长、工资等问题，表现认真考虑的态度。保底校选择关键：以学术产出为导向选课题组而非学校，问自己待四五年会不会很憋屈。rej是玄学，有些排名低的学校很早拒，排名高的5月才拒。`,
	},
	{
		DisplayName:       "凝聚态老王yh",
		OriginalAuthor: "王煜寰",
		School:            "南方科技大学",
		MajorLine:         "Physics PhD @ UIUC",
		ScoreLine:         "GPA 3.88/4 (4/55), TOEFL 106, GRE Physics 990(95%)",
		ArticleTitle:      "南科大飞跃手册 | 物理系PhD申请踩坑实录与伯克利暑研",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "一直在踩坑的物理PhD申请者，分享GRE Sub、伯克利暑研和DIY全攻略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对物理PhD申请、GRE Subject备考或伯克利暑研有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GRE Physics Sub怎么准备？",
			"物理PhD申请三维门槛是多少？",
			"凝聚态和生物物理方向怎么选？",
		},
		ExpertiseTags: []string{"物理PhD", "UIUC", "GRE Sub", "飞跃手册", "暑研"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级物理系，GPA 3.88排名4/55，TOEFL 106(听力放完一组就去洗手间回来发现放完了)，GRE 153V+169Q+3.5，GRE Physics 990(95%)。三段科研(二维材料、光学、生物物理)，伯克利学期交流+暑研。最终录取UIUC Physics PhD，另获Penn State、U Florida、UT-Austin Physics PhD和NUS PhD(President Fellowship)等5个offer。被Berkeley、Cornell、Columbia等7所拒。GRE Physics对申请物理PhD很重要——伯克利招生秘书说基本不看General但看Sub。中国学生没990基本没戏(虽然美国学生800就够)。Sub中国一年只考一次(10月底)，强烈建议大三就考。全DIY申请，不找中介。`,
	},
	{
		DisplayName:       "数分不放弃yf",
		OriginalAuthor: "吴一凡",
		School:            "南方科技大学",
		MajorLine:         "数学 考研 @ 南方科技大学",
		ScoreLine:         "初试378分, 数学与应用数学",
		ArticleTitle:      "南科大飞跃手册 | 数学系考研上岸与毅力的重要性",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "贪图玩乐失去出国机会后走投无路选择考研，分享制定计划和严格执行的经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对数学考研备考策略、复习计划制定或心态调整有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"数学考研怎么复习效率最高？",
			"考研计划执行不下去怎么办？",
			"数学分析用什么教材复习？",
		},
		ExpertiseTags: []string{"考研", "数学", "南科大", "飞跃手册", "备考策略"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `15级数学系，初试378分拟录取数学与应用数学专业。因大学期间成绩不好失去出国机会，大三学期结束(6月底)当机立断决定考研。考研备考最重要的是制定计划并严格执行——常出现"今天放松明天补"的念头导致计划报废。专业课是大头，不要妄图用政治英语甩开别人。政治用肖秀荣系列。线性代数推荐北大高等代数和丘维声教材。数学分析推荐常庚哲、史济怀《数学分析》一本就够。眼高手低是考研大忌，看书觉得会了碰到题目却不会做。找同路人一起复习相互提问非常重要。`,
	},
	{
		DisplayName:       "游戏规则解读yc",
		OriginalAuthor: "钟志源",
		School:            "南方科技大学",
		MajorLine:         "Applied Math PhD @ U of Maryland",
		ScoreLine:         "GPA 3.94/4 (1/N), TOEFL 108, GRE 166V+170Q+4.0AW",
		ArticleTitle:      "南科大飞跃手册 | PhD申请游戏规则、推荐信与Connection",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "系排名第一的方法论型申请者，深度解析PhD申请的真实规则和推荐信策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你想深入理解PhD申请的底层逻辑、推荐信策略或科研规划，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"PhD申请中推荐信到底有多重要？",
			"什么叫一封好的推荐信？",
			"如何提高GPA和英语成绩？",
		},
		ExpertiseTags: []string{"PhD方法论", "推荐信", "应用数学", "飞跃手册", "CSST"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级数学系，GPA 3.94排名第一，NYU Courant交流全A(含两门PhD课程)，TOEFL 108(口语24)，GRE 166V+170Q+4.0AW。UCLA-CSST暑研+NYU交流+NYU Shanghai暑研。最终录取UW Applied Math PhD和Maryland AMSC PhD等5个全奖PhD，被Berkeley IEOR、Cornell ORIE等11所拒。文章深度分析PhD申请因素排序：推荐信(research-based)>高质量研究经历>本科学校>GPA>SOP>TOEFL>GRE。推荐信甚至可以逆天改命——被顶尖项目录取不需要是天才但需要贵人相助。好的推荐信来自执导过research的业内大牛。建议丢掉学生思维，理解PhD申请掺杂大量软性人际因素。`,
	},
	{
		DisplayName:       "BA转型选手zy",
		OriginalAuthor: "杨志遥",
		School:            "南方科技大学",
		MajorLine:         "Business Analytics MS @ U of Maryland",
		ScoreLine:         "GPA 3.53/4, TOEFL 100, GRE 319",
		ArticleTitle:      "南科大飞跃手册 | 金融数学申请商业分析硕士的踩坑心得",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "并不拔尖的普通学生，分享商科申请选校选项目和中介避坑经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对商业分析硕士申请、金融数学方向或中介选择有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"商业分析硕士项目怎么选？",
			"该不该找中介申请？",
			"金融数学能转什么方向？",
		},
		ExpertiseTags: []string{"商业分析", "UMD", "金融数学", "飞跃手册", "选校"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级金融数学，GPA 3.53，TOEFL 100(L30)，GRE 319+3.5(V151+Q168)。广发银行和联储证券实习，UBC交流，前书院学生会主席。主申Business Analytics混申Finance。获UMD BA、GWU BA(6k奖)、NEU BA、JHU Finance等AD。被UIUC Finance和RPI BA拒。花了大钱找中介但非常后悔——选校选项目需自己研究、文书可找专人修改、网申中介可能帮倒忙。申请所需信息在学校网站和论坛都能找到(商科推荐chasedream)。建议不要只看学校综排，关注项目本身质量和就业方向。选项目前想清楚自己想要什么。`,
	},
	{
		DisplayName:       "PPT达人xy2",
		School:            "南方科技大学",
		MajorLine:         "数学系 美国方向 MS/PhD 申请",
		ScoreLine:         "16级数学系",
		ArticleTitle:      "南科大飞跃手册 | 数学系申请美国硕博PPT总结",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "以PPT图文形式分享数学系美国硕博申请经验，直观展示完整申请流程。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对数学系美国申请的完整流程有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"数学系美国申请的基本流程？",
			"选校需要考虑哪些因素？",
			"申请材料怎么准备？",
		},
		ExpertiseTags: []string{"美国留学", "数学", "申请流程", "飞跃手册", "选校"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级数学系同学以PPT/图片形式分享了美国方向硕博申请的完整流程和经验总结。内容以可视化方式呈现，涵盖选校策略、标化考试准备、科研经历积累、文书写作、推荐信安排、申请时间线等核心环节。图文并茂的形式便于快速了解申请全貌，尤其适合数学系学弟学妹参考。建议结合其他同届同学的详细文字版经验一起阅读，从不同角度了解申请过程。`,
	},
	{
		DisplayName:       "东大修士sh",
		OriginalAuthor: "郑书晗",
		School:            "南方科技大学",
		MajorLine:         "EEIS 修士 @ 东京大学 (IME项目)",
		ScoreLine:         "GPA 3.84/4, TOEFL 107, SCI一作一篇",
		ArticleTitle:      "南科大飞跃手册 | 物理系申请东京大学IME英文项目实录",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "通过IME英文项目拿到东大EEIS修士offer，详解套磁、研究计划书和面试流程。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对东京大学IME项目、日本留学或研究计划书写作有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"东京大学IME项目怎么申请？",
			"日本修士和欧美PhD有什么区别？",
			"研究计划书怎么写？",
		},
		ExpertiseTags: []string{"日本留学", "东京大学", "IME", "飞跃手册", "修士"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `17级物理系，GPA 3.84/4，TOEFL 107(口语23)，GRE 155V+167Q+4AW，SCI一作论文一篇，UCSD交换满绩。最终录取东京大学IME-EEIS修士。被UCSD Cognitive Science PhD和EPFL Life Sciences Master拒。日本大学院不能直博，本科后只能读两年修士。IME(International Multidisciplinary Engineering)覆盖工学院7个系，无录取名额限制达到标准即录取。申请前需套磁教授获内诺，研究计划书(Research Proposal)相当重要需体现对前沿理解。面试时回答要言之有据，导师会深入追问。不要求日语，全英语交流。`,
	},
	{
		DisplayName:       "脑科学探路yj",
		OriginalAuthor: "张亚杰",
		School:            "南方科技大学",
		MajorLine:         "研究助理 @ 北京脑科学与类脑研究中心",
		ScoreLine:         "GPA 3.0+, 16级生物系",
		ArticleTitle:      "南科大飞跃手册 | 生物系毕业选择研究助理的心路历程",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "PhD申请不到、考研失败后选择做RA，分享如何疯狂投简历找到满意的研究岗位。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在考虑做研究助理、毕业方向迷茫或想了解RA申请策略，欢迎交流。",
		Education:         "本科（研究助理）",
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"做研究助理对申PhD有帮助吗？",
			"怎么找到好的RA岗位？",
			"选年轻PI还是大牛导师？",
		},
		ExpertiseTags: []string{"研究助理", "脑科学", "求职", "飞跃手册", "RA"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级生物系，GPA比3.0高，生物系优秀毕业生。PhD申请不到好学校、考研失败后选择就业。投简历策略：不在就业网站找，主动出击——把北师大脑院、北大心理学院、清华生科院等所有PI研究兴趣看一遍，挑最感兴趣的逐一发自荐邮件。大部分石沉大海但有惊喜。最终选择年轻新建实验室的PI：论文虽少但每篇质量高，博士和博后来自美国知名实验室。RA工作2-3年是合理期限，有好成果对申博帮助比读硕士更大。选导师建议：自制力强选大牛(博后厉害能学到)，自制力弱选愿意手把手教的年轻PI。`,
	},
	{
		DisplayName:       "宾大生工人z",
		OriginalAuthor: "张展",
		School:            "南方科技大学",
		MajorLine:         "Bioengineering PhD @ UPenn",
		ScoreLine:         "GPA 3.77/4, TOEFL 104",
		ArticleTitle:      "南科大飞跃手册 | 生物系跨申生物工程PhD的申请策略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "缺乏工科背景但凭科研贡献和主动邮件联系教授拿到UPenn生物工程PhD。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对生物转工程方向PhD、主动争取面试或UCLA CSST暑研有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"生物系能申生物工程PhD吗？",
			"没收到面试邀请怎么主动争取？",
			"CSST暑研是什么体验？",
		},
		ExpertiseTags: []string{"生物工程", "UPenn", "CSST", "飞跃手册", "PhD申请"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `17级生物系，GPA 3.77/4，TOEFL 104(口语23)，GRE optional。参加UCLA-CSST暑研(因疫情改线上，首次尝试计算模型研究)。明显缺乏工科背景却主申生物工程PhD，选校未拉开梯度导致很长时间无面试。最终通过主动邮件联系教授获得一对一面试机会，拿到UPenn Bioengineering PhD和UIUC PhD、NUS PhD、哥本哈根MS等。邮件要简洁，重点讲为什么对教授项目感兴趣并联系自身经历。申请最重要三因素：对科研项目的理解和贡献、专业核心课GPA、推荐信。GPA不是最关键但老师会关心相关核心课成绩。`,
	},
	{
		DisplayName:       "KAUST脑科学j",
		OriginalAuthor: "周觉晓",
		School:            "南方科技大学",
		MajorLine:         "Computer Science PhD @ KAUST",
		ScoreLine:         "GPA 3.92/4 (专1系1), 4篇SCI+2篇顶会",
		ArticleTitle:      "南科大飞跃手册 | 生物信息到KAUST CS PhD的规划之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "大一规划好四年课表，生物信息转CS方向，以丰硕成果拿到KAUST PhD offer。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对学术规划、生物信息转CS或KAUST PhD有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"如何从大一开始规划四年？",
			"生物信息能转CS PhD吗？",
			"KAUST的PhD项目怎么样？",
		},
		ExpertiseTags: []string{"KAUST", "生物信息", "CS PhD", "飞跃手册", "规划"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `16级生物信息学，GPA 3.92/4专业和系双第一。4篇SCI、2篇顶会、多个会议oral和poster。入学第一个月就排好四年每学期课表和小目标。大一积极进组试错：先在湿实验课题组学习，后转入生信课题组。大二吃苦霸蛮——有时间就往实验室跑，以课题为导向学习高阶知识最高效。申请KAUST CS PhD(脑科学方向)，从生物信息转向CS是为了从计算角度解码大脑。入学规划建议：对照培养方案排课避雷，定期小目标并在试错中修正计划。科研中失败是家常便饭，失败恰恰是最强动力。好课题组关键在老板格局和组内环境。`,
	},
	{
		DisplayName:       "凝聚态自救xc",
		OriginalAuthor: "周鑫池",
		School:            "南方科技大学",
		MajorLine:         "凝聚态理论 PhD @ 北大ICQM",
		ScoreLine:         "GPA 3.88/4 (2/56), TOEFL 100",
		ArticleTitle:      "南科大飞跃手册 | 南科大凝聚态理论方向自救指南",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "分享国内凝聚态理论直博选择、夏令营面试技巧和南科大理论方向课程补课建议。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对凝聚态理论方向、国内直博选择或物理面试准备有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"凝聚态理论方向该出国还是国内直博？",
			"清华高研院和北大ICQM怎么选？",
			"南科大理论方向课程不够怎么补？",
		},
		ExpertiseTags: []string{"凝聚态理论", "北大ICQM", "直博", "飞跃手册", "物理"},
		Source: `南科大飞跃手册`,
		KnowledgeBody: `15级物理系，GPA 3.88/4排名2/56，TOEFL 100(口语23)，GRE 155V+167Q+3.0AW。最终选择北大ICQM凝聚态理论直博，另获HKUST和中科院物理所PhD口头offer。理论方向国内直博性价比更高——不能保证申到top60建议考虑清华高研院、北大ICQM、中科院物理所。夏令营大部分课题组已招满，不要拖到推免面试。南科大课程对理论方向不友好：课程过于简单浅显、缺少必要training。自救方法：尽早自学统计物理和固体物理、训练数值方法、通过讨论班研读前沿文章(需教授把关)、以课题为导向学习高阶概念。面试考基本概念，问到不会为止。`,
	},
}
