package yantuseed

// 南方科技大学飞跃手册系列。
// 原文版权归南方科技大学飞跃手册编辑委员会与原作者所有。
const sustechFeyueLongBioPrefix = "本文来自南方科技大学飞跃手册，著作权属原作者；以下为个人升学/求职经验，仅供参考。"

const (
	sustechAudience     = "正在准备升学或求职的同学，尤其是理工科背景。"
	sustechEducation    = "硕士/博士（已录取或就读）"
	sustechMajorLabel   = "申请方向"
	sustechKnowledgeCat = "升学求职经验"
)

var sustechKnowledgeTags = []string{"升学", "经验贴", "飞跃手册", "南方科技大学"}

var sustechFeyueCSProfiles = []Profile{
	{
		DisplayName:       "键盘敲敲敲",
		School:            "南方科技大学",
		MajorLine:         "CS 考研（国内读研）",
		ScoreLine:         "18级计算机系",
		ArticleTitle:      "南科大飞跃手册 | 计算机系考研攻略与经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "国内考研上岸CS方向，分享择校、复习、专硕学硕选择等实战经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在犹豫考研还是出国，或者想了解计算机考研的流程和技巧，欢迎提问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"考研选学硕还是专硕有什么区别？",
			"计算机考研如何择校？",
			"南科大本科考研需要注意什么？",
		},
		ExpertiseTags: []string{"考研", "计算机", "国内读研", "飞跃手册", "择校"},
		KnowledgeBody: `18级计算机系同学，国内考研方向。作者强调考研前一定要想清楚目标，不要跟风。文章详细介绍了学硕vs专硕（学硕侧重理论发paper，可直博；专硕侧重就业实习）、全日制vs非全日制、定向vs非定向等制度区别。择校方面，建议关注分数线体系（国家线/校线/专业线/自划线），结合科研投入、专业排名、就业意向、地理位置和难度综合选择。复习策略上建议尽早开始专业课准备，数学多刷题练手感，英语坚持背单词做阅读。考研拼的不是谁跑得快，而是谁能稳到最后。`,
	},
	{
		DisplayName:       "咖啡不加冰c",
		School:            "南方科技大学",
		MajorLine:         "CS MS @ CMU (Software Engineering)",
		ScoreLine:         "GPA 3.69/4, TOEFL 104, GRE 329",
		ArticleTitle:      "南科大飞跃手册 | CS Master申请CMU全攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA非顶尖但拿到CMU录取，分享美国CS硕士申请的全流程经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！我曾以非顶尖三维拿到CMU录取，关于美国CS Master申请有什么问题都可以问我。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GPA不到3.7能申到CMU吗？",
			"托福GRE和GPA哪个更重要？",
			"申请美国CS硕士如何选校和写文书？",
		},
		ExpertiseTags: []string{"美国留学", "CMU", "CS硕士", "飞跃手册", "选校"},
		KnowledgeBody: `16级计算机系，GPA 3.69/4，TOEFL 104，GRE V159+Q170+AW4.0。有IIT暑研课程和UC Berkeley学期交流经历。最终录取CMU软件工程硕士(MSE)，同时获得Rice、UCI、NYU Courant、NEU录取。作者认为重要性排序为GPA>TOEFL>GRE。建议大一寒假就开始准备GRE，先考GRE再考TOEFL，大四前考完英语比较安心。申请季从8月持续到次年4月，选校时每个项目都要问自己"如果只有这一个录取是否愿意去"。文书先写一个模版再针对不同学校修改，推荐信提前联系教授。活跃于一亩三分地论坛收集信息非常重要。`,
	},
	{
		DisplayName:       "代码写不停xy",
		School:            "南方科技大学",
		MajorLine:         "CS MS @ CMU (Software Engineering)",
		ScoreLine:         "GPA 3.82/4, TOEFL 104, GRE 325",
		ArticleTitle:      "南科大飞跃手册 | 19级CMU软件工程硕士申请记录",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "无交换无论文，一段暑研拿到CMU等多校录取，分享申请时间线与策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你和我一样没有交换和论文经历但想冲击好学校，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"没有论文和交换经历能申到CMU吗？",
			"一段暑研经历对申请有多大帮助？",
			"CMU不同CS硕士项目怎么选？",
		},
		ExpertiseTags: []string{"美国留学", "CMU", "暑研", "飞跃手册", "软件工程"},
		KnowledgeBody: `19级计算机系，GPA 3.82/4(排名15/156)，TOEFL 104，GRE V155+Q170+AW3.0。无交换、无论文，申请时无实习，一段UCI暑研。最终录取CMU SESV（软件工程硕士），另获UIUC MCS、JHU、UCI、WUSTL、USC、NTU MSAI录取，被NWU、NYU Courant、Wisc、UMich、UCSD、GaTech、Columbia、Duke、UC Davis PhD拒。申请材料12月至1月提交，2月开始陆续出结果。建议申请时合理分配冲刺/主申/保底档次，多申几个项目增加录取概率。`,
	},
	{
		DisplayName:       "极客老方yd",
		School:            "南方科技大学",
		MajorLine:         "CS MS @ UW-Madison",
		ScoreLine:         "GPA 3.87/4 (Rank 1/98), TOEFL 99, GRE 324",
		ArticleTitle:      "南科大飞跃手册 | 系排名第一的CS Master申请心得",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA系第一、TOEFL口语偏低但拿到UW-Madison和PhD Offer，分享申请遗憾与建议。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于CS申请中GPA、托福、暑研、文书等方面的问题欢迎提问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GPA第一但托福口语低怎么办？",
			"UCLA CSST暑研经历是什么样的？",
			"文书和推荐信有多重要？",
		},
		ExpertiseTags: []string{"美国留学", "UW-Madison", "CSST暑研", "飞跃手册", "GPA"},
		KnowledgeBody: `15级计算机系，GPA 3.87/4排名1/98，TOEFL 99(口语20)，GRE 155V+169Q+3.0AW。最终录取UW-Madison CS硕士，另获Stony Brook PhD Offer和UMass AD。参加过UCLA-CSST暑研和腾讯实习。作者大一开始注重课业，选高质量课程保持系第一GPA。最大遗憾是托福口语偏低，建议早考早分手。文书要突出个人特点并与申请项目match，不要与简历重复，找native润色。选校参考一亩三分地往年数据。不要为了出国而出国，要想清楚自己想要什么。`,
	},
	{
		DisplayName:       "安全研究员rx",
		School:            "南方科技大学",
		MajorLine:         "CS PhD @ U of Delaware (Security)",
		ScoreLine:         "GPA 3.73/4, TOEFL 90, No GRE",
		ArticleTitle:      "南科大飞跃手册 | Security方向PhD申请实录",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "随性风格、条件不突出的CS PhD申请者，分享在困难年份拿到全奖offer的经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！如果你对CS Security方向的PhD申请感兴趣，或者条件一般但想试试PhD，欢迎聊聊。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"条件一般怎么申请CS PhD？",
			"PhD申请中套磁有什么注意事项？",
			"托福90分够申PhD吗？",
		},
		ExpertiseTags: []string{"PhD申请", "安全方向", "套磁", "飞跃手册", "美国留学"},
		KnowledgeBody: `21级计算机系，GPA 3.73/4(64/195)，TOEFL 90，无GRE，无论文。申请方向CS Security，有UCI暑研经历。在25Fall这个近5年最难的申请季（经费大砍），最终拿到U of Delaware全奖PhD offer，另获VCU、Michigan Tech、UT Arlington offer。作者风格随性注重work-life-balance，强调心态最重要。套磁建议不要发模板，注意教授主页暗号要求。中介最大作用是整理信息列表，选校和文书应自己完成。英语对排名不太高的学校没那么重要，GRE非必须可不考。年薪36000刀，免税州生活成本低。`,
	},
	{
		DisplayName:       "鹿仔ECE冲",
		School:            "南方科技大学",
		MajorLine:         "ECE MS @ CMU",
		ScoreLine:         "GPA 3.86/4, TOEFL 103, GRE 148V+170Q",
		ArticleTitle:      "南科大飞跃手册 | 图灵班到CMU ECE硕士的申请之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "图灵班同学申请CMU ECE硕士，分享从焦急等待到收获offer的完整流程。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于CMU ECE项目或者美国硕士申请流程有什么问题都可以问我。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"CMU ECE硕士项目怎么样？",
			"港新和美国硕士怎么选？",
			"申请季焦虑怎么调节心态？",
		},
		ExpertiseTags: []string{"美国留学", "CMU", "ECE", "飞跃手册", "图灵班"},
		KnowledgeBody: `21级计算机系（图灵班），GPA 3.86/4(排名15/195)，TOEFL 103(口语20)，GRE 148V+170Q+3.5AW。最终录取CMU ECE硕士，另获Rice MCS录取。被CMU MSIN、UCSD CS75、Notre Dame CS PhD拒，港新多项待定。整个寒假焦急等待，每天刷邮箱和Reddit、小红书，开学后第二周收到首个offer。文章按时间轴复盘申请流程，分享使用的工具和踩过的坑。建议提前做好文书准备和推荐信安排，关注各项目截止日期差异。`,
	},
	{
		DisplayName:       "医工交叉sr",
		School:            "南方科技大学",
		MajorLine:         "AI+Biomedical PhD @ UCLA",
		ScoreLine:         "GPA 3.77/4, TOEFL 106",
		ArticleTitle:      "南科大飞跃手册 | 后疫情时代北美AI+医学交叉方向PhD申请",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "AI+生物医学交叉方向，经历两个申请季最终拿到UCLA PhD全奖，分享详细方法论。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对AI+医学交叉方向的PhD申请、gap year策略或暑研选择有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"申PhD被拒后gap一年再申靠谱吗？",
			"AI+医学交叉方向怎么准备？",
			"推荐信和connection对PhD申请有多重要？",
		},
		ExpertiseTags: []string{"PhD申请", "AI医学", "gap year", "飞跃手册", "暑研"},
		KnowledgeBody: `20级计算机系，GPA 3.77/4(排名30-35/220)，TOEFL 106，GRE 315。AI+Biomedical交叉方向，经历24Fall和25Fall两个申请季。24Fall：MICCAI workshop一作两篇、ISBI论文多篇，但PhD全拒（多个口头offer被缩招砍掉），仅获NYU Courant硕和NTU MSAI录取。Gap后25Fall增加Northwestern线上RA和Stanford postdoc线上RA，最终获UCLA CompMed PhD全奖offer（最终去向）和Northwestern BME PhD。文章事无巨细分享方法论，强调推荐信/connection>>高质量研究经历>GPA>标化成绩。建议混申硕士做保底，避免申"PhD保底校"。`,
	},
	{
		DisplayName:       "保研小白zq",
		School:            "南方科技大学",
		MajorLine:         "CS 保研 @ 南方科技大学",
		ScoreLine:         "GPA 3.63/4 (Rank 19/98)",
		ArticleTitle:      "南科大飞跃手册 | 本校保研CS硕士的心路历程",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "在出国、就业和保研间权衡，最终选择本校三年学硕，分享保研流程和教训。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于南科大本校保研流程、夏令营准备或境内升学选择有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"南科大保研流程是什么样的？",
			"计算机系保研夏令营考什么？",
			"保研还是出国读硕怎么选？",
		},
		ExpertiseTags: []string{"保研", "国内读研", "夏令营", "飞跃手册", "南科大"},
		KnowledgeBody: `15级计算机系，GPA 3.63/4排名19/98。原计划出国但英语没准备好，大三暑假在某大厂实习6个月（测试工程师，实际做全栈工作）。保研流程：4-6月准备申请材料参加夏令营，7-8月参营获接收资格（A），9-10月获本校推送资格（B），A和B缺一不可。本校夏令营有笔试（数据结构、数据库、计网、操作系统）和面试。最终在保研/联培/就业/自主申请中选择了本校三年学硕。教训：想出国就早考英语，推迟实习；实习比较占时间。2019届起本校硕士改为3年学术型硕士。`,
	},
	{
		DisplayName:       "系统狂魔wd",
		School:            "南方科技大学",
		MajorLine:         "CS MS @ UCSD",
		ScoreLine:         "GPA 3.80/4, TOEFL 107, GRE 327",
		ArticleTitle:      "南科大飞跃手册 | UCSD CS硕士申请与MS/PhD选择思考",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA Top5%、SIGMOD竞赛入围者，分享UCSD等美国名校CS硕士申请经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于美国CS硕士申请、MS vs PhD选择、或者美国/新加坡/香港的比较有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"UCSD CS75项目怎么样？",
			"该选MS还是PhD？",
			"美国、新加坡、香港硕士怎么对比？",
		},
		ExpertiseTags: []string{"美国留学", "UCSD", "CS硕士", "飞跃手册", "选校"},
		KnowledgeBody: `17级计算机系，GPA 3.80/4(Top5%)，TOEFL 107(Best 109)，GRE V158+Q169+AW3.5。有NUS暑期项目、UC Berkeley学期交流和SIGMOD编程竞赛World Finalist经历。因疫情同时申请内地+港新+美国。最终录取UCSD CS75，另获GaTech MSCS、NEU MSDS、CUHK(SZ) MSDS、USC、NUS MSCS录取，被CMU MCDS、NWU、UMich、Brown、HKUST、NYU拒。关于MS vs PhD：需考虑科研兴趣和能力，如果都满足可读PhD。美国MS优点是教学好、留美就业好，缺点是学费高、签证和治安问题。新加坡性价比高适合过渡。`,
	},
	{
		DisplayName:       "浙软上岸ysh",
		School:            "南方科技大学",
		MajorLine:         "CS 保研 @ 浙江大学",
		ScoreLine:         "GPA 3.81 (Rank 8/145)",
		ArticleTitle:      "南科大飞跃手册 | 计算机系保研浙大软院经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "保研外校最大的困难是简历关，分享计系保研浙大的经验与套磁技巧。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于国内保研、夏令营简历筛选、面试准备等有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"南科大CS保研外校难度大吗？",
			"保研夏令营简历怎么过筛？",
			"为什么选择保研而不是出国？",
		},
		ExpertiseTags: []string{"保研", "浙大", "夏令营", "飞跃手册", "套磁"},
		KnowledgeBody: `17级计算机系，GPA 3.81排名8/145，有腾讯游戏客户端实习经历。最终保研至浙江大学软件学院专硕。计系保研名额约33个，其中本系老师可招21位，剩下12位需自行寻找接收单位（不兜底）。保研外校最大困难在于简历关——投递各大高校计算机学院碰壁无数，最终只被浙大软院和清华伯克利学院录进夏令营。建议3-4月提前联系导师套磁，用gmail而非南科大企业邮箱以免对方收不到。如果打算保研外校，暑期不建议实习，精力应放在夏令营准备上。国内一流实验室不比国外差，有好的国内机会值得考虑。`,
	},
	{
		DisplayName:       "NUS打工人yl",
		School:            "南方科技大学",
		MajorLine:         "CS MS @ NUS (MComp)",
		ScoreLine:         "GPA 3.75/4, IELTS 7.0, GRE 322",
		ArticleTitle:      "南科大飞跃手册 | NUS MComp CS硕士申请与就读体验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "All in NUS MComp并成功上岸，分享申请心得和新加坡就读真实体验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！如果你对NUS MComp项目、港新CS硕士申请、或新加坡生活有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"NUS MComp CS项目值得all in吗？",
			"港新CS硕士项目怎么比较？",
			"NUS的就读体验和就业前景如何？",
		},
		ExpertiseTags: []string{"新加坡留学", "NUS", "CS硕士", "飞跃手册", "就业"},
		KnowledgeBody: `20级计算机系（从智能医学工程转入），GPA 3.75/4(排名38/220)，IELTS 7.0，GRE 322+4。有NUS Summer Workshop、三段科研（一篇非CCF论文一作）、三段小厂实习。24Fall all in NUS MComp，获NUS MComp CS、HKU CS、HKUST IT录取。NUS MComp是港新CS master中bar最高的项目之一，下offer最晚（5-6月），需考虑是否扛得住焦虑和留位费。项目6万新币，灵活选择1/1.5/2年毕业。新加坡就业机会好（TikTok、NVIDIA等），转博友好（dissertation选项可进入lab）。推荐信比重很高，一封好的科研推可弥补很多不足。建议做六边形战士或在一个方向深耕。`,
	},
	{
		DisplayName:       "中科大梦yl",
		School:            "南方科技大学",
		MajorLine:         "CS 保研 @ 中国科学技术大学",
		ScoreLine:         "GPA 3.89/4 (Top 5-10%)",
		ArticleTitle:      "南科大飞跃手册 | 双非保研中科大CS硕士的经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "双非背景保研中科大，分享夏令营海投、笔试面试和专业课复习技巧。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于双非学校保研到名校的流程、夏令营筛选策略有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"双非保研名校需要什么条件？",
			"保研夏令营笔试考什么内容？",
			"GPA和科研竞赛怎么平衡？",
		},
		ExpertiseTags: []string{"保研", "中科大", "夏令营", "飞跃手册", "双非"},
		KnowledgeBody: `21级计算机系，GPA 3.89/4，夏令营时排名11/189(Top10%)，预推免时进入9/194(Top5%)。建模国赛国二+美赛H奖，六级524。最终保研中科大硕士。夏令营海投：南大CS挂了（不会编译原理和OS）、清深/东南/人大/同济/复旦拒、杭高院+中科大10系+浙软优营。预推免南大CS和浙软优营。作者强调双非保研初筛最看重GPA和排名，很多学校双非只放排名前5%。六级过480即可。面试主要看专业知识和项目，需提前复习数据结构、OS、计网、编译原理等专业课。建议尽早规划，保证GPA的同时积累竞赛和论文。`,
	},
	{
		DisplayName:       "CMU多面手yc",
		School:            "南方科技大学",
		MajorLine:         "CS MS @ CMU (MIIS)",
		ScoreLine:         "GPA 3.79/4, TOEFL 106, GRE 322",
		ArticleTitle:      "南科大飞跃手册 | MS与PhD双线并行的CMU申请策略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "MS和PhD两条线并行，拿到CMU MIIS和UCSD等多校录取，分享四年规划建议。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于MS/PhD选择、多线并行申请策略或CMU项目有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"MS和PhD应该如何选择？",
			"申请季两条线并行累不累？",
			"CMU MIIS项目怎么样？",
		},
		ExpertiseTags: []string{"美国留学", "CMU", "PhD申请", "飞跃手册", "规划"},
		KnowledgeBody: `21级计算机系，GPA 3.79/4(大三rk8)，TOEFL 106，GRE V153+Q169+AW3.5。有MIT在线课程、NUS暑期项目、NTU访问研究等交流经历，三段实习，申请时无AC论文但有多篇在投。获CMU MIIS、UCSD CS75、HKUST MSAI、CUHK MSCS、NTU MSAI、Notre Dame MSCSE、USC CS28、JHU MSCSE录取。被UChicago、GaTech、Cornell等拒。一直没决定读PhD还是MS所以两条线并行。PhD优势：学术积累、不急就业、更好出路；问题：时间长、方向可能过时。MS优势：时间短、立即就业。建议看不进论文就无脑选MSc。推荐四年规划：大一考英语，大二进实验室，大三暑研，大四申请。`,
	},
	{
		DisplayName:       "赌博少女_yt",
		School:            "南方科技大学",
		MajorLine:         "CS PhD @ UC Davis (Software Engineering)",
		ScoreLine:         "GPA 3.72/4, TOEFL 104, GRE 320",
		ArticleTitle:      "南科大飞跃手册 | 从零科研到CS PhD申请的逆袭故事",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA说高不高，从零科研起步拿到6个PhD offer，分享模板海套法和面试技巧。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你和我一样背景普通但想申请CS PhD，关于套磁、面试、科研经历积累都可以问我。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"背景一般怎么申请CS PhD？",
			"模板海套法是什么？",
			"KAUST科研实习项目值得去吗？",
		},
		ExpertiseTags: []string{"PhD申请", "套磁", "KAUST", "飞跃手册", "科研"},
		KnowledgeBody: `16级计算机系，GPA 3.72/4(排名25/146)，TOEFL 104，GRE 150V+170Q+3.5W。有UCI暑研和KAUST科研实习经历。申请时无论文，后来一篇一作发表在SIGKDD(CCF-A)。全部申请PhD，申10中6：UC Davis(最终去向，带fellowship)、UCI SE PhD(带fellowship)、PSU、NEU、Virginia Tech、UT Dallas offer。秘诀是"模板海套"法：先简洁列出自己的闪光点，再根据每位教授的研究兴趣做match，套磁一个老师只需10-20分钟。15个老师13个回复，11个面试邀请。KAUST科研实习让作者发现了对科研的热爱，是高风险超高回报的决定。关键是及时发现薄弱点并争取机会弥补。`,
	},
	{
		DisplayName:       "沙特体验官w",
		School:            "南方科技大学",
		MajorLine:         "KAUST VSRP 科研实习",
		ScoreLine:         "GPA 3.7+, TOEFL 100+",
		ArticleTitle:      "南科大飞跃手册 | 为什么推荐去KAUST做科研实习",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "分享在沙特KAUST做3-6个月带薪科研实习的体验与申请攻略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对KAUST VSRP科研实习项目或海外科研实习有兴趣，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"KAUST VSRP项目是什么？",
			"去沙特做科研安全吗？",
			"科研实习对申请有什么帮助？",
		},
		ExpertiseTags: []string{"科研实习", "KAUST", "海外经历", "飞跃手册", "暑研"},
		KnowledgeBody: `16级计算机系同学介绍KAUST VSRP(Visiting Student Research Program)科研实习。项目时长3-6个月，每月1000美元工资+机票住宿全包+海边别墅住宿。申请条件：大三或研一在读、GPA 3.5+、需英语成绩。3月中旬开始套磁教授，3月底面试并获同意，4-7月等待，7月底获正式通知，9月下旬抵达。作者动机：体验阿拉伯文化、专心科研的机会、获海外推荐信、丰富软背景。沙特天气10月后舒适，校内生活设施齐全。这段经历帮助作者发现对科研的热爱，是后续PhD申请的关键亮点。`,
	},
	{
		DisplayName:       "安卓小哥km",
		School:            "南方科技大学",
		MajorLine:         "安卓开发工程师 @ 华为",
		ScoreLine:         "放弃保研直接就业",
		ArticleTitle:      "南科大飞跃手册 | 放弃保研选择华为安卓开发的故事",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "放弃保研的异类，通过实习转正拿到华为安卓开发offer，分享面试和求职心得。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在纠结读研还是就业，或者想了解CS本科直接求职的经验，欢迎交流。",
		Education:         "本科（已就业）",
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"CS本科直接就业可行吗？",
			"为什么放弃保研选择工作？",
			"华为面试准备什么内容？",
		},
		ExpertiseTags: []string{"就业", "华为", "安卓开发", "飞跃手册", "面试"},
		KnowledgeBody: `16级计算机系，有华为安卓开发实习和Java学生助理经历。最终就业华为消费者云服务安卓开发岗。放弃保研原因：不喜欢AI和深度学习的繁琐公式，对研究生生活有顾忌。大三暑假在华为实习两个多月，参与会员中心开发。面试准备：项目经历要熟悉用到的框架和难点；刷剑指Offer和LeetCode；计网、数据库、操作系统、面向对象四门课重点复习。技术栈要深入而非广泛，至少分清前端还是后端。时间节点：3-5月实习招聘，7-11月秋招。建议多投多面打怪升级，心态要好抗压能力强。不要盲目选互联网，不是真的喜欢就不要来。`,
	},
	{
		DisplayName:       "腾讯刷题王yh",
		School:            "南方科技大学",
		MajorLine:         "后台开发 @ 腾讯",
		ScoreLine:         "ACMer 刷题破千",
		ArticleTitle:      "南科大飞跃手册 | ACMer如何拿到腾讯后台开发offer",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "ACM刷题破千、不想搞研究选择直接就业，分享腾讯实习和秋招面试经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于互联网大厂面试、后台开发求职或者实习转正策略有什么问题都可以问。",
		Education:         "本科（已就业）",
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"如何准备互联网大厂面试？",
			"实习对秋招有多重要？",
			"CS本科为什么选择就业而不是读研？",
		},
		ExpertiseTags: []string{"就业", "腾讯", "后台开发", "飞跃手册", "面试"},
		KnowledgeBody: `16级计算机系，ACMer刷题破千，数据结构课学生助理。最终就业腾讯PCG战略管理中心。选择就业原因：不想搞research、天花板取决于能力不是学历、早工作早晋升。先后在腾讯IEG游戏AI研究中心（算法岗）和CDG广点通（后台开发）实习近5个月。校招三个月，四轮面试（技术面、总监面、总经理面、HR面）。简历需列举项目经历、获奖经历、GitHub主页、技术博客。技术储备Java/C++/Python/Golang至少精通一门。计网、数据库、OS、面向对象四门课重点复习。实习很重要，可以直接转正省去秋招。`,
	},
	{
		DisplayName:       "Purdue宁神dn",
		School:            "南方科技大学",
		MajorLine:         "CS PhD @ Purdue University",
		ScoreLine:         "GPA 3.85/4 (Rank 3/98), TOEFL 106, GRE 323",
		ArticleTitle:      "南科大飞跃手册 | Purdue CS PhD面经与申请全攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "系排名前三获Purdue CS PhD，分享最有价值的PhD面经和选校策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于CS PhD面试准备、套磁策略和选校有什么问题都可以问我。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"PhD面试一般会问什么问题？",
			"SOP里应该只提一个导师的名字吗？",
			"三月中旬后没面试还有希望吗？",
		},
		ExpertiseTags: []string{"PhD申请", "Purdue", "面试", "飞跃手册", "选校"},
		KnowledgeBody: `15级计算机系，GPA 3.85/4排名3/98，TOEFL 106(口语23)，GRE 155V+168Q+3.0AW。最终录取Purdue CS PhD，另获UTDallas CS PhD和UCI SE PhD(带Dean Scholarship)。面试心得：能拿到面试说明离offer只一步之遥；英语好很加分；SOP里只提一个导师非常加分（一位教授说只有作者一个人这样做并给了offer）。面试必问：自我介绍、Why PhD、Why School、Other Schools、Research Experience、研究计划。建议事先读导师1-2篇论文，选与研究方向匹配的顶会文章。三月中旬后没面试基本希望不大。面试时可将答案写在Word里分屏参考，但不要看起来在念。`,
	},
	{
		DisplayName:       "UCI搞基侠xy",
		School:            "南方科技大学",
		MajorLine:         "CS PhD @ UC Irvine",
		ScoreLine:         "GPA 3.85/4 (Rank 3/98), TOEFL 102, GRE 318",
		ArticleTitle:      "南科大飞跃手册 | 从机械到CS PhD的探索之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "伴随计算机系成立与成长，通过暑研拿到UCI CS PhD，分享培养Geeky精神的经历。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于暑研项目选择、申请北美CS PhD的经验或培养计算机素养有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"暑研对北美PhD申请有多重要？",
			"如何培养Geeky的计算机素养？",
			"计系暑研项目有哪些选择？",
		},
		ExpertiseTags: []string{"PhD申请", "UCI", "暑研", "飞跃手册", "科研"},
		KnowledgeBody: `15级计算机系，GPA 3.85/4排名3/98，TOEFL 102(口语23)，GRE 149V+169Q+3.5AW。最终录取UCI CS PhD，另获CUHK和HKU PhD。大一机械系暑期认知实习后确定转CS。大二培养Geeky精神——追求广度打基础养习惯，强调用英文搜索和debug。大量看海外网课练听力(youtube-dl下载)，地铁飞机上随时看。大三在先进院MMLAB实习，之后参加UCInspire暑研（导师推荐信非常管用）。认为暑研是北美CS PhD申请的关键：暑研项目走F1签证容易，自己套磁走J1签证困难。推荐信重要性：北美知名教授强推>了解你的大陆教授走心推>很牛但不了解你的教授推。`,
	},
	{
		DisplayName:       "暑研安利员xy2",
		School:            "南方科技大学",
		MajorLine:         "暑研对北美PhD申请的重要性",
		ScoreLine:         "15级计算机系",
		ArticleTitle:      "南科大飞跃手册 | 暑研对北美CS PhD申请的重要性",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "深度分析计系暑研项目与推荐信策略，帮助理解北美PhD申请核心要素。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于暑研项目选择、推荐信策略或北美PhD申请规划有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"没有暑研能申到好学校PhD吗？",
			"推荐信的有效性怎么判断？",
			"CSST和UCInspire暑研项目怎么选？",
		},
		ExpertiseTags: []string{"暑研", "PhD申请", "推荐信", "飞跃手册", "CSST"},
		KnowledgeBody: `15级计算机系同学深度分析暑研对北美CS PhD申请的重要性。核心观点：在计系没有北美暑研经历基本不可能申到好学校PhD。原因：CS申请pool极度饱和，推荐信是最重要因素，而系里大部分教授博士毕业于港英日新，北美connection有限。暑研项目（走F1学生签）成功概率远高于自己套磁（走J1访问学者签）。推荐的暑研项目：UCLA CSST（难度高、不花钱）、UCI UCInspire（一年比一年难、约3-4万）。推荐信有效性排序：北美知名教授强推(五星)>外国知名教授强推(四星)>了解你的大陆教授走心推(三星)>很牛但不了解你的大陆教授推(没用)。`,
	},
	{
		DisplayName:       "NEU安全侠rg",
		School:            "南方科技大学",
		MajorLine:         "CS PhD @ Northeastern University (Security x SE)",
		ScoreLine:         "GPA 3.78/4, TOEFL 105, No GRE",
		ArticleTitle:      "南科大飞跃手册 | 22级Security方向PhD申请策略分享",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "非顶尖选手靠精准选校和材料打磨拿到NEU等PhD offer，分享选导师与文书策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于CS Security方向PhD申请、选导师策略和申请材料有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"非顶尖背景怎么选PhD导师？",
			"PhD申请中SOP怎么写？",
			"套磁和正式申请该怎么配合？",
		},
		ExpertiseTags: []string{"PhD申请", "安全方向", "选校", "飞跃手册", "文书"},
		KnowledgeBody: `22级计算机系，GPA 3.78/4，TOEFL 105，无GRE。申请方向Security x SE，有校内课题组科研一年、UC Davis暑研三个月+线上四个月（产出一篇顶会一作在投）、UCLA线上科研。三封科研推（两封北美tenure教授强推）+一封课程推。拿到NEU CS PhD offer(最终去向)、IUB offer、UCLA口头offer、VT waitlist等。作者认为对非顶尖选手，选校本质是选导师，与导师匹配度是最关键因素。匹配度分强/中/弱match。SOP中先写经历再定制化学校段，每个学校只提一两个POI。建议有精力就海套，通过套磁回复率判断申请梯度。`,
	},
	{
		DisplayName:       "NEU找工人whf",
		School:            "南方科技大学",
		MajorLine:         "CS MS @ NEU (Silicon Valley)",
		ScoreLine:         "GPA 3.73/4, TOEFL 106, GRE 326",
		ArticleTitle:      "南科大飞跃手册 | NEU硅谷校区CS硕士申请与求职分析",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "不算最优秀但实际的申请分享，分析Rice vs NEU硅谷校区的就业导向选择。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于美国CS硕士求职导向选校、NEU硅谷校区体验或签证BUG有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"NEU硅谷校区CS硕士值得去吗？",
			"美国CS硕士怎么选求职导向的项目？",
			"本科交换能解决签证check问题吗？",
		},
		ExpertiseTags: []string{"美国留学", "NEU", "求职", "飞跃手册", "硅谷"},
		KnowledgeBody: `19级计算机系，GPA 3.73/4(排名23%)，TOEFL 106，GRE 156V+170Q+3.5。无交换、无论文，一段大厂实习，一个专利在申。最终去向NEU(Silicon Valley) MSCS，另获Rice MSCS、USC MSCE、BU MSCS、CityU MSCS、UW(Tacoma) MSCS录取。选择NEU硅谷校区而非Rice的原因：虽然Rice排名好看，但NEU有Coop政策和硅谷地理位置优势，在美找工更方便。签证BUG：本科去美国交换可拿五年F1签证，读硕时继续使用，避免CS专业被check只拿一年签。香港学校留位费很高且出结果快，如仅保底建议晚申。NEU硅谷校区没有校园只有两层楼，但"当技校读服务不错"。`,
	},
	{
		DisplayName:       "设计转码云zx",
		School:            "南方科技大学",
		MajorLine:         "IoT MS @ CMU / EE MS @ UW Seattle",
		ScoreLine:         "GPA 3.68/4 (南科大) + 4.0/4 (UCB交流), TOEFL 108",
		ArticleTitle:      "南科大飞跃手册 | SDIM跨专业申请美国CS/ECE硕士",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "SDIM第一期毕业生，跨专业DIY申请CMU和UW硕士，分享转专业申请策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于跨专业申请CS/ECE硕士、Berkeley交流或DIY申请有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"非CS专业怎么跨申CS/ECE硕士？",
			"DIY申请需要注意什么？",
			"PhD和Master该怎么选？",
		},
		ExpertiseTags: []string{"跨专业", "CMU", "UW", "飞跃手册", "DIY申请"},
		KnowledgeBody: `SDIM(系统设计与智能制造)学院工业设计专业第一期毕业生，GPA 3.68/4(南科大)+4.0/4(UC Berkeley交流)，TOEFL 108，GRE 319。有UCB机械系URAP学年科研和EECS暑期科研经历。全部DIY申请11个项目收到2个录取：CMU MSMITE(移动和物联网工程硕士，最终去向)和UW Seattle MSEE。转专业定位偏高导致8个REJ。Master尽量申名校（业界看学校名声），PhD则导师chemistry更重要。文书在Fiverr找native speaker做语法修改。选校时估算每个学校录取概率，控制非全聚德概率在90%左右。`,
	},
	{
		DisplayName:       "清华设计师tg",
		School:            "南方科技大学",
		MajorLine:         "设计学硕 @ 清华 + MIT ME (SM)",
		ScoreLine:         "GPA 3.86/4 (Rank 1/28), 六级636, 雅思7.0",
		ArticleTitle:      "南科大飞跃手册 | SDIM到清华+MIT双学位的跨界升学路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "SDIM专业排名第一，先保研清华后申到MIT机械硕士，分享跨界规划与选择。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于跨界申请、清华保研、MIT交流或设计与工程方向选择有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"SDIM专业有哪些升学方向？",
			"如何从设计转到工程方向深造？",
			"清华+MIT双学位项目是什么体验？",
		},
		ExpertiseTags: []string{"清华", "MIT", "设计", "飞跃手册", "跨界"},
		KnowledgeBody: `SDIM学院工业设计专业，GPA 3.86/4排名1/28，六级636，雅思7.0。有IC-RCA线上项目、MIT机械系学年交流等经历。Robomaster全国一等奖，MIT机械系学生创新奖。大四保研清华设计学硕+UW MSTI双学位项目，研一申请季获MIT机械工程硕士SM录取。MIT交流期间在Media Lab做科研助理，产出一篇会议论文和专利。先确定就业vs读研、国内vs国外、PhD vs Master三个问题。保研面试经历丰富（清华/上交），建议自信表达、对研究方向有思考。大四申请季和研一申请季的经历表明持续积累、把握机会很重要。`,
	},
	{
		DisplayName:       "CMU数据蕾al",
		School:            "南方科技大学",
		MajorLine:         "CS MS @ CMU (MCDS)",
		ScoreLine:         "GPA 3.85/4 (Rank 7/163), TOEFL 107, GRE 331",
		ArticleTitle:      "南科大飞跃手册 | CMU计算数据科学硕士申请经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "拿到CMU三个项目录取和Columbia等名校AD，分享详细申请时间线和选校思路。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于CMU多项目申请策略、选校定位或美国CS硕士申请有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"CMU可以同时申几个项目吗？",
			"GRE 330+对申请有多大帮助？",
			"CMU MCDS项目体验如何？",
		},
		ExpertiseTags: []string{"美国留学", "CMU", "数据科学", "飞跃手册", "选校"},
		KnowledgeBody: `18级计算机系，GPA 3.85/4排名7/163，TOEFL 107(口语25)，GRE 163V+168Q+3AW。最终录取CMU MCDS(计算数据科学硕士)，另获CMU MSIN、CMU MISM、Columbia MSCS、UC Berkeley IEOR Meng、NYU MSCE录取。被CMU MHCI、Brown、Rice、Cornell、UCSD CS75、Georgia Tech HCI、UCLA拒。11月中旬提交申请，3月初起陆续出结果。作者建议选校时关注项目特点和就业方向，不仅看学校排名。CMU可以同时申请多个学院的项目，增加录取概率。申请季今年美硕出结果特别晚，需要耐心等待。`,
	},
	{
		DisplayName:       "阿尔托HCI柯",
		School:            "南方科技大学",
		MajorLine:         "HCI MS @ Aalto (全奖)",
		ScoreLine:         "GPA 3.93/4 (Rank 1/13), TOEFL 103, GRE 326",
		ArticleTitle:      "南科大飞跃手册 | SDIM到Aalto HCI全奖硕士的探索之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "SDIM专业排名第一，在设计与科研间纠结后选择HCI方向，获欧洲顶级全奖硕士。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于HCI方向申请、欧洲硕士项目或设计与科研方向选择有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"Aalto HCI硕士项目怎么样？",
			"设计和科研方向怎么选择？",
			"欧洲硕士和美国硕士怎么比较？",
		},
		ExpertiseTags: []string{"HCI", "Aalto", "欧洲留学", "飞跃手册", "设计"},
		KnowledgeBody: `SDIM学院工业设计专业（南山三期），GPA 3.93/4排名1/13，TOEFL 103，GRE 326(170Q+156V)。有新加坡创业实习交换、一篇水会共一、两段初创公司实习、一个设计竞赛二等奖。最终录取Aalto HCI全奖硕士（100%学费减免，欧洲HCI排名CSrankings第一）。另获KTH、TU Delft、UMich MSI、NUS EDI、NUS DID、EIT项目录取。SDIM专业特殊：一直纠结设计vs科研，大三十二月才下定决心转设计方向。之前的计算机科研背景反而成为HCI申请独特优势。建议多找学长学姐聊天、早做决定但探索不浪费。纯DIY申请，作品集和PS质量很关键。`,
	},
	{
		DisplayName:       "求职蚂蚁st",
		School:            "南方科技大学",
		MajorLine:         "后台开发 @ 蚂蚁金服",
		ScoreLine:         "学业成绩过得去，有项目经历和腾讯实习",
		ArticleTitle:      "南科大飞跃手册 | CS本科求职蚂蚁金服后台开发经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "腾讯实习后最终入职蚂蚁金服，分享CS本科求职时间线和面试技巧。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于CS本科求职、互联网大厂面试准备或实习策略有什么问题都可以问。",
		Education:         "本科（已就业）",
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"CS本科求职如何准备简历？",
			"面试中专业基础怎么复习？",
			"实习对秋招有多大帮助？",
		},
		ExpertiseTags: []string{"就业", "蚂蚁金服", "后台开发", "飞跃手册", "面试"},
		KnowledgeBody: `15级计算机系，学业成绩过得去，有项目经历和腾讯实习。腾讯实习转正offer因个人原因未接受，最终去向蚂蚁金服。求职时间线：3-5月实习招聘、7-11月秋招、次年1-3月春招补录。简历需针对岗位编写，体现项目中个人角色和技术栈，不写无关社团和爱好。基础准备重点：编程语言、数据结构与算法、OS、数据库、计网、编译原理。面试是主要筛人环节，每次面试后记录不会的问题查漏补缺。建议多投多面打怪升级。秋招是最合适时机，即使有转正offer也建议秋招多投给自己选择余地。`,
	},
	{
		DisplayName:       "APS攻略xq",
		School:            "南方科技大学",
		MajorLine:         "CS MS @ KTH (欧陆)",
		ScoreLine:         "20级计算机系",
		ArticleTitle:      "南科大飞跃手册 | 南科大CS学生APS审核与欧陆申请指北",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "分享南科大CS学生APS审核全流程和欧陆硕士申请经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！如果你对APS审核流程、欧陆CS硕士申请或KTH项目有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"APS审核流程和时间线是怎样的？",
			"南科大学生APS材料怎么准备？",
			"欧陆CS硕士申请有什么注意事项？",
		},
		ExpertiseTags: []string{"欧陆留学", "APS审核", "KTH", "飞跃手册", "德国"},
		KnowledgeBody: `20级计算机系同学，最终去向KTH CS硕士。详细分享APS审核（德国高校录取中国学生前提条件）的完整流程。时间线：10月底准备材料，11月初寄出，12月中面试，12月底通过（"gut"）。总共约两个月。材料准备涉及高中毕业证公证翻译、大学录取花名册（在招生办获取）、在读证明和成绩单等。面试准备：针对成绩单上的课程复习，面试官会用英文问专业课内容。建议完成六个学期课业后尽早准备，课程少则询问范围少、知识新鲜。南科大特殊情况：义务教育证需涵盖完整九年。小红书上有更多欧陆申请经验分享。`,
	},
	{
		DisplayName:       "北大菁英st2",
		School:            "南方科技大学",
		MajorLine:         "CS 保研 @ 北京大学",
		ScoreLine:         "GPA 3.67/4 (Rank 15/98), 两篇共同一作论文",
		ArticleTitle:      "南科大飞跃手册 | 保研北大创新菁英计划的经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "排名不高但靠论文加分通过北大初审，分享保研夏令营面试和专业课技巧。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于国内名校保研、夏令营面试准备或科研论文对保研的帮助有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"排名不高怎么保研到北大？",
			"论文对保研面试有多大帮助？",
			"保研夏令营面试有什么技巧？",
		},
		ExpertiseTags: []string{"保研", "北大", "论文", "飞跃手册", "夏令营"},
		KnowledgeBody: `15级计算机系，GPA 3.67/4排名15/98，两篇共同一作论文（医学影像辅助诊断方向），无TOEFL/GRE。最终保研北京大学创新菁英计划硕士，另获清华深研院精准医学硕士offer，被清华叉院拒。夏令营初审最看重排名（学校属性+个人排名），深研院标准约985 Top20%/211 Top10%/其他Top3。论文在初审时有加分——招生老师说排名不够标准但论文让他通过了。面试时所有老师围绕论文问问题，一定要对简历上每个细节非常熟悉。教训：一定把专业课学习放第一位，GPA掉0.1可能让很多初审过不了。早考英语、早做规划。`,
	},
	{
		DisplayName:       "港大PM菁yj",
		School:            "南方科技大学",
		MajorLine:         "IDT MS @ HKU (产品经理方向)",
		ScoreLine:         "GPA 3.70/4 (Rank 79/195), IELTS 6.5",
		ArticleTitle:      "南科大飞跃手册 | CS转产品经理的升学与求职记",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "CS背景转产品经理方向，分享港新CS硕士申请和互联网产品岗实习求职经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于CS转产品经理、港新硕士申请或互联网产品岗求职有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"CS专业想转产品经理怎么规划？",
			"港新CS硕士项目怎么选？",
			"互联网产品岗实习怎么找？",
		},
		ExpertiseTags: []string{"产品经理", "港新留学", "HKU", "飞跃手册", "求职"},
		KnowledgeBody: `21级计算机系，GPA 3.70/4(排名79/195)，IELTS 6.5(口语5.5)。有NUS Summer Workshop(UX Design方向A+)、UC Berkeley学期交流、一个CCF-B会议workshop poster。多段产品实习（腾讯CSIG/WXG等）。最终去向HKU IDT硕士。获CUHK CS(10月offer)、HKUST TLE、NTU SPML/MSIS、HKUST IT等6个offer。选择产品经理原因：比起钻研技术更喜欢用户体验和功能设计，大E性格适合沟通协调。CUHK CS是港新top项目且出结果很早。建议早申港新（NUS EDI养鱼半年才拒）。CS背景+设计思维是PM求职的独特优势。`,
	},
	{
		DisplayName:       "PPT选手zx",
		School:            "南方科技大学",
		MajorLine:         "CS MS（美国方向）",
		ScoreLine:         "16级计算机系",
		ArticleTitle:      "南科大飞跃手册 | 16级CS申请美国硕士PPT总结",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "以PPT形式总结CS美国硕士申请经验，图文并茂展示完整流程。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于CS美国硕士申请流程有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"CS美国硕士申请的基本流程？",
			"如何制作申请材料？",
			"选校需要考虑哪些因素？",
		},
		ExpertiseTags: []string{"美国留学", "CS硕士", "申请流程", "飞跃手册", "选校"},
		KnowledgeBody: `16级计算机系同学，以PPT/图片形式分享了CS美国硕士申请的完整流程和经验总结。内容涵盖选校策略、标化考试准备、文书写作、推荐信安排、申请时间线等核心环节。图文并茂的形式便于快速了解申请全貌。建议结合其他同届同学的文字版经验一起参考，从不同角度了解申请过程中的注意事项。`,
	},
	{
		DisplayName:       "Utah全奖zy",
		School:            "南方科技大学",
		MajorLine:         "CS PhD @ U of Utah (AI Safety)",
		ScoreLine:         "GPA 3.94/4 (Rank 2/195), TOEFL 109, No GRE",
		ArticleTitle:      "南科大飞跃手册 | 绩点第二申请AI Safety方向PhD的经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "系排名第二，只申五所学校的冒险策略，分享套磁和面试的实战心得。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于AI Safety方向PhD申请、套磁策略或少量精申策略有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"只申5所学校的PhD策略风险大吗？",
			"AI Safety方向PhD申请难度如何？",
			"套磁无回复该怎么判断和应对？",
		},
		ExpertiseTags: []string{"PhD申请", "AI Safety", "Utah", "飞跃手册", "套磁"},
		KnowledgeBody: `21级计算机系，GPA 3.94/4排名2/195，TOEFL 109，无GRE。大二起在校内做软工方向(LLM+Testing)科研，大三暑假在HKUST(GZ)做RA(Trustworthy AI/AI Safety方向)。申请时无pub，有一篇SE非research track一作在投。25Fall只申请5所美国CS PhD（非常冒险），最终拿到Utah和UGeorgia offer，另有HKUST、UIC、Concordia口头offer后拒绝。套磁建议：10-11月开始，通过套磁回复率判断申请梯度。无回复可能是不招人/太忙/pool太大；约面试说明professor感兴趣。Utah导师面试后非常明确表示positive，第二天早上就收到正式offer。建议海套不要因BG不强就不套。`,
	},
	{
		DisplayName:       "系统菜狗sc",
		School:            "南方科技大学",
		MajorLine:         "CS PhD @ U of Utah (System)",
		ScoreLine:         "GPA 3.78/4 (Rank 44/195), TOEFL 105, No GRE",
		ArticleTitle:      "南科大飞跃手册 | 菜狗的System方向PhD申请故事",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "自称菜狗但收获Utah全奖PhD with fellowship，分享申请中的逆天小故事。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！如果你觉得自己背景一般但想试试PhD，关于System方向申请和offer比较有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"背景一般能拿到PhD全奖吗？",
			"System方向PhD申请有什么特点？",
			"多个PhD offer怎么比较和选择？",
		},
		ExpertiseTags: []string{"PhD申请", "System", "Utah", "飞跃手册", "offer比较"},
		KnowledgeBody: `21级计算机系，GPA 3.78/4(排名44/195)，TOEFL 105，无GRE。在UChicago做了半年访问学生，申请时有一篇一作论文在投。最终录取Utah CS PhD全奖with fellowship，另获UC Merced offer。被UChicago(缩招)、CMU、UIUC、UWM拒，多所学校无回复。UMass面试后说感觉不错但一直没正式offer。Utah强committee制未套磁，12月导师主动邮件约面试，聊完第二天早上就收到offer。自称很菜但身边师长支持让申请有了不错结果。分享UC Merced申请中的逆天故事。建议参考博士申请指导GitHub仓库。Good luck to everyone!`,
	},
}
