package yantuseed

var sustechFeyueBIZProfiles = []Profile{
	{
		DisplayName:       "传媒少女cd",
		School:            "南方科技大学",
		MajorLine:         "财经传媒硕士 @ 中山大学（保研）",
		ScoreLine:         "GPA 3.65/4, Ranking 10/68, IELTS 6.5",
		ArticleTitle:      "南科大飞跃手册 | 金融系跨保财经传媒的血泪经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "从金融跨专业保研财经传媒，分享跨保准备、夏令营面试和选校策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在考虑跨专业保研、金融方向选择或夏令营准备，欢迎提问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"跨专业保研需要怎么准备？",
			"金融系保研夏令营面试考什么？",
			"怎么选择保研的Target School？",
		},
		ExpertiseTags: []string{"跨专业保研", "财经传媒", "夏令营", "飞跃手册", "金融"},
		KnowledgeBody: `15级金融系，GPA 3.65/4排名10/68，IELTS 6.5。最终跨专业保研中山大学财经传媒硕士，另获哈工大(深圳)财经传媒和南科大金融学AD。有金融风控、财经媒体远程和地产战略规划部实习经历。跨保核心问题是想清楚为什么要跨——需要有背景加触发点，面试反复会问。建议保研选校分好/较好/一般三档5-6所院校，确认夏令营时间是否冲突和录取比。金融保研最核心是GPA（60%成绩+40%奖项综合排名），实习含金量决定offer含金量。自荐信和简历是面试官了解你的唯一渠道，一定要对上面每一点都熟悉到能预判问题。`,
	},
	{
		DisplayName:       "法学冒险家gy",
		School:            "南方科技大学",
		MajorLine:         "法学硕士(JD/JM) @ 北京大学国际法学院",
		ScoreLine:         "金融工程, Ranking 3/58, GPA 3.85/4",
		ArticleTitle:      "南科大飞跃手册 | 金工转法学保研北大国法的探索之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "金融工程排名第三，多次海外交流后决定跨保北大国际法学院，分享跨界保研心得。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于金融转法学、跨专业保研北大或海外交流的问题欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"金融专业可以跨保法学吗？",
			"北大国际法学院夏令营怎么准备？",
			"海外交流对保研有帮助吗？",
		},
		ExpertiseTags: []string{"跨专业保研", "北大国法", "海外交流", "飞跃手册", "法学"},
		KnowledgeBody: `16级金融工程专业，排名3/58，GPA 3.85/4。曾赴加拿大UBC、牛津和加州伯克利交流。在伯克利选修知识产权和创业法律课程后，对商法交叉方向产生兴趣，最终保研北大国际法学院(STL)。STL是全球唯一将美国JD和中国JM模式结合的法学院，夏令营核心活动是模拟法庭比赛。申请材料需中英双语，PS要充分说明为何选择该项目。建议纯商科如无法留海外工作，出国读master性价比不高；想保研名校金融，成绩排名最重要；STL注重个人经历，排名非前二也有机会。`,
	},
	{
		DisplayName:       "金融卷王xy",
		School:            "南方科技大学",
		MajorLine:         "金融学保研 @ 北京大学汇丰商学院",
		ScoreLine:         "GPA 3.8/4, 专排 5/83, 国家奖学金",
		ArticleTitle:      "南科大飞跃手册 | 从金融系到北大汇丰的保研攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "非第一名也成功保研北大汇丰，分享GPA策略、课外活动和保研全流程。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于金融保研、GPA提升策略或北大汇丰申请有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"不是专业第一能保研北大吗？",
			"金融保研怎么平衡学业和课外活动？",
			"ACCA对保研有帮助吗？",
		},
		ExpertiseTags: []string{"保研", "北大汇丰", "金融学", "飞跃手册", "课外活动"},
		KnowledgeBody: `17级金融学专业，GPA 3.8/4排名5/83，国家奖学金，ACCA过9/13门，多段证券及咨询实习。成功保研北京大学汇丰商学院，成为专业唯二去清北的学生之一。大一GPA不高后面拼命追赶。保研中成绩占80%重要性，是各校卡人的硬性指标。建议给每学期设定GPA目标，细化到每门课需要的分数。实习建议大二暑假开始，有big name加分。重要性排序：成绩>>英语=科研=实习>竞赛=海外交流>证书=学生工作。很多名校商科夏令营初筛只给南科大一个名额，往往是成绩第一名。`,
	},
	{
		DisplayName:       "金科状元hy",
		School:            "南方科技大学",
		MajorLine:         "金融科技方向保研（具体项目保密）",
		ScoreLine:         "成绩 1/58, 四级616, 六级507, 托福96",
		ArticleTitle:      "南科大飞跃手册 | 金融科技专业第一的保研准备之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "金融工程(金融科技)专业第一，分享成绩、实习、科研三维准备和保研项目选择。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于金融科技方向保研、成绩提升或实习规划有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"金融工程保研需要什么成绩？",
			"金融保研中实习和科研哪个更重要？",
			"怎么选择保研的项目？",
		},
		ExpertiseTags: []string{"保研", "金融科技", "成绩规划", "飞跃手册", "实习"},
		KnowledgeBody: `16级金融工程(金融科技)专业，成绩排名1/58，四级616，六级507，托福96。有券商实习经历，一篇论文(未发表)和课题组经历。保研金融建议总成绩保持专业前三，保证出勤认真听讲做作业考前复习，大部分课分数不低于90。六级建议刷到550+，托福100+/雅思7+满足所有要求。实习建议大二寒假开始，两三段为宜，好的机构big name帮你背书。科研对学硕项目有论文要求的很重要，建议大二开始。金融+编程的复合背景在就业中很受欢迎。`,
	},
	{
		DisplayName:       "港大统计侠dy",
		School:            "南方科技大学",
		MajorLine:         "Statistics PhD @ HKU (全奖)",
		ScoreLine:         "GPA 3.70/4, Ranking 21/49, IELTS 7.0",
		ArticleTitle:      "南科大飞跃手册 | 统计系GPA中等偏上的PhD申请之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA中等但通过正确方向选择和科研积累拿到港大统计PhD全奖，分享详细四年经历。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于统计方向PhD申请、香港学校RA经历或选专业有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GPA中等能申到统计PhD全奖吗？",
			"香港RA经历对PhD申请有多大帮助？",
			"统计学和生物统计有什么区别？",
		},
		ExpertiseTags: []string{"PhD申请", "统计学", "港大", "飞跃手册", "科研"},
		KnowledgeBody: `16级统计系，GPA 3.70/4排名21/49，IELTS 7.0(口语5.5)。大四上在CUHK统计系做半年RA，另有远程暑期研究和校内讨论班经历。最终获HKU统计PhD全奖和KAUST统计PhD全奖，另获KTH和UCPH硕士录取。作者认为GPA属于"上不着天下不着地"，但选取正确方向加上足够努力最终达到较高高度。香港PhD申请中RA经历很有价值，但建议提前联系好导师方向要match。学生工作最大意义在于结交朋友和锻炼能力，不要偏离这个意义增加学业负担。`,
	},
	{
		DisplayName:       "欧陆探索者mz",
		School:            "南方科技大学",
		MajorLine:         "金融硕士(MSF) @ 博科尼大学(半奖)",
		ScoreLine:         "16级金融工程, GMAT 700+",
		ArticleTitle:      "南科大飞跃手册 | 意法英三地金融硕士申请经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "英国申请惨淡后转向欧陆拿到博科尼半奖，分享多地金融硕士申请策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！如果你对欧陆金融硕士、博科尼、法国高商或多地混申有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"博科尼大学金融硕士怎么样？",
			"法国高商GE项目值得申吗？",
			"英国和欧陆金融硕士怎么选？",
		},
		ExpertiseTags: []string{"欧陆留学", "博科尼", "法国高商", "飞跃手册", "金融硕士"},
		KnowledgeBody: `16级金融工程专业。最终去向意大利博科尼大学金融硕士(半奖)。英国申了7所中介选校结果惨淡，自己补申3所CV重做后均获offer。博科尼申请页面人性化，GMAT最好700+，GPA建议85+，文书很重要可争取奖学金。一次可申5个专业，MSF是王牌，硕士两年制含强制实习，需学意大利语。法国高商GE项目三年制含gap年实习，面试占比大，TOP3值得上。英国GPA是硬道理，建议早申。欧陆学校是留学洼地学费低有奖学金。建议多撒网不要给自己设限，中介坑多能自己来就自己来。`,
	},
	{
		DisplayName:       "哥大风控达人hm",
		School:            "南方科技大学",
		MajorLine:         "企业风险管理硕士(ERM) @ Columbia",
		ScoreLine:         "GPA 3.62/4, IELTS 7.5, GMAT 690",
		ArticleTitle:      "南科大飞跃手册 | 金融系申请美国金融硕士的选校与文书策略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GMAT未达700但拿到Columbia等7个offer，分享美国金融硕士选校和文书定制策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于美国金融硕士申请、选校策略或文书定制有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GMAT不到700能申到好学校吗？",
			"美国金融硕士如何选校？",
			"文书怎么体现和项目的匹配度？",
		},
		ExpertiseTags: []string{"美国留学", "Columbia", "金融硕士", "飞跃手册", "文书"},
		KnowledgeBody: `19级金融学专业，GPA 3.62/4，IELTS 7.5，GMAT 690。获Columbia ERM、WUSTL金融、UIUC MSF、UR MSF、BC MSF、WFU MSBA、HKU MFin共7个offer。雅思比托福对口语写作较弱的学生更友好。中介可做dirty work但文书必须全程参与。选校除看排名还需关注class profile和国际学生比例。美国综合评估各维度，一项缺陷可用另一项补救。文书按项目课程和特点定制，最合适的才是最好的。部分项目early提交或参加info session可免申请费。WES认证绩点需尽早准备。`,
	},
	{
		DisplayName:       "港新混申达人bw",
		School:            "南方科技大学",
		MajorLine:         "金融学硕士(MS in Finance) @ 香港中文大学",
		ScoreLine:         "GPA 3.6+, 专排30%, IELTS 7.5, GMAT 710",
		ArticleTitle:      "南科大飞跃手册 | 港新商科金融硕士申请全指南",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "南科大商科信息有限的背景下拿到港新多校offer，分享港新商科申请完整策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于港新金融硕士申请、留学地区选择或商科就业有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"港新金融硕士怎么选校？",
			"国内读研和港新留学哪个性价比高？",
			"GMAT和雅思分别需要考多少？",
		},
		ExpertiseTags: []string{"港新留学", "CUHK", "金融硕士", "飞跃手册", "选校"},
		KnowledgeBody: `18级金融学专业，GPA 3.6+专排30%，雅思7.5，GMAT 710。有咨询、券商行研、互联网战略实习。最终去向CUHK MS in Finance，另获HKU、HKUST、NUS多个AD。港新费用友好(25-40万港币学费)，内地认知度高。南科大申港新商科有一定优势。金融系保研结果近年不错，有很多保去985和两财一贸的同学。国内金融专硕性价比高可攒实习，但想出去看看只有留学可选。申请策略是Round1优先，多地金融混申或加申商业分析增加录取概率。`,
	},
	{
		DisplayName:       "NUS金工先锋fe",
		School:            "南方科技大学",
		MajorLine:         "金融工程硕士(MFE) @ NUS",
		ScoreLine:         "GPA 3.88, TOEFL 105, GMAT 720",
		ArticleTitle:      "南科大飞跃手册 | NUS金融工程提前批录取经验分享",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "目标明确、一步一脚印拿到NUS金融工程提前批录取，分享规划和语言准备策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于NUS金融工程申请、提前批策略或大学整体规划有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"NUS金融工程提前批怎么申请？",
			"语言考试应该什么时候准备？",
			"大学四年怎么做整体规划？",
		},
		ExpertiseTags: []string{"新加坡留学", "NUS", "金融工程", "飞跃手册", "规划"},
		KnowledgeBody: `16级金融工程专业，GPA 3.88，TOEFL 105(30+27+24+24)，GMAT 720(50+37)。9月即收到NUS金融工程提前批录取，比保研还早。提前批对GPA(3.7+)和TOEFL(100+)有严格要求。英语成绩是卡住大多数人的阿喀琉斯之踵，建议大一考四级、大二考六级、大二暑假考TOEFL、大三寒假考GMAT。所有考试尽量一次过，预留刷分时间。大学规划最关键是尽早设定阶段性目标，建议大三上确定具体方向。保研和出国可两线程同步推进，两者相似度很高。`,
	},
	{
		DisplayName:       "CMU数据分析师zc",
		School:            "南方科技大学",
		MajorLine:         "信息管理硕士(MISM-BIDA) @ CMU",
		ScoreLine:         "GPA 3.77/4 (专排11/57), TOEFL 108, GRE 327",
		ArticleTitle:      "南科大飞跃手册 | 金融工程转商业分析申请CMU BIDA",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "金融工程背景混申商业分析拿到CMU BIDA，分享项目对比和课程选择建议。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于CMU BIDA/MISM项目、商业分析申请或金融转数据方向有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"CMU MISM和BIDA有什么区别？",
			"金融工程可以申商业分析吗？",
			"GaTech MSA项目怎么样？",
		},
		ExpertiseTags: []string{"美国留学", "CMU", "商业分析", "飞跃手册", "BIDA"},
		KnowledgeBody: `18级金融工程专业，GPA 3.77百分制90.24专排11/57，TOEFL 108，GRE 327。最终录取CMU MISM-BIDA(商业情报与数据分析方向)。CMU有三个商业分析相关项目：Tepper MSBA(9个月无实习)、Heinz MISM(20年历史)、MISM-BIDA(每年录取约60人中国人约10人)。申请BIDA未录取会调剂到MISM，无反向调剂。BIDA毕业3个月就业率约90%，平均薪资超11万美元，留美率95%+。金融工程和商业分析混申可行，注意课程匹配度，面向对象编程经验和数据库基础是申请要求。`,
	},
	{
		DisplayName:       "PPT金工达人yl",
		School:            "南方科技大学",
		MajorLine:         "金融工程硕士申请经验（图解版）",
		ScoreLine:         "16级金融工程",
		ArticleTitle:      "南科大飞跃手册 | 金融工程境外升学PPT总结",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "以PPT图解形式分享金融工程境外升学申请流程和关键节点。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于金融工程境外升学流程有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"金融工程境外升学流程是什么样的？",
			"申请金融硕士需要准备什么材料？",
			"金融工程申请有什么注意事项？",
		},
		ExpertiseTags: []string{"金融工程", "境外升学", "申请流程", "飞跃手册", "选校"},
		KnowledgeBody: `16级金融工程专业同学，以PPT图片形式总结了金融工程方向境外升学的完整流程和要点。内容涵盖选校定位、标化考试准备(TOEFL/GMAT/GRE)、文书撰写、推荐信安排、申请时间线等核心环节。图文并茂的形式便于快速了解金融工程申请全貌，包括如何选择金融工程、金融数学和量化金融等细分方向。建议结合其他金工方向同学的文字版经验一起参考，从不同角度了解申请中的注意事项。`,
	},
	{
		DisplayName:       "考研数分选手my",
		School:            "南方科技大学",
		MajorLine:         "数学(统计)硕士 考研 @ 南方科技大学",
		ScoreLine:         "初试299分, 英语73",
		ArticleTitle:      "南科大飞跃手册 | 统计方向考研南科大的复习攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "分享考研南科大统计方向的复习策略，涵盖政治、英语和专业课各科经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在考虑考研或准备数分线代专业课，欢迎提问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"考研统计方向怎么复习专业课？",
			"考研复习时间怎么安排？",
			"数学分析考试和教材差异大吗？",
		},
		ExpertiseTags: []string{"考研", "统计", "数学分析", "飞跃手册", "复习策略"},
		KnowledgeBody: `15级数学(统计)专业，考研录取南科大统计硕士，初试299分（英语73、政治61、线代99、数分较弱）。核心建议：一定要列可行复习计划并严格执行，建议留8个月复习时间。政治用肖秀荣系列不在多在于利用透。英语一要每天做真题不能断，每周至少2次写作训练。数分考题和教材课后题风格差异较大，侧重对基本概念的准确理解，经典反例和特殊函数要灵活运用。线代重点是矩阵变换性质和特殊矩阵结论的证明及延伸。专业课需大量习题练习，用专门复习资料而非数学一二三。`,
	},
	{
		DisplayName:       "精算小达人ty",
		School:            "南方科技大学",
		MajorLine:         "统计方向保研 @ 北京大学汇丰商学院",
		ScoreLine:         "GPA 3.84, SOA四门, 港科大学期交流",
		ArticleTitle:      "南科大飞跃手册 | 统计系保研北大汇丰的坚持之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "统计系保研北大汇丰，持有SOA精算证书，分享实习夏令营和坚持的重要性。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于统计方向保研、精算证书或北大汇丰夏令营有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"统计系保研北大汇丰需要什么条件？",
			"SOA精算考试对保研有帮助吗？",
			"保研夏令营怎么准备？",
		},
		ExpertiseTags: []string{"保研", "北大汇丰", "统计学", "飞跃手册", "精算"},
		KnowledgeBody: `16级统计与数据科学系，GPA 3.84，持有SOA精算考试P/FM/IFM/SRM四门证书。有再保险和券商研究所实习，港科大学期交流和伯明翰暑期交流经历。最终保研北京大学汇丰商学院，另获港中深数据科学硕士和多个实习offer。从认识自己开始选择方向，大二确定统计专业。坚持是最重要的品质，把握能把握的机会，用心完成的东西最终会积淀为人生财富。暑期实习建议投不少于30家，保研夏令营尽可能多申。夏令营是考核也是享受，享受过程拿offer概率就很大。`,
	},
	{
		DisplayName:       "量化瑞士通dy",
		School:            "南方科技大学",
		MajorLine:         "金融工程硕士(MFE) @ EPFL",
		ScoreLine:         "GPA 3.84 (3/57), TOEFL 105, GRE 325",
		ArticleTitle:      "南科大飞跃手册 | DIY申请量化金融硕士全攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "全程DIY申请拿到EPFL等6个AD，分享美国量化金融硕士选校和GPA策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于量化金融硕士DIY申请、EPFL体验或选校策略有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"金融工程硕士怎么DIY申请？",
			"EPFL MFE项目怎么样？",
			"金工申请GPA有多重要？",
		},
		ExpertiseTags: []string{"金融工程", "EPFL", "DIY申请", "飞跃手册", "量化金融"},
		KnowledgeBody: `16级金融工程专业，GPA 3.84排名3/57，TOEFL 105(口语23)，GRE 155V+170Q。有私募量化研究、银行信贷和集团风控部实习。全程DIY申请。最终去向EPFL金融工程硕士，另获NYU(15k奖学金)、NYU Tandon、USC、UW Seattle、UMich AD，被MIT、CMU、Cornell拒。GPA是致命因素，某些项目中GPA劣势靠实习和GT都无法弥补。GPA走高趋势更亮眼，数学/计算机/金融三类课分数差异不要太大。金工申请需微积分、线代、概统必修，随机过程等多多益善。编程至少掌握一门语言。`,
	},
	{
		DisplayName:       "生统跨洋人ld",
		School:            "南方科技大学",
		MajorLine:         "Biostat PhD @ Penn State (先读海硕)",
		ScoreLine:         "南科大GPA 3.64(7/30), 海硕GPA 3.95",
		ArticleTitle:      "南科大飞跃手册 | 先读海硕再申PhD的生物统计进阶之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "本科GPA中等先读美国硕士再申PhD，分享海硕转博的路径和生物统计申请。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于海硕转博、生物统计PhD申请或统计方向规划有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"本科成绩一般可以先读硕再申PhD吗？",
			"生物统计PhD就业前景怎么样？",
			"美国统计和生物统计有什么区别？",
		},
		ExpertiseTags: []string{"PhD申请", "生物统计", "海硕转博", "飞跃手册", "Penn State"},
		KnowledgeBody: `14级数学系，南科大GPA 3.64(7/30)，先到美国读Biostat硕士(GPA 3.95)再申PhD。最终获Penn State、Ohio State、U of Toronto等6个Biostat PhD全奖offer。Biostat偏好收硕士生，PhD就业前景比硕士好很多，在美国算就业友好专业。建议本科成绩中等但想做科研的同学考虑海硕转博路线。硕士期间要保持高GPA并完成完整科研项目。Stat PhD要求高偏好TOP校TOP学生，Biostat竞争同样激烈因为面对统计和生物专业的混申者。暑假去排名第一的学校上暑课也是提升背景的好方法。`,
	},
	{
		DisplayName:       "港中深会计yr",
		School:            "南方科技大学",
		MajorLine:         "会计学硕士(MA) @ 香港中文大学(深圳)",
		ScoreLine:         "GPA 3.59/4, Ranking 15+/60+, TOEFL 90",
		ArticleTitle:      "南科大飞跃手册 | 港中深会计硕士夏令营申请指南",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA不算高但成功申请港中深会计硕士，分享夏令营面试和专业选择策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于港中深硕士申请、金融相关专业选择或夏令营面试有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"港中深会计硕士好申请吗？",
			"港中深金融相关四个专业怎么选？",
			"GPA不高怎么提高竞争力？",
		},
		ExpertiseTags: []string{"港中深", "会计硕士", "夏令营", "飞跃手册", "面试"},
		KnowledgeBody: `15级金融系，GPA 3.59/4排名15+/60+，TOEFL 90。最终录取港中深会计学硕士。港中深金融相关有经济、金融、金工、会计四个专业，会计最好申只有单面无笔试，可作为保底。其他三个有笔试和群面，可同时申多个专业。夏令营7月从4-5月开始申请分批录取，第一批概率最大建议9-10月开始。GPA是硬指标筛选主要因素，不要在课多学期去实习导致GPA下降。笔试含数学和金融经济理论难度不大。会计单面全英文，限时阅读材料后开放式分析回答。`,
	},
	{
		DisplayName:       "清华经管冲刺jp",
		School:            "南方科技大学",
		MajorLine:         "金融硕士保研 @ 清华大学经管学院",
		ScoreLine:         "GPA 3.88/4 (2/56), 托福83",
		ArticleTitle:      "南科大飞跃手册 | 保研清华经管金融硕士的全方位准备",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "专排第二靠科研论文冲击清华经管，分享金融保研中绩点、科研和实习的平衡策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于清华经管保研、金融科研规划或夏令营笔面试准备有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"保研清华经管需要什么条件？",
			"金融保研中科研论文有多重要？",
			"保研各项指标的重要性排序是什么？",
		},
		ExpertiseTags: []string{"保研", "清华经管", "金融硕士", "飞跃手册", "科研"},
		KnowledgeBody: `18级金融系金融工程专业，GPA 3.88/4排名2/56。有投行实习、数模国赛省二、美赛H奖和校学生会执行主席经历。保研清华大学经管学院金融硕士。经管保研关注度排序：绩点>(科研)>实习>比赛>英语>社会工作。论文逐渐成为好项目的首选加分项，但投入时间足够做一段好实习或复习所有专业课，需权衡。科研是相对蓝海的路上限较高，冲击清北建议带科研。笔试考高数线代概统和金融专业课，面试更关键会深挖论文和专业知识。保研分夏令营和九推两个时期，准备完成后果断申请。`,
	},
	{
		DisplayName:       "汇丰游泳健将yq",
		School:            "南方科技大学",
		MajorLine:         "金融保研 @ 北京大学汇丰商学院",
		ScoreLine:         "GPA 3.84/4 (1/49), 托福100+",
		ArticleTitle:      "南科大飞跃手册 | 金融系专排第一保研北大汇丰全流程",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "专排第一从大一认真每节课，分享保研时间线和多个夏令营面试经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于北大汇丰保研、夏令营面试经历或保研时间规划有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"北大汇丰金融夏令营怎么准备？",
			"金融保研的时间线是怎样的？",
			"考证对保研有帮助吗？",
		},
		ExpertiseTags: []string{"保研", "北大汇丰", "金融", "飞跃手册", "夏令营"},
		KnowledgeBody: `18级金融系，GPA 3.84/4排名1/49，托福100+。有投行、行研和交易所多段实习，攀登计划和大创各一项。保研北京大学汇丰商学院。参加过深高金、上财、北大国法和北大汇丰等多个夏令营。个人排序：专业排名>科研>英语/比赛>实习>课外活动。学术成果在夏令营中重要性越来越大。建议3月完成简历、4月完成PS、5月初完成论文。汇丰面试可能全英文，勇于表达不要怕语法错误。面试中引导老师在自己亮点方面提问，不确定的不要写在简历里避免挖坑。`,
	},
	{
		DisplayName:       "哥大交流攻略zh",
		School:            "南方科技大学",
		MajorLine:         "哥伦比亚大学学期交流",
		ScoreLine:         "16级统计系, TOEFL 100+",
		ArticleTitle:      "南科大飞跃手册 | 哥伦比亚大学学期交流申请全攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "自主申请拿到哥大、宾大和天普大学交流邀请，分享完整的申请和奖学金攻略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "嗨！关于美国学期交流申请、奖学金策略或哥大生活有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"怎么申请哥大学期交流项目？",
			"学期交流有哪些奖学金可以申？",
			"哥大CC和SPS选课有什么区别？",
		},
		ExpertiseTags: []string{"学期交流", "哥大", "奖学金", "飞跃手册", "美国"},
		KnowledgeBody: `16级统计系，自主申请获得哥伦比亚大学、宾夕法尼亚大学和天普大学学期交流邀请。哥大交流分学分项目(TOEFL100+)、语言项目和商科证书课程三类，一学期费用约25-30万。CC和SPS主要区别：CC是本科生院选研究生课需审批，SPS是研究生院选课优先级更高。建议提前在Vergil系统查课程对哪个学院开放。南科大提供卓越计划奖学金(GPA3.5+最高20万)和留基委优秀本科生资助(1600美元/月)。Short Questions相当于PS功能，一定要认真准备找native speaker修改。`,
	},
	{
		DisplayName:       "芝大风险管理ys",
		School:            "南方科技大学",
		MajorLine:         "MACRM @ UChicago (Harris)",
		ScoreLine:         "GPA 3.79/4, TOEFL 108",
		ArticleTitle:      "南科大飞跃手册 | 金融工程到芝加哥大学政策分析硕士的跨界申请",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "金融工程背景拿到芝大、WUSTL、Duke等多校录取，分享丰富交流经历的跨界申请之路。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于美国金融/经济硕士申请、芝大项目或跨领域申请有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"芝加哥大学MACRM项目怎么样？",
			"金融工程可以申经济/政策方向吗？",
			"海外交流经历对申请有多大帮助？",
		},
		ExpertiseTags: []string{"美国留学", "UChicago", "金融", "飞跃手册", "跨界"},
		KnowledgeBody: `18级金融工程专业，GPA 3.79/4，TOEFL 108(口语25)，三年一等奖学金。有联合国气候大会、牛津暑期课程、芝大暑期研究和多伦多大学学期交换等国际交流经历。有管理咨询实习，一篇基于暑研课题的一作文章(已发表)。最终去向芝加哥大学Harris学院MACRM项目，另获WUSTL金融、HKU经济(40%奖学金)、JHU和Duke经济AD。申请关键是展现跨界视野和研究能力，暑期研究论文是重要的Writing Sample。交流经历让形象更丰满，跨领域尝试试错成本不高。`,
	},
	{
		DisplayName:       "ML理论探索者ya",
		School:            "南方科技大学",
		MajorLine:         "CSE PhD @ Rensselaer Polytechnic Institute",
		ScoreLine:         "GPA 3.42/4 (18/25), TOEFL 98, 无GRE",
		ArticleTitle:      "南科大飞跃手册 | 平庸背景的泛计算机博士申请故事",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA 3.42排名中下但靠方向匹配和坚持拿到PhD offer，分享ML Theory方向申请。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你GPA不高但想申PhD，或对ML Theory方向感兴趣，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GPA低于3.5能申到PhD吗？",
			"ML Theory方向PhD怎么准备？",
			"如何判断一个学校的PhD值不值得申？",
		},
		ExpertiseTags: []string{"PhD申请", "机器学习", "RPI", "飞跃手册", "低GPA"},
		KnowledgeBody: `20级统计与数据科学系，数据科学专业，GPA 3.42/4排名18/25(大一GPA仅2.54)，TOEFL 98(口语19)，无GRE。申请方向ML Theory/Deep Learning Theory。最终去向RPI计算机与系统工程PhD。面试了多所学校，申请过程波折——有与方向非常match的老师暗示会录取但最终未录。重要性排序：推荐信>高质量研究经历>本科背景>GPA/课程>SOP/托福口语>托福/GRE>奖项。择校建议找目标学校中国博士生看履历，如果水平与南科大相当则可考虑。美国前70的学校都值得考虑。`,
	},
	{
		DisplayName:       "清华出国两手yc",
		School:            "南方科技大学",
		MajorLine:         "金融硕士保研 @ 清华大学经管学院",
		ScoreLine:         "GPA 3.86 (1/63), 国家奖学金",
		ArticleTitle:      "南科大飞跃手册 | 出国党的保研清华攻略与交流经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "保研+出国两手准备最终清华经管上岸，分享双线规划和海外交流申请经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于保研出国两手准备、海外交流项目选择或清华经管有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"保研和出国可以同时准备吗？",
			"伯克利和哥大交流怎么选？",
			"清华经管金融硕士夏令营怎么准备？",
		},
		ExpertiseTags: []string{"保研", "清华经管", "海外交流", "飞跃手册", "双线准备"},
		KnowledgeBody: `16级金融专业，GPA 3.86排名1/63，国家奖学金，英语竞赛特等奖。有牛津暑期交流和伯克利BGA学期交流。最终夏令营录取清华大学经管学院金融硕士。保研+出国两手准备：GPA对两者都重要，英语成绩保研锦上添花出国必须。夏令营3-7月出国首批申请10月，时间错开可作PlanB。实习建议大二开始Networking，2-3份最佳不要耽误学业。交流项目锦上添花不是决定因素但能开拓眼界。选择伯克利vs哥大可从推荐信需求、费用、城市偏好和学分转换四方面考量。`,
	},
	{
		DisplayName:       "HEC自由灵魂yy",
		School:            "南方科技大学",
		MajorLine:         "管理硕士(MiM) @ HEC Paris",
		ScoreLine:         "GPA 3.5/4, 金融工程, 排名约30%",
		ArticleTitle:      "南科大飞跃手册 | GPA不高但成功申请HEC管理硕士的故事",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA一般但个人特色鲜明，通过合作项目面试拿到HEC offer，分享非传统申请路径。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！关于HEC Paris申请、低GPA如何扬长避短或管理方向选择有什么问题都可以问。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GPA不高能申到顶级商学院吗？",
			"HEC Paris MiM项目怎么样？",
			"学校合作项目怎么申请？",
		},
		ExpertiseTags: []string{"HEC Paris", "管理硕士", "法国留学", "飞跃手册", "合作项目"},
		KnowledgeBody: `17级金融工程专业，GPA 3.5/4排名约30%，托福和GRE均有成绩。有NUS计算机学院暑期交流和多段行业实习。最终通过学校合作项目面试获HEC Paris MiM(管理硕士)录取，HEC是management大类世界第一。大物低分对GPA打击巨大。建议对力所不能及的课程考虑退课而非硬撑，选课前了解给分情况。国外学校注重软实力，面试轮是展示个人特色的机会。金融转管理/咨询方向可行，试错成本不高不要畏惧尝试。重大选择当断则断，尽早获得家里认可和支持。`,
	},
}
