package yantuseed

var sustechFeyueENGProfiles = []Profile{
	{
		DisplayName:       "环保清研er",
		School:            "南方科技大学",
		MajorLine:         "环境工程 保研 @ 清华大学深圳研究生院",
		ScoreLine:         "GPA 3.72, Rank 2/33, 雅思6.5",
		ArticleTitle:      "南科大飞跃手册 | 环境系保研清华深研院的完整流程分享",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "环境系排名第二保研清华深研院，分享夏令营报名、面试和九推全流程经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你正在考虑国内保研，对夏令营流程或清华深研院有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"保研夏令营需要准备哪些材料？",
			"清华深研院环境工程怎么样？",
			"保研中最看重什么条件？",
		},
		ExpertiseTags: []string{"保研", "清华深研院", "环境工程", "飞跃手册", "夏令营"},
		KnowledgeBody: `16级环境系，GPA 3.72排名2/33，CET4 492，CET6 491，雅思6.5。最终保研清华深研院环境工程专硕。选择保研原因：对科研有兴趣但不确定是否适合读博，先读硕士过渡；经济条件不允许出国。夏令营报名4-6月，各院系官网发通知。材料：成绩单+排名、英语成绩、推荐信1-3封、获奖证书、论文。夏令营7-8月，含开营介绍、参观实验室、导师交流和面试。建议即使校方未安排导师交流也要主动创造条件。面试常见问题：自我介绍、报考原因、未来计划、专业基础知识，都可能用英文提问。九推在8月通知，面试更偏学术。保研最看重学业成绩，其次英语，科研经历是加分项。`,
	},
	{
		DisplayName:       "模拟芯人rw",
		School:            "南方科技大学",
		MajorLine:         "微电子 直博 @ 清华大学集成电路学院",
		ScoreLine:         "GPA 3.85, Rank 3/80, IELTS 7.0",
		ArticleTitle:      "南科大飞跃手册 | 微电子模拟IC方向保研清华直博经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "微电子专业排名前三，提前联系导师成功入营清华直博，分享IC设计保研选校和面试。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对IC设计方向保研、直博选择或清华面试有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"模拟IC方向保研怎么选校？",
			"保研直博和学硕哪个更难申请？",
			"清华集成电路夏令营面试考什么？",
		},
		ExpertiseTags: []string{"保研", "清华", "集成电路", "飞跃手册", "模拟IC"},
		KnowledgeBody: `19级微电子专业，GPA 3.85排名3/80，IELTS 7.0。走模拟IC设计电源管理方向。最终保研清华集成电路学院直博。保研难度排序：学硕>专硕或直博。IC设计领域国内优秀院校主观排名：T0清华澳大，T1复旦港科浙大东南中科大电科北大上交。提前联系导师非常关键，尤其直博——第一位联系的导师直接拒绝，换了一位聊得投机后被捞入营。清华面试20分钟：英文翻译3分钟+自我介绍5分钟+项目提问+专业知识。问题涉及振荡器指标、LDO结构原理、版图设计注意事项等。建议尽早联系导师表达直博意愿，科研竞赛经历可丰富简历。`,
	},
	{
		DisplayName:       "脑机接口wy",
		School:            "南方科技大学",
		MajorLine:         "EE PhD @ Columbia University",
		ScoreLine:         "GPA 3.9/4, Rank 5/44, TOEFL 108",
		ArticleTitle:      "南科大飞跃手册 | Connection is All You Need——美国EE PhD申请技巧",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "申20中3，靠connection拿到Columbia PhD，分享美国PhD申请中的实操建议。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对美国PhD申请、推荐信策略或跨方向申请有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"PhD申请中connection有多重要？",
			"如何获得有价值的科研推荐信？",
			"跨方向申请PhD该怎么规划？",
		},
		ExpertiseTags: []string{"PhD申请", "Columbia", "EE", "飞跃手册", "推荐信"},
		KnowledgeBody: `22级电子系信息工程，GPA 3.9/4排名5/44，TOEFL 108。申请方向横跨人机交互、外骨骼机器人和脑机接口。申20面6中3，最终去向Columbia EE PhD。核心观点：connection is all you need。影响力排序：connection>科研成果&经历>>GPA>>英语。最强connection是申请对象就是推荐人(return offer)，其次推荐人通过私人联系推荐你。获得科研强推的方法：海外暑研、学期交流、找校内导师引荐。建议大二起积极进实验室，大三争取海外科研机会。文章不是针对学业规划的指导，而是分享已确定硬背景下如何通过策略获得更好结果的实操技巧。`,
	},
	{
		DisplayName:       "航发冲天xw",
		School:            "南方科技大学",
		MajorLine:         "航空航天 直博 @ 清华大学航空发动机研究院",
		ScoreLine:         "GPA 3.77/4, 六级469",
		ArticleTitle:      "南科大飞跃手册 | 航空航天保研清华直博的经验与面经",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "航空航天专业保研清华直博，分享多校夏令营面试经历和导师引荐技巧。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对航空航天保研、清华/北大等名校夏令营有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"航空航天专业保研有哪些好学校？",
			"保研夏令营线上和线下面试有什么区别？",
			"如何让导师帮你引荐保研目标校？",
		},
		ExpertiseTags: []string{"保研", "清华", "航空航天", "飞跃手册", "直博"},
		KnowledgeBody: `17级航空航天工程，GPA 3.77/4(保研时3.76)，六级469。最终保研清华航空发动机研究院直博，另获上交和浙大优秀营员。夏令营面试形式因校而异：西工大五分钟英文自我介绍+交流；上交线上笔试+英文问答+专业知识问答；北大英文自我介绍+专业问答；清华和浙大PPT自我介绍+问答。提前联系导师非常重要——利用南科大师资力量，让自己的导师引荐目标校导师，成功率远高于自己单独联系。如果线上夏令营一定要海投，时间短效率高不容易冲撞。直博需要六级460以上，英语证书要保管好。`,
	},
	{
		DisplayName:       "力学小白jq",
		School:            "南方科技大学",
		MajorLine:         "力学 保研 @ 中国科学技术大学",
		ScoreLine:         "GPA 3.78/4",
		ArticleTitle:      "南科大飞跃手册 | 力学系保研中科大的心路历程",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "优柔寡断中最终下定决心保研，分享从德国暑研到回国保研的转变。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在出国和保研之间犹豫，或对力学专业保研流程有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"力学专业保研需要什么条件？",
			"保研评选中GPA占多大比重？",
			"暑研期间考英语是好时机吗？",
		},
		ExpertiseTags: []string{"保研", "中科大", "力学", "飞跃手册", "暑研"},
		KnowledgeBody: `16级力学系，GPA 3.78/4。德国马普所暑研，最终保研中科大工学院力学专业。一直对未来规划不明确，大三暑假在德国暑研时才开始认真考虑出路。暑研期间体会到在国外的孤独感，加上托福没考好，决定先在国内读研。保研流程：7月系里预报名（只有参加预报名才有正式报名资格），8月正式报名。选拔方法：总GPA占70%，论文竞赛占20%，面试占10%。面试需准备自我介绍、科研经历、为什么选择国内读研和研究方向。建议：想出国就早考英语；没有明确规划就把GPA搞上去，保研时占比70%是硬道理。`,
	},
	{
		DisplayName:       "学渣逆袭yh",
		School:            "南方科技大学",
		MajorLine:         "力学 联培PhD @ 香港城市大学",
		ScoreLine:         "GPA 3.33/4, IELTS 7.0",
		ArticleTitle:      "南科大飞跃手册 | GPA 3.33的自我救赎——联培博士之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "大一大二GPA只有3.18，大三逆袭到3.33后走联培直博，分享低GPA出路。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你GPA不高但仍想深造，或对联培直博有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"GPA低怎么规划升学出路？",
			"联培直博是什么意思？",
			"境外考雅思真的分更高吗？",
		},
		ExpertiseTags: []string{"联培", "低GPA", "香港", "飞跃手册", "逆袭"},
		KnowledgeBody: `16级力学系，GPA 3.33/4（大一大二仅3.18，挂过通识课）。最终去向香港城市大学联培博士。读博前必须想清楚：是内心向往科研还是想早点工作。博士会到接近三十岁才能工作，需考虑家庭情况。大三一年努力提GPA但前期坑太大。暑期通过系里老师推荐去新加坡国家计量中心实习，填补简历空白。建议：大三暑假实习是提升背景的宝贵机会一定要把握。保研报名即使觉得没资格也要报——可能最后有额外名额。在新加坡考雅思口语从5.5飙到7分，强烈建议境外考雅思机考，评分宽松服务好。`,
	},
	{
		DisplayName:       "荷兰机器人rb",
		School:            "南方科技大学",
		MajorLine:         "Robotics MSc @ TU Delft",
		ScoreLine:         "GPA 3.66/4, Rank 9/43, TOEFL 109, GRE 325",
		ArticleTitle:      "南科大飞跃手册 | 机器人方向美欧混申——代尔夫特全奖硕士之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "原计划申美国直博全聚德后转向欧洲，拿到TU Delft加中荷政府全奖硕士。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对机器人方向申请、欧洲硕士或美欧混申策略有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"美国PhD全聚德怎么办？",
			"欧洲硕士申请有什么注意事项？",
			"机器人方向怎么选校？",
		},
		ExpertiseTags: []string{"欧洲留学", "TU Delft", "机器人", "飞跃手册", "混申"},
		KnowledgeBody: `17级机器人工程，GPA 3.66/4排名9/43(申请时14/44)，TOEFL 109，GRE 325。两段国外暑研+推荐信、专利一项、国奖比赛。美欧混申（美国全博士、欧洲全硕士），美国PhD全聚德。最终录取TU Delft机器人学硕士，自行申请拿到中荷政府交换全奖。另获KTH、DTU、Lund、Tel Aviv录取。建议：大一保成绩，大二进实验室+搞定英语，大三暑研+套磁，大四申请。暑研要多跟教授互动争取强推，不要一个人默默干。欧洲硕士申请注意专业对口程度，GPA高可考虑ETH/EPFL。`,
	},
	{
		DisplayName:       "光电暑研zk",
		School:            "南方科技大学",
		MajorLine:         "ECE MS @ GaTech / UPenn / UCSD 等",
		ScoreLine:         "GPA 3.89, TOEFL 104, GRE 322",
		ArticleTitle:      "南科大飞跃手册 | 光电专业ECE Master申请与MS/PhD选择",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "光电方向GPA优异，通过UCI暑研拿到多校ECE Master录取，分享选校和暑研经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对ECE Master申请、MS/PhD选择或暑研有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"MS和PhD该怎么选择？",
			"ECE Master选校看什么因素？",
			"暑研对Master申请有多大帮助？",
		},
		ExpertiseTags: []string{"美国留学", "ECE", "暑研", "飞跃手册", "选校"},
		KnowledgeBody: `16级电子系光电专业，GPA 3.89（前三年），TOEFL 104，GRE 322。无文章，大三暑假UCI官方UCInspire暑研。已获GaTech、UPenn、U of Rochester、UCSD、UCI等校ECE MS录取。MS分两种：MS(学术型，可能含实验室和论文)和MEng(工作导向)。选择MS原因：没找到特别想钻研的方向但想继续读书。选校主要参考USNews排名+地理位置，加州学校多公司多优势大。暑研很重要——最大目标是拿到推荐信。没有文章申MS不用太操心，有文章的神仙大多申PhD了。建议先想清楚目的再准备。GRE建议大一大二先背单词。`,
	},
	{
		DisplayName:       "数字芯片yz",
		School:            "南方科技大学",
		MajorLine:         "微电子 保研 @ 北京大学深圳研究生院",
		ScoreLine:         "GPA 3.88/4, 综合排名1, TOEFL 90+",
		ArticleTitle:      "南科大飞跃手册 | 微电子数字IC方向保研北大深信工的挣扎之旅",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "综合排名第一但夏令营连续被拒，预推免逆袭拿到北大深信工学硕。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对微电子保研、数字IC方向选择或夏令营策略有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"微电子保研的难度排名是怎样的？",
			"夏令营被拒后还有什么机会？",
			"数字IC和模拟IC方向怎么选？",
		},
		ExpertiseTags: []string{"保研", "北大", "数字IC", "飞跃手册", "微电子"},
		KnowledgeBody: `17级深港微电子学院实验班，GPA 3.88/4专业排名6综合排名1，TOEFL 90+。最终保研北大深信工学硕（数字芯片设计方向）。夏令营：本校优营，清华深研院入营没优营，中科院入营没优营，清华微纳/北大信科/复旦/上交微电子均被拒。预推免逆袭：北大深信工、东南、中科院信工、复旦口头offer等。保研难度：学硕>专硕≈直博。微电子申请难度：模拟设计>数字设计>半导体制造>器件设计。导师更愿意收直博学生——IC设计实验周期长。提前联系导师对直博申请至关重要。建议转CS也不是不可能——有计算机课程基础即可。`,
	},
	{
		DisplayName:       "北大IC达人yj",
		School:            "南方科技大学",
		MajorLine:         "微电子 保研 @ 北京大学深圳研究生院",
		ScoreLine:         "GPA 3.85/4, Rank 1/66",
		ArticleTitle:      "南科大飞跃手册 | 电子系微电子保研北大深信工数字IC方向",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "微电子专业排名第一，分享保研选校策略、夏令营面经和提前联系导师的重要性。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对微电子保研选校、面试准备或IC设计方向选择有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"微电子保研有哪些值得去的学校？",
			"北大深信工面试考什么？",
			"想保研外校应该怎么准备？",
		},
		ExpertiseTags: []string{"保研", "北大", "微电子", "飞跃手册", "IC设计"},
		KnowledgeBody: `16级电子系微电子专业，GPA 3.85/4排名1/66，CET6 520+，TOEFL 90+。最终保研北大深信工数字IC设计方向。夏令营：北大深信工优营、清华微电子入营但与北大冲突咕了、北大信科/复旦/上交均被拒。微电子保研值得去的院校：清北复旦上交澳大浙大东南成电西电及中科院各所。清北复交绝对第一梯队。选校时至少留一个能拿offer的备胎。北大信工面试三部分：英语口语(生活学习相关)+专业问题抽题(电路/器件/光电)+个人问题。建议自学数字集成电路基础课程，套磁用gmail邮箱。想保本校强烈建议参加本校夏令营拿预录取。`,
	},
	{
		DisplayName:       "东大修士xg",
		School:            "南方科技大学",
		MajorLine:         "ECE PhD @ NUS / 修士 @ 东京大学",
		ScoreLine:         "GPA 3.83/4, Rank 1/43, TOEFL 107",
		ArticleTitle:      "南科大飞跃手册 | NUS博士+东京大学修士的双线申请",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "电子系排名第一，同时拿到NUS PhD和东大修士全奖，分享新加坡和日本的申请经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对NUS PhD、东京大学申请流程或亚洲PhD有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"NUS ECE PhD申请流程是什么？",
			"东京大学修士怎么申请？",
			"申请前如何跟教授搭上线？",
		},
		ExpertiseTags: []string{"PhD申请", "NUS", "东京大学", "飞跃手册", "亚洲"},
		KnowledgeBody: `15级电子系，GPA 3.83/4排名1/43，TOEFL 107。最终录取NUS ECE PhD和东京大学ME修士(Fellowship)。核心教训：千万别把希望都压在申请季的邮件套磁上。有机会在会议上与教授面对面交流一定要抓住，提前读近期论文准备问题。NUS出结果奇慢需耐心。东京大学IME项目不需要日语，流程特殊：先提交申请→教授审阅→面试→邮寄材料→等待结果。官方禁止提前套磁但建议主动联系。申请材料记得提前准备仔细核对，作者就因拖延症在DDL前才交材料把系填错了。多运用网络资源如寄托天下和一亩三分地。`,
	},
	{
		DisplayName:       "UMN力学zl",
		School:            "南方科技大学",
		MajorLine:         "ME PhD @ University of Minnesota",
		ScoreLine:         "GPA 3.89/4, TOEFL 103, GRE 325",
		ArticleTitle:      "南科大飞跃手册 | 力学系ME PhD申请UMN的经验与选校策略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "力学系高GPA申请美国ME PhD，12月交申请1月就收到UMN Fellowship offer。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对力学系PhD申请、选校策略或SOP写作有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"力学系申PhD可以申哪些专业？",
			"PhD申请中套磁有多重要？",
			"SOP什么时候开始写？",
		},
		ExpertiseTags: []string{"PhD申请", "UMN", "力学", "飞跃手册", "机械"},
		KnowledgeBody: `15级力学系，GPA 3.89/4，TOEFL 103(口语23)，GRE 155V+170Q+3.0AW。最终录取UMN ME PhD(fellowship)，另获Purdue ME PhD AD和Northwestern ME MS AD。力学系申请通常对应对方ME系，也可大胆申BME、AE甚至ChemE——关键看导师方向。做固体力学的可申BME做细胞骨头研究，做流体的可申ChemE多相流。选校参考USNEWS，建议所有申请人合作做各校deadline和要求的excel。SOP要尽早写并不断修改，给每个特别想去的学校单独写。UMN 12月DDL，1月9号就发offer，非常高效。套磁很关键但作者基本没做所以结果不算特别好。`,
	},
	{
		DisplayName:       "圣母转码gc",
		School:            "南方科技大学",
		MajorLine:         "MS CSE @ University of Notre Dame",
		ScoreLine:         "GPA 3.69/4, Rank 17/71, TOEFL 112",
		ArticleTitle:      "南科大飞跃手册 | 微电子转ECE/CS方向——圣母大学硕士申请全记录",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "微电子背景转码申CS/ECE方向，凭借高TOEFL和connection拿到圣母大学CSE录取。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对微电子转CS/ECE、圣母大学或就业导向选校有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"微电子专业可以转申CS硕士吗？",
			"TOEFL 112对申请有多大帮助？",
			"为什么选择出国而不是保研？",
		},
		ExpertiseTags: []string{"美国留学", "转码", "圣母大学", "飞跃手册", "ECE"},
		KnowledgeBody: `19级微电子专业，GPA 3.69/4排名17/71(Top25%)，TOEFL 112。本科科研方向与CS相关，因此申请以CS/ECE项目为主。明确目标：转码→ECE(避开CS激烈竞争)→找工→Master(偏就业导向)。选择学制较长的MS而非MEng以便找实习。最终去向圣母大学MS CSE。出国优势：拓宽文化视野、更好教育质量、更短学制、海外就业前景。保研需要准备竞赛课外活动对GPA容错率低；考研竞争激烈投入产出比不高。综合来看留学仍是大多数人的最优选项。该校在US News排名20，校友网络强大，师生比高。`,
	},
	{
		DisplayName:       "柔性电子h",
		School:            "南方科技大学",
		MajorLine:         "Nanoengineering PhD @ UCSD",
		ScoreLine:         "GPA 3.75/4, Rank 9/68, TOEFL 103",
		ArticleTitle:      "南科大飞跃手册 | 从边缘人到UCSD PhD——暑研逆风翻盘的故事",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "背景不强但通过半年暑研逆袭拿到UCSD PhD fellowship，分享职业规划与暑研策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你觉得自己背景弱但想冲PhD，关于暑研策略和逆袭经验欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"背景弱怎么找到暑研机会？",
			"暑研要做多久才有效果？",
			"转实验室会不会得罪导师？",
		},
		ExpertiseTags: []string{"PhD申请", "UCSD", "暑研", "飞跃手册", "逆袭"},
		KnowledgeBody: `16级电子系，GPA 3.75/4排名9/68，TOEFL 103，GRE 322。申请时两篇挂名SCI两篇共一待投。最终录取UCSD NanoE PhD(fellowship)。三个核心教训：(1)做好职业规划——大一别急着进实验室，先调研清楚方向；(2)及时做取舍——发现方向不合适果断转实验室；(3)逆风翻盘靠暑研——浏览百余所学校筛选40+实验室发套磁信，突出技能和self-funded。最终通过学长引荐获得UCSD暑研，从9点工作到凌晨2-3点，半年后收到教授读博邀请。暑研建议做六个月起步。关键是展现motivation和解决问题的决心。`,
	},
	{
		DisplayName:       "安堡微电mt",
		School:            "南方科技大学",
		MajorLine:         "ECE MS @ University of Michigan Ann Arbor",
		ScoreLine:         "GPA 3.66/4, TOEFL 101",
		ArticleTitle:      "南科大飞跃手册 | 微电子ECE Master申请密歇根安堡经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "GPA不算顶尖但拿到UMich等多校ECE MS录取，分享时间轴和申请心得。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对ECE Master申请、语言准备或申请时间规划有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"ECE Master申请需要多高的GPA？",
			"语言考试什么时候准备最好？",
			"没有暑研经历怎么申请Master？",
		},
		ExpertiseTags: []string{"美国留学", "UMich", "ECE", "飞跃手册", "硕士"},
		KnowledgeBody: `17级微电子专业，GPA 3.66/4，TOEFL 101(口语23)，GRE optional。两篇专利（中美各一），中芯国际实习，校内电赛三等奖。申请全部ECE MS项目。最终录取UMich Ann Arbor ECE MS，另获USC、GaTech、Duke、UCI、Columbia、UW-Seattle录取。时间轴：大一暑期GRE课程，大二准备TOEFL并进课题组，大三暑期中芯国际实习+二战TOEFL，大四9月开始网申。建议最迟大三暑假拿到所有语言成绩——大四同时考试和申请会非常被动。申请本身操作不难但过程繁琐，文书和选校占大量时间。`,
	},
	{
		DisplayName:       "厦大环科hw",
		School:            "南方科技大学",
		MajorLine:         "环境科学 保研 @ 厦门大学",
		ScoreLine:         "GPA 3.76, Rank 2/41",
		ArticleTitle:      "南科大飞跃手册 | 环境系保研厦大——四校夏令营面试全记录",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "环境系排名第二，参加四所学校夏令营，分享不同学校面试风格和选择策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对环境专业保研、夏令营对比或面试准备有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"环境专业保研有哪些好学校？",
			"不同学校夏令营面试有什么区别？",
			"提前联系导师有什么好处？",
		},
		ExpertiseTags: []string{"保研", "厦门大学", "环境科学", "飞跃手册", "夏令营"},
		KnowledgeBody: `17级环境系，GPA 3.76排名2/41，CET4 522，CET6 469。最终保研厦门大学环境科学。申请了四校：厦大(170人入营录60-70)、中山(200+人入营录60-70)、北师大(100+人录40)、广州地化所(50+人)。各校面试风格差异大：中山两天含英语提问，较紧凑；厦大四五天体验最好，含导师单独见面会，面试可中文自我介绍；北师大最紧凑含笔试+口试+个人汇报。建议提前邮件联系意向导师——本科科研和导师方向匹配会大大加分。疫情期线上夏令营入营人数大增但优营名额不变。材料早准备：成绩单、英语成绩、推荐信2封、获奖证书、个人陈述都可以提前写好。`,
	},
	{
		DisplayName:       "哥大暑研jy",
		School:            "南方科技大学",
		MajorLine:         "Columbia LDEO 暑期实习（环境方向）",
		ScoreLine:         "15级环境系",
		ArticleTitle:      "南科大飞跃手册 | 哥伦比亚大学LDEO暑期实习申请攻略与体验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "分享哥伦比亚大学地球科学研究所十周暑期科研实习的申请攻略和生活体验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对哥大LDEO暑期实习、环境方向暑研或美国科研生活有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"哥大LDEO暑期项目怎么申请？",
			"暑期科研十周能做出什么成果？",
			"申请美国J1签证需要什么材料？",
		},
		ExpertiseTags: []string{"暑研", "哥伦比亚大学", "环境", "飞跃手册", "科研实习"},
		KnowledgeBody: `15级环境系同学分享哥伦比亚大学LDEO(拉蒙特-多尔蒂地球观测站)十周暑期科研实习。项目面向大二大三本科生，需修至少两门地球/大气/海洋科学课程和一年微积分。申请材料：成绩单、简历、研究兴趣声明(选三个志愿)、两封推荐信。住宿由哥大安排在校园宿舍(三至六人合住)。流程：第一周参观+定方向，第四周完成proposal，第二个月完整汇报，最后一周做poster展示。需申请J1签证，提前填写DS-160和DS-2019表格。南科大提供1.5万元生活费补助。总花费含签证、机票和生活费约需准备充分。`,
	},
	{
		DisplayName:       "水文博士yi",
		School:            "南方科技大学",
		MajorLine:         "环境PhD @ University of Michigan",
		ScoreLine:         "GPA 3.70/4, TOEFL 98, GRE 317",
		ArticleTitle:      "南科大飞跃手册 | 从UCSC到UMich——一段神奇而幸运的PhD申请故事",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "通过公众号招生信息套磁拿到PhD口头offer，后随导师从UCSC转学至UMich。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对环境方向PhD申请、境外交换或套磁策略有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"如何通过公众号找到PhD机会？",
			"境外交换对申请有什么帮助？",
			"全聚德怎么调整心态？",
		},
		ExpertiseTags: []string{"PhD申请", "UMich", "环境", "飞跃手册", "交换"},
		KnowledgeBody: `18级水文与水资源工程，GPA 3.70/4，TOEFL 98(拼分)，GRE 317。一篇SCI二作、一篇一区top四作、一篇一作在投。多伦多大学学期交换。在公众号"每日更新全奖国外申请资讯"上看到导师招生信息，套磁后拿到口头offer。最初录取UCSC环境PhD，后导师转去UMich遂跟随转学。文章投稿经历坎坷但心态平和后终获接收。建议：追求要热烈心态要平和；多尝试抓住一切可能；做好最坏打算——当准备好面对全聚德时遇到的就都只有幸运。在多大交换期间多做只有在那里才能做的事。`,
	},
	{
		DisplayName:       "代尔夫特argue姐",
		School:            "南方科技大学",
		MajorLine:         "ME MSc @ TU Delft (Biomechanical Design)",
		ScoreLine:         "GPA 3.73/4, Rank 5/31, TOEFL 97",
		ArticleTitle:      "南科大飞跃手册 | 被拒后argue成功翻盘——TU Delft机械硕士申请",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "收到TU Delft拒信后写argue letter成功翻盘拿到录取，分享argue策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你收到拒信想argue，或对欧洲机械硕士申请有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"收到拒信后怎么argue？",
			"TU Delft机械硕士申请难度大吗？",
			"Argue letter怎么写？",
		},
		ExpertiseTags: []string{"欧洲留学", "TU Delft", "argue", "飞跃手册", "机械"},
		KnowledgeBody: `17级机械系，GPA 3.73/4排名5/31，TOEFL 97。申请TU Delft机械工程硕士(生物力学设计方向)。11月提交申请，12月收到拒信：理由是本科课程设置中机械设计经验不足、通识工程课太多。收到拒信后立即写argue letter：(1)分析对方为什么从材料中得出这个结论，(2)补充材料反驳。信中详细描述了被忽略的项目经历，约600词。12月14日发出argue letter，1月5日收到AD成功翻盘。建议：收到拒信不要放弃，先询问具体拒绝原因，针对性地写argue信。提交申请后关注网申系统进度，提前做好心理准备。`,
	},
	{
		DisplayName:       "GaTech力学yz",
		School:            "南方科技大学",
		MajorLine:         "ME PhD @ Georgia Institute of Technology",
		ScoreLine:         "GPA 3.89/4, TOEFL 94, 一篇SCI一作",
		ArticleTitle:      "南科大飞跃手册 | 力学PhD申请GaTech——认清现实放弃幻想",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "力学系高GPA拿到GaTech等多校ME PhD offer，分享套磁策略和签证注意事项。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对ME PhD申请、套磁方法或美国签证问题有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"PhD申请中套磁邮件怎么写？",
			"TOEFL口语不够怎么办？",
			"F-1签证check会影响入学吗？",
		},
		ExpertiseTags: []string{"PhD申请", "GaTech", "力学", "飞跃手册", "套磁"},
		KnowledgeBody: `17级力学系，GPA 3.89/4，TOEFL 94(口语21)，GRE 326(V156+Q170)。一篇SCI一作(IF4.8)。最终录取GaTech ME PhD(可附赠硕士学位)，另获UT-Austin、CU Boulder、HKUST、NEU、Purdue、UCLA AD。被Cornell拒(口语不够23分)。套磁邮件格式：简短自我介绍+学术背景+感兴趣方向+能否成为学生，正文150-250词附CV和成绩单。不回的过段时间再发一次(丢锅给邮箱服务器)。语言成绩越高越好尽早准备。导师是申请路上的贵人要多交流。签证可能check两个月导致延迟入学，拿到I-20就尽快面签。`,
	},
	{
		DisplayName:       "中科院IC侠wz",
		School:            "南方科技大学",
		MajorLine:         "微电子 学硕 @ 中国科学院微电子研究所",
		ScoreLine:         "GPA 3.82/4, Rank 4/66",
		ArticleTitle:      "南科大飞跃手册 | 微电子保研中科院微电子所的面试攻略",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "微电子排名前四，分享中科院、东南、华科、浙大等不同学校的面试经历和技巧。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对微电子保研面试准备或不同学校面试风格有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"保研面试一般考什么内容？",
			"不同学校面试风格差异大吗？",
			"保研有哪三个关键时间节点？",
		},
		ExpertiseTags: []string{"保研", "中科院", "微电子", "飞跃手册", "面试"},
		KnowledgeBody: `16级电子系微电子专业，GPA 3.82/4排名4/66。最终保研中科院微电子研究所学硕，另获东南和华科录取，被浙大拒。保研三个时间节点：(1)夏令营(最早拿offer)，(2)预推免(夏令营后的补录)，(3)九月推免(系统开放后捡漏)。中科院面试：自我介绍→项目提问→专业知识考察，无英语。东南面试：直接英文问答(生活类)+成绩单和简历专业知识考察。浙大信电最严格：七门课笔试+四轮面试(两轮专业+英语阅读理解+项目经历)。面试前一定要复习专业课(成绩单上最好的课和最差的课)，项目细节要非常熟悉。`,
	},
	{
		DisplayName:       "港科联培ry",
		School:            "南方科技大学",
		MajorLine:         "力学 联培PhD @ 香港科技大学",
		ScoreLine:         "GPA 3.67/4, TOEFL 98",
		ArticleTitle:      "南科大飞跃手册 | 力学系联培与自申的选择——港科大PhD之路",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "在保研、联培和自申之间权衡后选择港科大联培PhD，分享选择过程和建议。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在纠结联培、自申还是保研，或对港科大PhD有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"联培PhD和自申PhD有什么区别？",
			"暑研前应该先考出英语成绩吗？",
			"如何向心仪教授推荐自己？",
		},
		ExpertiseTags: []string{"联培", "港科大", "力学", "飞跃手册", "PhD"},
		KnowledgeBody: `16级力学系，GPA 3.67/4，TOEFL 98。最终去向港科大联培博士。正式考虑升学是从暑研开始，感觉有些仓促。建议在暑研之前考到足够高的英语成绩，这样选择毕业去向时更自由。联培需要自己提前联系老师，了解合作老师是否有招生意向。系里联培面试结束后确定名额，合作学校老师可能还会再进行一次面试。自申的重点：关注截止日期(美国名校通常12月截止)，提前统筹想申的学校，关注教授具体研究方向并发邮件联系。建议可以系统性培训英语考试，高强度培训是有效果的。`,
	},
	{
		DisplayName:       "市场大使hh",
		School:            "南方科技大学",
		MajorLine:         "市场/销售方向 @ 深信服",
		ScoreLine:         "16级电子系通信工程",
		ArticleTitle:      "南科大飞跃手册 | 另类求职之路——校园大使到市场岗offer",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "不走技术路线的另类选择，通过校园大使工作拿到4家公司offer，分享面试经验。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你想做市场或产品经理方向的工作，或对面试准备有疑问，欢迎交流。",
		Education:         "本科（已就业）",
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"理工科背景怎么转市场方向？",
			"校园大使对求职有什么帮助？",
			"群面和单面分别怎么应对？",
		},
		ExpertiseTags: []string{"就业", "市场", "面试", "飞跃手册", "校园大使"},
		KnowledgeBody: `16级电子系通信工程。应聘4家公司全部拿到offer，最终签约深信服。走市场方向的另类选择。核心秘诀：先做校园大使。校园大使好处：(1)和业界大牛直接沟通获得方向指导，(2)招聘信息第一个知道知己知彼，(3)横向对比同类公司福利薪水。群面建议：积极参与分享观点但不强硬霸道，关注团队配合和交流，保持自信不要被大神吓到。单面建议：充分准备面经答案(推荐看准网APP)，了解公司文化价值观，具备抗压能力应对压力面。压力面中面试官可能说"你很一般"——不要消极，积极自信回答即可。`,
	},
	{
		DisplayName:       "北大力学ym",
		School:            "南方科技大学",
		MajorLine:         "力学 保研 @ 北京大学工学院",
		ScoreLine:         "GPA 3.84/4",
		ArticleTitle:      "南科大飞跃手册 | 力学系保研北大工学院夏令营面经",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "参加北大工学院夏令营，分享面试黑板答题和流体力学专业考核经历。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对力学保研、北大夏令营面试或美国暑研有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"北大工学院夏令营面试什么形式？",
			"力学系保研外校难吗？",
			"暑研心态不好怎么调整？",
		},
		ExpertiseTags: []string{"保研", "北大", "力学", "飞跃手册", "夏令营"},
		KnowledgeBody: `16级力学系，GPA 3.84/4。最终保研北大工学院流体力学方向。北大夏令营两天：第一天听工学院名师介绍+面试。面试形式：抽两道题(一物理一数学)准备15分钟→英语自我介绍→黑板作答15分钟。对面坐满教授阵容还有录像机。面试题涉及瑕点定积分和拉普拉斯算子在流体力学中的意义(调和函数)。答错被批判也要保持镇定可以说"我没有学过"。搞科研需要良好环境和积极心态。暑研教训：英语没认真准备导致托福不理想，最终进行风险回避型决策选择保研。保研流程：填表→系里排名→学信网系统推荐免试完成。`,
	},
	{
		DisplayName:       "北航暑研hr",
		School:            "南方科技大学",
		MajorLine:         "力学 保研 @ 北京航空航天大学",
		ScoreLine:         "GPA 3.51/4, 专业排名3/8",
		ArticleTitle:      "南科大飞跃手册 | 不参加夏令营的另类保研——荷兰暑研后保研北航",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "跳过夏令营在荷兰暑研三个月，回国后靠暑研经历保研北航能动学院。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你想了解不参加夏令营的保研路线，或对海外暑研转保研有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"没参加夏令营还能保研吗？",
			"海外暑研对保研面试有帮助吗？",
			"航空航天方向保研怎么选校？",
		},
		ExpertiseTags: []string{"保研", "北航", "暑研", "飞跃手册", "航空航天"},
		KnowledgeBody: `16级力学系，GPA 3.51/4，专业排名3/8，系排名11/20。暑假在荷兰代尔夫特理工大学航空航天系暑研三个月，没有参加国内夏令营。暑研机会来源：一位代尔夫特教授来校学术访问时在机场接机认识，系主任建议联系对方。9月拿到推免资格后直接参加北航复试（没走夏令营），暑研经历在面试中帮助很大，成功拿到预录取。经验：一定要胆子大主动争取，分析好想要什么后去争取而不是等安排。连清华都可以尝试套磁——套不到不亏套到就血赚。建议两条腿走路同时准备保研和申请。`,
	},
	{
		DisplayName:       "哥大骑行侠wx",
		School:            "南方科技大学",
		MajorLine:         "Columbia LDEO 暑期科研（大气污染方向）",
		ScoreLine:         "16级环境系",
		ArticleTitle:      "南科大飞跃手册 | 哥伦比亚大学LDEO暑期科研——纽约骑行测空气质量",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "分享在哥大Lamont研究所十周暑期科研项目的申请流程、衣食住行和研究经历。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对哥大LDEO暑研项目的生活和科研细节有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"哥大LDEO暑期项目生活条件怎样？",
			"申请J1签证需要注意什么？",
			"暑期科研十周的日程安排是怎样的？",
		},
		ExpertiseTags: []string{"暑研", "哥伦比亚大学", "大气科学", "飞跃手册", "科研"},
		KnowledgeBody: `16级环境系同学分享哥大LDEO暑期科研项目。项目时长十周(5月底-8月初)，33个实习生来自哥大、纽约社区大学和南科大环境系。住宿在哥大Main Campus，从宿舍到Lamont研究所约一小时。南科大预付住宿费并提供1.5万元生活补助。饮食在Lamont食堂一餐约8-10美元，自己做饭每周30-40美元。流程紧凑：第一周参观培训定方向，第四周proposal口头报告，第二个月完整汇报，最后一周做poster展示。研究课题是骑行评估纽约曼哈顿超微粒子污染，背着设备在曼哈顿环形骑行15英里。需提前申请J1签证和延期期末考试。`,
	},
	{
		DisplayName:       "ETH机器人yz2",
		School:            "南方科技大学",
		MajorLine:         "MS in RSC @ ETH Zürich",
		ScoreLine:         "GPA 3.80/4, Rank 3/74, TOEFL 101, GRE 319",
		ArticleTitle:      "南科大飞跃手册 | 机器人工程申请ETH机器人硕士的超详细选校分析",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "机器人系排名第三，拿到ETH和UMich等8个录取，超详细分析15+个项目的录取特点。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对ETH、机器人方向选校或欧美混申策略有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"ETH机器人硕士录取标准是什么？",
			"机器人方向有哪些好的硕士项目？",
			"UMich和ETH机器人硕士怎么比较？",
		},
		ExpertiseTags: []string{"ETH", "机器人", "选校", "飞跃手册", "欧美"},
		KnowledgeBody: `18级机器人工程，GPA 3.80/4排名3/74，TOEFL 101，GRE 319。有UC Berkeley学期交流/暑研经历。最终录取ETH RSC(机器人、系统与控制硕士)，另获ETH ME、TU Delft Robotics、UMich Robotics、UMich ME、UPenn ME、UC Berkeley MEng、Cornell MEng共8个AD。被EPFL、UPenn Robotics、CMU ME、UMich ECE等7个拒。ETH录取主要看总绩点排名，给生源校配额按排名录取无Waitlist。UMich Robotics是公认好项目资源丰富。建议Master尽量申名校看学校名声。关注CSC等奖学金机会。文书越早写越好。`,
	},
	{
		DisplayName:       "海洋博士yao",
		School:            "南方科技大学",
		MajorLine:         "Marine Science PhD @ USF",
		ScoreLine:         "GPA 3.79/4, Rank 2/28, TOEFL 87",
		ArticleTitle:      "南科大飞跃手册 | 环境系PhD申请——暑研直接拿口头offer的骚操作",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "放弃保研全力自申，通过骚操作拿到暑研和PhD口头offer，分享套磁和申请血泪史。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对环境/海洋方向PhD申请、暑研获取或英语刷分有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"暑研怎么通过导师关系获得？",
			"套磁应该什么时候开始？",
			"TOEFL刷不出分怎么办？",
		},
		ExpertiseTags: []string{"PhD申请", "套磁", "暑研", "飞跃手册", "海洋科学"},
		KnowledgeBody: `15级环境系水文专业，GPA 3.79/4排名2/28，TOEFL 87(刷了多次最高分)，GRE 325。两段在校科研+一段美国暑研+三段交流。最终录取USF海洋科学PhD。放弃综排第一保研选择自申。骚操作：告诉自己的导师"南科大本科生有两次出国交流补助机会不用白不用"，导师帮忙联系到dream school大佬，暑研后直接拿到口头offer。套磁建议"金九银十"，一两天套一个教授，套到再挑。套磁信要读对方文章提出学术观点附上CV和成绩单。TOEFL+GRE共刷十次，英语基础差想出国读博要特别重视。英语不好也可以考虑保研联培。`,
	},
	{
		DisplayName:       "UCI电子jd",
		School:            "南方科技大学",
		MajorLine:         "EE PhD @ UC Irvine",
		ScoreLine:         "GPA 3.74/4, Rank 4/45, TOEFL 94",
		ArticleTitle:      "南科大飞跃手册 | 电子系EE PhD全流程DIY申请经验",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "全程DIY申请EE PhD，分享详细的时间线、文书准备和推荐信策略。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对DIY申请EE PhD、GRE/TOEFL准备或申请材料有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"TOEFL和GRE该怎么安排准备？",
			"DIY申请PhD需要注意什么？",
			"文书对录取影响大吗？",
		},
		ExpertiseTags: []string{"PhD申请", "UCI", "EE", "飞跃手册", "DIY"},
		KnowledgeBody: `15级电子系，GPA 3.74/4排名4/45，TOEFL 94(口语22)，GRE 320。最终录取UCI EE PhD，另获TAMU PhD和NYU MS CE(奖$9000/年)等6个AD，被Rice、UCLA、UCSD、Cornell拒。申请材料：语言(TOEFL/GRE)+文书(CV/SOP/PHS)+推荐信+成绩单。TOEFL目标100+以上9月前考出；GRE可速成先背单词V150+Q165+W3.0起步。SOP对录取影响不如想象大——中规中矩不拖后腿即可。推荐信最重要的是找了解你的老师(暑研导师最佳)。选校参考USNEWS并结合一亩三分地数据。多数学校12月至1月截止。`,
	},
	{
		DisplayName:       "UCLA机械tq",
		School:            "南方科技大学",
		MajorLine:         "ME PhD @ UCLA",
		ScoreLine:         "GPA 3.77/4, TOEFL 107, GRE 321, 一篇SCI一作",
		ArticleTitle:      "南科大飞跃手册 | 机械PhD申请UCLA——三段科研经历如何打造申请优势",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "清华暑研+OSU暑研+MIT交流三段经历助力申请UCLA等多校ME PhD。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对ME PhD申请、多段科研经历积累或美国博士生活有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"多段暑研经历怎么规划？",
			"ME PhD套磁有什么技巧？",
			"申请材料的时间线怎么安排？",
		},
		ExpertiseTags: []string{"PhD申请", "UCLA", "机械工程", "飞跃手册", "暑研"},
		KnowledgeBody: `16级机械系，GPA 3.77/4(排名7/53)，TOEFL 107，GRE 321。清华暑研、OSU暑研、MIT学年交流+推荐信。一篇SCI一作、两项专利。申请17所美国大学ME PhD，最终录取UCLA ME PhD，另获USC ISE PhD(fellowship)、BU ME PhD(fellowship)、WPI offer、UW和UC Davis AD。时间线：6月前考出GT→6-7月选校选教授→8-11月套磁+准备材料→11月-1月填网申。套磁教授需提前看文章了解研究方向再发邮件。12月有教授直接约in-person面试。建议利用南科大暑研和交流机会积累推荐信。`,
	},
	{
		DisplayName:       "CMU机器学zc",
		School:            "南方科技大学",
		MajorLine:         "MS in Machine Learning @ CMU",
		ScoreLine:         "GPA 3.91/4, Rank 1/30, IELTS 7.0, GRE 324",
		ArticleTitle:      "南科大飞跃手册 | 通信工程跨申CMU机器学习硕士的申请故事",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "通信专业排名第一、多篇顶会论文，跨方向申请拿到CMU MSML等六校录取。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对跨专业申请AI/ML方向、CMU多项目申请或顶会论文对申请的作用有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"通信工程可以跨申AI/ML硕士吗？",
			"CMU MSML项目竞争激烈吗？",
			"顶会论文对硕士申请有多大帮助？",
		},
		ExpertiseTags: []string{"美国留学", "CMU", "机器学习", "飞跃手册", "跨专业"},
		KnowledgeBody: `19级电子系通信工程，GPA 3.91/4排名1/30，IELTS 7.0，GRE 324。本科科研均与AI/ML相关：申请时ICLR一作在投、CVPR二三作在投(后两篇CVPR接收)。最终去向CMU MSML(机器学习硕士)，另获CMU MSIN、CMU MSECE、NWU MSCS、Columbia MSCS、UCSD EC93录取。被大量名校拒(Harvard DS、CMU MSCS等)。CMU可同时申多个学院项目增加录取概率。先从Waitlist转正再到录取经历了两个月焦虑等待。跨专业申请关键在于科研产出与目标方向对口，学校名和GPA也很重要。`,
	},
	{
		DisplayName:       "宾大ESE侠yy",
		School:            "南方科技大学",
		MajorLine:         "ESE PhD @ University of Pennsylvania",
		ScoreLine:         "GPA 3.65, Rank 19/51",
		ArticleTitle:      "南科大飞跃手册 | 全聚德到宾大PhD全奖——推荐信的教训与反思",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "第一年全聚德因疑似黑推，换推荐人后第二年直接起飞拿到宾大全奖PhD。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对推荐信策略、全聚德后再申或PhD申请心态有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"如何判断推荐人是否写了黑推？",
			"全聚德后第二年再申值得吗？",
			"如何处理与导师的专业关系？",
		},
		ExpertiseTags: []string{"PhD申请", "宾大", "推荐信", "飞跃手册", "Gap"},
		KnowledgeBody: `20级微电子专业，GPA 3.65排名19/51。大三在圣母大学交流，大四在沙特KAUST做访问学生。2024Fall申请全聚德——有教授侧面提醒可能有两个教授写了黑推。2025Fall换掉推荐人后直接起飞，收到UPenn ESE PhD全奖offer。核心教训：推荐信极其重要，必须确保推荐人写正面推荐。与导师保持专业关系——私人生活和专业生活要分开。科研课题组永远缺劳动力但你需要证明自己是"不费别人力气"的劳动力。提高英语建议浸润式学习而非应试刷题。多出去走走多体验培养自信和适应新环境的能力。`,
	},
	{
		DisplayName:       "UIC通信博wz2",
		School:            "南方科技大学",
		MajorLine:         "CS PhD @ University of Illinois at Chicago",
		ScoreLine:         "GPA 3.77/4, Rank 9/42, TOEFL 91",
		ArticleTitle:      "南科大飞跃手册 | 通信转CS方向PhD申请——为什么要出国读博",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "通信工程转CS方向申请PhD，分享跨专业申博的课程准备和选择思考。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你在考虑出国读博、跨专业申请或PhD与Master的选择，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"通信工程转CS申PhD需要修什么课？",
			"直博和先读硕再读博怎么选？",
			"GPA对博士申请有多重要？",
		},
		ExpertiseTags: []string{"PhD申请", "转CS", "通信", "飞跃手册", "直博"},
		KnowledgeBody: `15级电子系通信工程，GPA 3.77/4排名9/42，TOEFL 91，GRE 312。最终录取UIC CS PhD。通信转CS申请的阻碍：部分项目要求CS本科或特定课程(数据结构、OS、离散数学、计算机组成原理等)。想转CS的同学一定要选上这几门课并拿高分。读博原因：喜欢研究想成为教授或研究员。理想路径是先读硕士再申博——可换专业、获海外推荐信、重新刷GPA、提前感受环境并留退路。但海外硕士费用高(年20-40万)。家庭不能支持读海外硕的同学可直接申fully funded直博或保研缓冲。GPA非常重要包括所有体育思政课。`,
	},
	{
		DisplayName:       "光电科研hy",
		School:            "南方科技大学",
		MajorLine:         "光电信息科学与工程（经验分享）",
		ScoreLine:         "GPA 3.84/4, Rank 6/38",
		ArticleTitle:      "南科大飞跃手册 | 光电专业大学课程学习与本科科研方法论",
		LongBioPrefix:     sustechFeyueLongBioPrefix,
		ShortBio:          "分享大学课程高效学习方法和本科科研入门技巧，帮助低年级同学少走弯路。",
		Audience:          sustechAudience,
		WelcomeMessage:    "你好！如果你对大学课程学习方法、本科科研入门或如何找导师有疑问，欢迎交流。",
		Education:         sustechEducation,
		MajorLabel:        sustechMajorLabel,
		KnowledgeCategory: sustechKnowledgeCat,
		KnowledgeTags:     sustechKnowledgeTags,
		SampleQuestions: []string{
			"大学课程该怎么高效学习？",
			"本科生什么时候开始科研？",
			"怎么找到合适的科研导师？",
		},
		ExpertiseTags: []string{"学习方法", "本科科研", "光电", "飞跃手册", "经验"},
		KnowledgeBody: `21级光电专业，GPA 3.84/4排名6/38。分享课程学习和本科科研方法论。大学课程与高中不同：知识量大、目的是理解知识而非应试。学习方法：课前预习找难点，课上产生疑问先记下课后解决(查教材/问老师/同学/GPT)。大学学到的是20%对口知识+80%自主学习能力。本科科研意义：培养基础科研能力、提前学习领域知识、建立领域理解、发表文章评奖助力申请。找导师方法：先看官网了解教授研究方向，约线下聊天了解——老师都欢迎学生来了解。大胆说出自己的想法和想进哪个组。不要因为老师热情就糊里糊涂进组。`,
	},
}
